[package]
name = "tidepool-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Testing utilities and benchmarks for Tidepool"
publish = false

[dependencies]
tidepool-repr.workspace = true
serde_json = { workspace = true, features = ["float_roundtrip"] }
tidepool-runtime.workspace = true
tidepool-toolchain.workspace = true
tidepool-mcp.workspace = true
tidepool-effect.workspace = true
tidepool-bridge.workspace = true
tidepool-bridge-derive.workspace = true
tidepool-bridge-effects.workspace = true
frunk.workspace = true

[lints]
workspace = true
