[package]
name = "tidepool-optimize"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Optimization passes for Tidepool Core"
readme = "../README.md"

[dependencies]
tidepool-repr.workspace = true
tidepool-eval.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true

[dev-dependencies]
tidepool-testing.workspace = true
proptest.workspace = true
serial_test = "3.4.0"
