{-# LANGUAGE NoImplicitPrelude, OverloadedStrings, DataKinds, TypeOperators, FlexibleContexts, FlexibleInstances, UndecidableInstances, GADTs, PartialTypeSignatures, ScopedTypeVariables, ExtendedDefaultRules, LambdaCase, TupleSections, MultiWayIf, RecordWildCards, NamedFieldPuns, ViewPatterns, BangPatterns, TypeApplications, BlockArguments, NumericUnderscores, MultilineStrings, DeriveFunctor, DeriveFoldable, DeriveTraversable, DeriveGeneric, DeriveAnyClass, QuasiQuotes, DuplicateRecordFields, OverloadedRecordDot, OverloadedLabels #-}
-- GENERATED by the tidepool MCP server from its effect handler
-- declarations. Do not edit; regenerated (content-addressed) at startup.
{-# OPTIONS_GHC -Wno-orphans #-}
module Tidepool.Effects where
import Tidepool.Prelude hiding (error)
import Control.Monad.Fail (MonadFail(..))
import qualified Tidepool.Data.Text as T
import qualified Data.Map.Strict as Map
import qualified Tidepool.Aeson.KeyMap as KM
import qualified Tidepool.Patch as Patch
import Control.Monad.Freer hiding (run)
import Control.Monad.Freer.Internal (Eff(..), qApp, tsingleton)
import Unsafe.Coerce (unsafeCoerce)
import qualified Prelude as P
default (Int, Double, Text)
error :: Text -> a
error = P.error . T.unpack
instance MonadFail (Eff effs) where fail = error . T.pack
liftEither :: P.Show e => Either e a -> Eff effs a
liftEither = either (error . T.pack . P.show) pure

data Console a where
  Print :: Text -> Console ()

data KV a where
  KvGet :: Text -> KV (Maybe Value)
  KvSet :: Text -> Value -> KV ()
  KvDelete :: Text -> KV ()
  KvKeys :: KV [Text]
  KvClear :: Text -> KV Int
  KvKeysP :: Text -> KV [Text]
  KvInfo :: KV Value
  KvCas :: Text -> Maybe Value -> Value -> KV (Either Value ())

data Fs a where
  FsRead :: Text -> Fs (Either FsError Text)
  FsWrite :: Text -> Text -> Fs (Either FsError ())
  FsListDir :: Text -> Fs (Either FsError [Text])
  FsGlob :: Text -> Fs (Either FsError [Text])
  FsGrep :: Text -> Text -> Fs (Either FsError [Hit])
  FsExists :: Text -> Fs (Either FsError Bool)
  FsMetadata :: Text -> Fs (Maybe FileMeta)
  FsReadGlob :: Text -> Fs [FileRead]
  FsHash :: Text -> Fs (Either FsError (Maybe Text))
  FsWriteCas :: Text -> Maybe Text -> Text -> Fs (Either (Maybe Text) ())

data Http a where
  HttpGet :: Text -> Http (Either HttpError Value)
  HttpPost :: Text -> Value -> Http (Either HttpError Value)

data ExecError = ExecSpawn Text | ExecBadDir Text deriving (Show, Eq)
instance ToJSON ExecError where
  toJSON e = case e of
    ExecSpawn detail -> object ["tag" .= ("ExecSpawn" :: Text), "detail" .= detail]
    ExecBadDir detail -> object ["tag" .= ("ExecBadDir" :: Text), "detail" .= detail]

data Exec a where
  Run :: Text -> Exec (Either ExecError Proc)
  RunIn :: Text -> Text -> Exec (Either ExecError Proc)
  RunArgv :: [Text] -> Exec (Either ExecError Proc)

data Position = Position { posLine :: Int, posChar :: Int } deriving (Show, Eq)
data LspNode = LspNode { nodeName :: Text, nodeContainer :: Text, nodeKind :: Text, nodeFile :: Text, nodePos :: Position, nodeText :: Text } deriving (Show, Eq)
data Diag = Diag { diagFile :: Text, diagLine :: Int, diagSeverity :: Text, diagMessage :: Text }
nodeLine :: LspNode -> Int
nodeLine = posLine . nodePos
instance ToJSON Position where
  toJSON (Position l c) = object ["line" .= l, "char" .= c]
instance ToJSON LspNode where
  toJSON nd@(LspNode n c k f _ t) = object ["name" .= n, "container" .= c, "kind" .= k, "file" .= f, "line" .= nodeLine nd, "text" .= t]
instance ToJSON Diag where
  toJSON (Diag f l s m) = object ["file" .= f, "line" .= l, "severity" .= s, "message" .= m]
data LspError = LspDaemonDown Text deriving (Show, Eq)
instance ToJSON LspError where
  toJSON e = case e of
    LspDaemonDown detail -> object ["tag" .= ("LspDaemonDown" :: Text), "detail" .= detail]

data Lsp a where
  LspWhere :: Text -> Lsp (Either LspError [LspNode])
  LspCallers :: LspNode -> Lsp [LspNode]
  LspCallees :: LspNode -> Lsp [LspNode]
  LspRefs :: LspNode -> Lsp [LspNode]
  LspDef :: LspNode -> Lsp (Maybe LspNode)
  LspHover :: LspNode -> Lsp (Maybe Text)
  LspRename :: LspNode -> Text -> Lsp (Maybe Text)
  LspDiagnostics :: Text -> Lsp (Either LspError [Diag])

data Llm a where
  LlmStructured :: Text -> Value -> Llm (Either LlmError Value)

data Git a where
  GitLog :: Int -> Git (Either GitError [Commit])
  GitStatus :: Git (Either GitError [StatusEntry])
  GitDiffStat :: Text -> Git (Either GitError [FileDelta])
  GitShow :: Text -> Git (Either GitError Commit)
  GitLogNumstat :: Int -> Git (Either GitError [CommitDeltas])

data Time a where
  TimeNow :: Time Int

data Schema = SObj [(Text, Schema)] | SArr Schema | SStr | SNum | SBool | SEnum [Text] | SOpt Schema
data Ask a where
  AskWith :: Text -> Value -> Ask Value

data ContextRef = ContextRef Text deriving (Show, Eq)
-- | Why a forked cognition window ended WITHOUT a typed answer.
-- Folded as data at the failing branch's own position (PRD 21
-- locked decision 6) — never an exception that erases the results
-- its siblings already produced. Each constructor carries the
-- runtime's own detail text.
data InvocationExit
  = ExitRoundsExhausted Text
  | ExitNotFinalized Text
  | ExitCancelled Text
  | ExitRuntimeFailure Text
  deriving (Show, Eq)
instance ToJSON InvocationExit where
  toJSON e = case e of
    ExitRoundsExhausted detail -> object ["tag" .= ("ExitRoundsExhausted" :: Text), "detail" .= detail]
    ExitNotFinalized detail -> object ["tag" .= ("ExitNotFinalized" :: Text), "detail" .= detail]
    ExitCancelled detail -> object ["tag" .= ("ExitCancelled" :: Text), "detail" .= detail]
    ExitRuntimeFailure detail -> object ["tag" .= ("ExitRuntimeFailure" :: Text), "detail" .= detail]
data RunLLMTurn a where
  RunLLMTurnWith :: Text -> Value -> RunLLMTurn Value
  RunLLMTurnFreezeWith :: RunLLMTurn ContextRef

data Fork a where
  ForkWith :: Int -> Text -> Fork Value
  ForkAllWith :: Int -> [Text] -> Fork Value

type M = Eff '[Console, KV, Fs, Http, Exec, Lsp, Llm, Git, Time, Ask, RunLLMTurn, Fork]

-- | Emit a line of console output. Thin wrapper over the Print effect
-- so chains never need `send (Print …)`.
say :: Text -> M ()
say = send . Print
-- | `say` on anything Showable (`say . show`).
sayShow :: Show a => a -> M ()
sayShow = say . show
-- | Look up a key; Nothing when absent.
kvGet :: Text -> M (Maybe Value)
kvGet = send . KvGet
-- | Persist a JSON value under a key.
kvSet :: Text -> Value -> M ()
kvSet k v = send (KvSet k v)
-- | Delete a key (no-op when absent).
kvDel :: Text -> M ()
kvDel = send . KvDelete
-- | All keys (unordered; kvKeysP "" for sorted).
kvKeys :: M [Text]
kvKeys = send KvKeys
-- | Delete all keys whose name starts with @prefix@; return the count deleted.
-- Pass "" (empty string) to clear the ENTIRE store — this erases ALL
-- persisted KV data for this server session, so use with caution.
-- Recommended pattern: namespace keys as "ns/key" and clear with "ns/".
-- NOTE: per-session automatic scoping is a deferred design decision (#327);
-- callers manage namespaces manually via this prefix argument.
kvClear :: Text -> M Int
kvClear = send . KvClear
-- | All keys whose name starts with @prefix@, returned sorted.
-- E.g. @kvKeysP "agent/"@ returns @["agent/bar", "agent/foo", ...]@.
-- Pass "" to list ALL keys sorted (like kvKeys but deterministically ordered).
kvKeysP :: Text -> M [Text]
kvKeysP = send . KvKeysP
-- | Summary of KV store state as a JSON Value:
-- @{count :: Int, sample :: [Text], file_size_bytes :: Int}@.
-- Use to inspect junk-drawer accumulation without listing all keys.
-- Extract fields with optics: @i <- kvInfo; i ^? key "count" . _Int@
kvInfo :: M Value
kvInfo = send KvInfo
-- | Atomic compare-and-swap: set @key@ to @new@ only if its current
-- value equals @expected@ (Nothing = require the key ABSENT).
-- @Right ()@ on success; @Left actual@ (the current value) on a
-- mismatch, with nothing written. Cross-process safe (the store
-- file is flocked), so it is the lost-update-free primitive that
-- kvModify\/kvIncr\/kvAppend retry over — prefer those for the
-- common read-modify-write; reach for kvCas directly for a custom
-- conflict policy.
kvCas :: Text -> Maybe Value -> Value -> M (Either Value ())
kvCas k e n = send (KvCas k e n)
-- | Read a file. Failure is TYPED (#335): `Left (FsNotFound p)` / `Left
-- (FsNotUtf8 p)` / `Left (FsIo _)`. The natural spelling unwraps-or-aborts with
-- a failable bind: `Right src <- readFile path` (or `readFile path >>= liftEither`).
readFile :: FilePath -> M (Either FsError Text)
readFile = send . FsRead
-- | Write a file (mkdir -p on the parent). `Left (FsSandbox _)` on a path
-- escape, `Left (FsIo _)` on write failure; unwrap with `liftEither`.
writeFile :: FilePath -> Text -> M (Either FsError ())
writeFile f c = send (FsWrite f c)
-- | Append to a file (reads then writes). Failure is TYPED (#335): a read
-- or write failure comes back as `Left (FsError)` DATA, nothing partially
-- applied; unwrap with `Right () <- appendFile path t` or `>>= liftEither`.
appendFile :: FilePath -> Text -> M (Either FsError ())
appendFile p t = do
  er <- readFile p
  case er of
    Left e -> pure (Left e)
    Right old -> writeFile p (old <> t)
-- | List a directory. `Left (FsNotFound _)` when absent; unwrap with `liftEither`.
listDirectory :: FilePath -> M (Either FsError [FilePath])
listDirectory = send . FsListDir
-- | TOTAL existence predicate (System.Directory semantics): False for a
-- missing path, a directory, or a path outside the sandbox — never throws.
doesFileExist :: FilePath -> M Bool
doesFileExist p = send (FsMetadata p) <&> maybe False (\m -> m.isFile)
-- | TOTAL existence predicate: False for missing/non-dir/out-of-sandbox.
doesDirectoryExist :: FilePath -> M Bool
doesDirectoryExist p = send (FsMetadata p) <&> maybe False (\m -> m.isDir)
-- | File size in bytes, or `Nothing` if the path is missing.
getFileSize :: FilePath -> M (Maybe Int)
getFileSize p = send (FsMetadata p) <&> fmap (\m -> m.size)
-- | File metadata as a `FileMeta` record {size, isFile, isDir}, or `Nothing`
-- if the path is missing/unreadable (use record-dot: `m.size`, `m.isDir`).
fsMeta :: FilePath -> M (Maybe FileMeta)
fsMeta = send . FsMetadata
getCurrentDirectory :: M FilePath
getCurrentDirectory = do { p <- run "pwd" >>= liftEither; pure (T.strip p.stdout) }
-- | Expand a glob to matching file paths. `Left (FsSandbox _)` on an empty
-- or absolute pattern, `Left (FsNotFound _)` on a missing search root; unwrap
-- with `Right ps <- glob pat` or `glob pat >>= liftEither`.
glob :: FilePath -> M (Either FsError [FilePath])
glob = send . FsGlob
-- | Regex-search files matching a path glob. ARG ORDER: regex FIRST, glob
-- SECOND — a path glob like "*.rs" goes in arg 2, not arg 1. Returns [Hit]
-- {path, line, text} (the shared Hit shape, so it composes with
-- hitsByFile/refs). Failure is typed: `Left (FsBadRegex _)` on a bad regex.
-- NB regex metachars are double-escaped here (JSON x Haskell), so a literal dot
-- needs four backslashes; the FsBadRegex detail shows the exact form.
grepGlob :: Text -> FilePath -> M (Either FsError [Hit])
grepGlob pat g = send (FsGrep pat g)
-- | Read every file matching a glob with PER-FILE failure isolation: one
-- `FileRead {path, contents}` per match — `contents` is `Right text` on a clean
-- UTF-8 read, `Left err` on a per-file failure (binary / non-UTF-8, permission).
-- One bad file (e.g. a binary swept up by a wide glob) does NOT fail the whole
-- batch. An empty glob is rejected loudly, but a glob matching NOTHING yields
-- `[]` silently — check `null rs` when absence itself is the signal. Recover
-- the readable files with
-- `[r.path | r <- rs, isRight r.contents]`, or split all outcomes with
-- `partitionEithers (map (.contents) rs)`.
readGlob :: Text -> M [FileRead]
readGlob = send . FsReadGlob
-- | Exact str-replace, EXACTLY-ONCE. Reports the outcome as an
-- `UpdateOneOutcome` DATA value (never throws, mirrors `InsertAfterOutcome`):
-- empty `old`, a missing file, `old` not found, or `old` matching 2+ places
-- is `UpdateOneRejected` (nothing written); otherwise `UpdateOneApplied`.
-- Pass enough surrounding text that `old` is unique. Use planUpdate to review
-- the diff first; the full editing surface is in tidepool://edits.
update :: FilePath -> Text -> Text -> M UpdateOneOutcome
update path old new
  | T.null old = pure (UpdateOneRejected "'old' must be non-empty" Nothing)
  | otherwise = do
      er <- readFile path
      case er of
        Left e -> pure (UpdateOneRejected ("file not found: " <> show e) Nothing)
        Right src ->
          case len (T.splitOn old src) - 1 of
            0 -> pure (UpdateOneRejected ("'old' not found in " <> path) Nothing)
            1 -> writeFile path (replace old new src) >>= liftEither >> pure UpdateOneApplied
            n -> pure (UpdateOneRejected ("'old' matches " <> show n <> " places in " <> path <> " (add surrounding context to disambiguate)") (Just n))
-- | Replace EVERY occurrence of `old` with `new`. Reports the outcome as an
-- `UpdateAllOutcome` DATA value (never throws): empty `old`, a missing file,
-- or zero matches is `UpdateAllRejected` (nothing written); otherwise
-- `UpdateAllApplied` carries the replacement count.
updateAll :: FilePath -> Text -> Text -> M UpdateAllOutcome
updateAll path old new
  | T.null old = pure (UpdateAllRejected "'old' must be non-empty")
  | otherwise = do
      er <- readFile path
      case er of
        Left e -> pure (UpdateAllRejected ("file not found: " <> show e))
        Right src ->
          let n = len (T.splitOn old src) - 1
          in if n == 0
               then pure (UpdateAllRejected ("'old' not found in " <> path))
               else writeFile path (replace old new src) >>= liftEither >> pure (UpdateAllApplied n)
-- | Dry-run `update`: returns an `UpdateOutcome` (the review diff, or the
-- reason it can't apply), writes NOTHING. Never errors — the conflict comes
-- back as data so you can branch before committing.
planUpdate :: FilePath -> Text -> Text -> M UpdateOutcome
planUpdate path old new = do
  er <- readFile path
  case er of
    Left e -> pure (UpdateRejected ("file not found: " <> show e) Nothing)
    Right src ->
      let n = if T.null old then 0 else len (T.splitOn old src) - 1
      in if T.null old then pure (UpdateRejected "'old' must be non-empty" Nothing)
         else if n == 0 then pure (UpdateRejected "not found" Nothing)
         else if n > 1 then pure (UpdateRejected "ambiguous" (Just n))
         else case Patch.genPatch path src (replace old new src) of
                Left _ -> pure UpdateNoChange
                Right fp -> pure (UpdateDiff (Patch.renderPatch [fp]))
-- | `update` from the input lane: {file, old, new} (for big/quote-heavy
-- fragments). Reports the outcome as an `UpdateOneOutcome` DATA value (never
-- throws, same contract as `update`): a malformed payload (missing or
-- non-string file/old/new key) is `UpdateOneRejected` — one bad item never
-- aborts a batch.
updateJ :: Value -> M UpdateOneOutcome
updateJ v = case (v ^? key "file" . _String, v ^? key "old" . _String, v ^? key "new" . _String) of
  (Just f, Just o, Just n) -> update f o n
  _ -> pure (UpdateOneRejected "updateJ: need {file, old, new} strings in input" Nothing)
-- | Insert a block after the unique line containing `anchor`. Reports the
-- outcome as an `InsertAfterOutcome` DATA value (never throws): a missing
-- file, or an anchor matching zero or 2+ lines, is `InsertAfterRejected`
-- (nothing written); otherwise `InsertAfterApplied`.
insertAfter :: FilePath -> Text -> Text -> M InsertAfterOutcome
insertAfter path anchor block = do
  er <- readFile path
  case er of
    Left e -> pure (InsertAfterRejected ("file not found: " <> show e) Nothing)
    Right src ->
      let ls = lines src
          n = len (filter (isInfixOf anchor) ls)
      in case n of
           1 -> writeFile path (unlines (concatMap (\l -> if anchor `isInfixOf` l then [l, block] else [l]) ls))
                  >>= liftEither >> pure InsertAfterApplied
           _ -> pure (InsertAfterRejected ("anchor matched " <> show n <> " lines in " <> path) (Just n))
-- | Compute-check-commit: write only if every named check holds; failures
-- come back as a `WriteOutcome` (nothing written on failure).
writeChecked :: FilePath -> [(Text, Bool)] -> Text -> M WriteOutcome
writeChecked path checks content = do
  let failed = [name | (name, ok) <- checks, not ok]
  if null failed
    then writeFile path content >>= liftEither >> pure (Written path (length checks))
    else pure (WriteBlocked path failed)
-- | Blake3 content hash (hex) of a file, or Nothing if it does not exist.
-- The compare-and-swap token for writeCheckedIf: read it, compute your new
-- content, then write back only if the file still hashes the same.
fileHash :: FilePath -> M (Maybe Text)
fileHash p = send (FsHash p) >>= liftEither
-- | Content-hash compare-and-swap write (#330). Writes CONTENT only if the
-- file's current blake3 hash equals EXPECTED (Nothing = expect the file ABSENT,
-- i.e. create-only). The compare-and-write is atomic within the handler, closing
-- the lost-update race between parallel agents. Returns a WriteOutcome: 'Written'
-- on success, or 'WriteConflict' (carrying expected vs actual hash) if the
-- precondition failed — conflicts come back as DATA, nothing is written. Get
-- EXPECTED from fileHash; on a conflict re-read, recompute, and retry.
writeCheckedIf :: Maybe Text -> FilePath -> Text -> M WriteOutcome
writeCheckedIf expected path content = do
  r <- send (FsWriteCas path expected content)
  pure $ case r of
    Right () -> Written path 1
    Left actual -> WriteConflict path expected actual
-- | Fetch JSON from an HTTP endpoint. Failure is TYPED (#335): `Left
-- (HttpStatus code body)` on a non-2xx response, `Left (HttpNetwork _)`
-- on a network failure. Unwrap with `Right v <- httpGet url` or `>>= liftEither`.
httpGet :: Text -> M (Either HttpError Value)
httpGet = send . HttpGet
-- | POST a JSON body; returns the response Value (see `httpGet` for the
-- failure shape).
httpPost :: Text -> Value -> M (Either HttpError Value)
httpPost url body = send (HttpPost url body)
-- | Run a shell command; returns a `Proc` record {exitCode, stdout, stderr}
-- (use `ok p` for the zero-exit check). Failure is TYPED (#335): `Left
-- (ExecSpawn _)` when the process can't be spawned, `Left (ExecBadDir _)`
-- for `runIn` with a bad/escaping directory. A nonzero EXIT is NOT a
-- failure — inspect `p.exitCode`. Natural spelling: `Right p <- run cmd`.
run :: Text -> M (Either ExecError Proc)
run = send . Run
runIn :: Text -> Text -> M (Either ExecError Proc)
runIn dir cmd = send (RunIn dir cmd)
runArgv :: [Text] -> M (Either ExecError Proc)
runArgv = send . RunArgv
-- | Seed: every workspace definition named X (each a LspNode with container/file/line/source line).
-- `Left (LspDaemonDown _)` when the daemon isn't reachable; unwrap with `>>= liftEither`.
lspWhere :: Text -> M (Either LspError [LspNode])
lspWhere = send . LspWhere
-- | Incoming calls; [] = none (or node not callable). A daemon-down failure
-- aborts the eval structurally (not a silent []) — see the Lsp effect description.
lspCallers :: LspNode -> M [LspNode]
lspCallers = send . LspCallers
-- | Outgoing calls; [] = none (or node not callable).
lspCallees :: LspNode -> M [LspNode]
lspCallees = send . LspCallees
-- | Use sites of this node's symbol (kind = "reference"); [] = none (or not a symbol).
lspRefs :: LspNode -> M [LspNode]
lspRefs = send . LspRefs
-- | Resolve any node (e.g. a use site) to its definition node.
lspDef :: LspNode -> M (Maybe LspNode)
lspDef = send . LspDef
-- | Type / signature / docs for a node.
lspHover :: LspNode -> M (Maybe Text)
lspHover = send . LspHover
-- | Rename a node's symbol to NEW; returns a unified diff (apply with applyDiff). Nothing = can't rename.
lspRename :: LspNode -> Text -> M (Maybe Text)
lspRename n new = send (LspRename n new)
-- | Diagnostics (errors / warnings) for FILE. `Left (LspDaemonDown _)`
-- when the daemon isn't reachable; unwrap with `>>= liftEither`.
lspDiags :: FilePath -> M (Either LspError [Diag])
lspDiags = send . LspDiagnostics
-- | Call the LLM for structured output. Failure is TYPED and TOTAL
-- (#335): `Left (LlmApi _)` on an API/network failure, `Left (LlmRefusal
-- _)` on a declined answer, `Left LlmBudget` when the per-eval call budget
-- is exhausted — none of these abort the eval. Unwrap with `Right v <- llm
-- schema prompt` or `>>= liftEither`.
llm :: Schema -> Text -> M (Either LlmError Value)
llm schema prompt = send (LlmStructured prompt (schemaToValue schema))
findTally :: Eq a => a -> [(a, Int)] -> Maybe [(a, Int)]
findTally _ [] = Nothing
findTally x ((k, n):rest) = if x == k then Just ((k, n + 1) : rest) else case findTally x rest of { Just rest' -> Just ((k, n) : rest'); Nothing -> Nothing }
tallyList :: Eq a => [a] -> [(a, Int)]
tallyList = foldl' (\acc x -> case findTally x acc of { Just acc' -> acc'; Nothing -> acc ++ [(x, 1)] }) []
-- | Last N commits, newest-first. Each 'Commit' carries sha/subject/author/date/files.
gitLog :: Int -> M (Either GitError [Commit])
gitLog = send . GitLog
-- | Working-tree status. Each 'StatusEntry' has path and 2-char XY state code
-- (e.g. "M ", "??", "A ").
gitStatus :: M (Either GitError [StatusEntry])
gitStatus = send GitStatus
-- | Per-file diff stats. THE ARGUMENT IS A REVSPEC COMPARED AGAINST THE WORKING
-- TREE, not "commit vs its parent" — `gitDiffStat sha` on a clean tree is
-- `Right []` (correct data, not an error). For "what did this commit change",
-- pass a RANGE: `gitDiffStat (sha <> "~1.." <> sha)` (also "main..HEAD",
-- "HEAD~3..HEAD"). For bulk per-commit history, use `gitLogNumstat` instead —
-- one subprocess for N commits, no per-commit mapM. 'FileDelta' carries
-- path/adds/dels/binary.
gitDiffStat :: Text -> M (Either GitError [FileDelta])
gitDiffStat = send . GitDiffStat
-- | Single commit by revspec. `Left (GitBadRevspec _)` on an unknown or
-- ambiguous revspec; unwrap with `Right c <- gitShow rev` or `>>= liftEither`.
gitShow :: Text -> M (Either GitError Commit)
gitShow = send . GitShow
-- | Last N commits, newest-first, EACH PAIRED WITH ITS OWN per-file numstat
-- deltas — one subprocess for all N, in place of `gitLog` followed by a
-- per-commit `mapM gitDiffStat`. 'CommitDeltas' carries {commit, deltas};
-- a merge or otherwise-empty commit has `deltas = []`. A renamed file records
-- only its NEW path.
gitLogNumstat :: Int -> M (Either GitError [CommitDeltas])
gitLogNumstat = send . GitLogNumstat
-- | Current UTC time as an opaque UTCTime (epoch-millisecond resolution).
getCurrentTime :: M UTCTime
getCurrentTime = UTCTime <$> send TimeNow
ask :: Schema -> Text -> M Value
ask schema prompt = send (AskWith prompt (object ["schema" .= schemaToValue schema]))
isOpt :: Schema -> Bool
isOpt (SOpt _) = True
isOpt _ = False
innerSchema :: Schema -> Schema
innerSchema (SOpt s) = s
innerSchema s = s
schemaToValue :: Schema -> Value
schemaToValue SStr = object ["type" .= ("string" :: Text)]
schemaToValue SNum = object ["type" .= ("number" :: Text)]
schemaToValue SBool = object ["type" .= ("boolean" :: Text)]
schemaToValue (SEnum vs) = object ["type" .= ("string" :: Text), "enum" .= vs]
schemaToValue (SArr item) = object ["type" .= ("array" :: Text), "items" .= schemaToValue item]
schemaToValue (SOpt s) = schemaToValue s
schemaToValue (SObj fields) = object ["type" .= ("object" :: Text), "properties" .= object (map (\(k,s) -> k .= schemaToValue (innerSchema s)) fields), "required" .= map fst (filter (not . isOpt . snd) fields)]
{-# OPAQUE runLLMTurn #-}
runLLMTurn :: forall a effs. Member RunLLMTurn effs => Text -> Eff effs a
runLLMTurn prompt = runLLMTurnSited 0 prompt
{-# OPAQUE runLLMTurnFork #-}
runLLMTurnFork :: forall a effs. Member RunLLMTurn effs => Text -> Eff effs (Either InvocationExit a)
runLLMTurnFork prompt = runLLMTurnForkSited 0 prompt
{-# OPAQUE runLLMTurnFanout #-}
runLLMTurnFanout :: forall a effs. Member RunLLMTurn effs => [Text] -> Eff effs [Either InvocationExit a]
runLLMTurnFanout prompts = runLLMTurnFanoutSited 0 prompts
renderInvocationExit :: InvocationExit -> Text
renderInvocationExit (ExitRoundsExhausted d) = "round exhaustion: " <> d
renderInvocationExit (ExitNotFinalized d) = "non-finalization: " <> d
renderInvocationExit (ExitCancelled d) = "cancelled: " <> d
renderInvocationExit (ExitRuntimeFailure d) = "runtime failure: " <> d
{-# OPAQUE runLLMTurnSited #-}
runLLMTurnSited :: forall a effs. Member RunLLMTurn effs => Int -> Text -> Eff effs a
runLLMTurnSited sid p = unsafeCoerce <$> send (RunLLMTurnWith p (object ["typedSite" .= sid]))
{-# OPAQUE runLLMTurnForkSited #-}
runLLMTurnForkSited :: forall a effs. Member RunLLMTurn effs => Int -> Text -> Eff effs (Either InvocationExit a)
runLLMTurnForkSited sid p = unsafeCoerce <$> send (RunLLMTurnWith p (object ["typedSite" .= sid, "fork" .= True]))
{-# OPAQUE runLLMTurnFanoutSited #-}
runLLMTurnFanoutSited :: forall a effs. Member RunLLMTurn effs => Int -> [Text] -> Eff effs [Either InvocationExit a]
runLLMTurnFanoutSited sid prompts = unsafeCoerce <$> send (RunLLMTurnWith (intercalate "\n" prompts) (object ["typedSite" .= sid, "fork" .= True, "fan" .= length prompts, "prompts" .= prompts]))
-- | Mint a capability naming THIS window's current frozen
-- prefix (PRD 21 locked decision 2: children fork the frozen
-- post-coalgebra context). Immediate — no operator, no model
-- round (ReadState's service shape). Possession is permission:
-- a ContextRef only ever comes from here or from
-- runLLMTurnBranch's own return; an unrecognized one is refused
-- by the driver as a typed error, never a silent fresh-root
-- fallback.
freezeContext :: forall effs. Member RunLLMTurn effs => Eff effs ContextRef
freezeContext = send RunLLMTurnFreezeWith
{-# OPAQUE runLLMTurnBranch #-}
runLLMTurnBranch :: forall a effs. Member RunLLMTurn effs => ContextRef -> Text -> Eff effs (Either InvocationExit (a, ContextRef))
runLLMTurnBranch ref p = runLLMTurnBranchSited 0 ref p
{-# OPAQUE runLLMTurnBranchSited #-}
runLLMTurnBranchSited :: forall a effs. Member RunLLMTurn effs => Int -> ContextRef -> Text -> Eff effs (Either InvocationExit (a, ContextRef))
runLLMTurnBranchSited sid (ContextRef ref) p = unsafeCoerce <$> send (RunLLMTurnWith p (object ["typedSite" .= sid, "branch" .= True, "ref" .= ref]))
{-# OPAQUE runLLMTurnBranchLabeled #-}
runLLMTurnBranchLabeled :: forall a effs. Member RunLLMTurn effs => Text -> ContextRef -> Text -> Eff effs (Either InvocationExit (a, ContextRef))
runLLMTurnBranchLabeled label ref p = runLLMTurnBranchLabeledSited 0 label ref p
{-# OPAQUE runLLMTurnBranchLabeledSited #-}
runLLMTurnBranchLabeledSited :: forall a effs. Member RunLLMTurn effs => Int -> Text -> ContextRef -> Text -> Eff effs (Either InvocationExit (a, ContextRef))
runLLMTurnBranchLabeledSited sid label (ContextRef ref) p = unsafeCoerce <$> send (RunLLMTurnWith p (object ["typedSite" .= sid, "branch" .= True, "ref" .= ref, "label" .= label]))
{-# OPAQUE runLLMTurnBranchFanout #-}
runLLMTurnBranchFanout :: forall a effs. Member RunLLMTurn effs => ContextRef -> [(Text, Text)] -> Eff effs [Either InvocationExit (a, ContextRef)]
runLLMTurnBranchFanout ref labeledPrompts = runLLMTurnBranchFanoutSited 0 ref labeledPrompts
{-# OPAQUE runLLMTurnBranchFanoutSited #-}
runLLMTurnBranchFanoutSited :: forall a effs. Member RunLLMTurn effs => Int -> ContextRef -> [(Text, Text)] -> Eff effs [Either InvocationExit (a, ContextRef)]
runLLMTurnBranchFanoutSited sid (ContextRef ref) labeledPrompts = unsafeCoerce <$> send (RunLLMTurnWith (intercalate "\n" (map snd labeledPrompts)) (object ["typedSite" .= sid, "branchFanout" .= True, "ref" .= ref, "labels" .= map fst labeledPrompts, "prompts" .= map snd labeledPrompts, "fan" .= length labeledPrompts]))
{-# OPAQUE forkSited #-}
forkSited :: forall a effs. Member Fork effs => Int -> Text -> Eff effs a
forkSited sid brief = unsafeCoerce <$> send (ForkWith sid brief)
{-# OPAQUE forkAllSited #-}
forkAllSited :: forall a effs. Member Fork effs => Int -> [Text] -> Eff effs [a]
forkAllSited sid prompts = unsafeCoerce <$> send (ForkAllWith sid prompts)
