{-# LANGUAGE NoImplicitPrelude, OverloadedStrings, DataKinds, TypeOperators, FlexibleContexts, FlexibleInstances, UndecidableInstances, GADTs, KindSignatures, RankNTypes, PartialTypeSignatures, ScopedTypeVariables, ExtendedDefaultRules, LambdaCase, TupleSections, MultiWayIf, RecordWildCards, NamedFieldPuns, ViewPatterns, BangPatterns, TypeApplications, BlockArguments, NumericUnderscores, MultilineStrings, DeriveFunctor, DeriveFoldable, DeriveTraversable, DeriveGeneric, DeriveAnyClass, QuasiQuotes, DuplicateRecordFields, OverloadedRecordDot, OverloadedLabels #-}
-- GENERATED by the tidepool MCP server from its effect handler
-- declarations. Do not edit; regenerated (content-addressed) at startup.
-- UNIVERSAL STABLE effect vocabulary (no executable row, no `type M`) —
-- see tidepool-mcp/CLAUDE.md's generated-effects section.
{-# OPTIONS_GHC -Wno-orphans #-}
module Tidepool.Effects.Core where
import Tidepool.Prelude hiding (error)
import Control.Monad.Fail (MonadFail(..))
import Data.Void (Void)
import Data.Kind (Type)
import Tidepool.Internal.ActorRef (ExitRef)
import qualified Tidepool.Data.Text as T
import qualified Data.Map.Strict as Map
import qualified Tidepool.Aeson.KeyMap as KM
import qualified Tidepool.Patch as Patch
import Control.Monad.Freer hiding (run)
import Control.Monad.Freer.Internal (Eff(..), qApp, tsingleton)
import Unsafe.Coerce (unsafeCoerce)
import qualified Prelude as P
default (Int, Double, Text)
error :: Text -> a
error = P.error . T.unpack
instance MonadFail (Eff effs) where fail = error . T.pack
liftEither :: P.Show e => Either e a -> Eff effs a
liftEither = either (error . T.pack . P.show) pure

data Console a where
  Print :: Text -> Console ()

data KV a where
  KvGet :: Text -> KV (Maybe Value)
  KvSet :: Text -> Value -> KV ()
  KvDelete :: Text -> KV ()
  KvKeys :: KV [Text]
  KvClear :: Text -> KV Int
  KvKeysP :: Text -> KV [Text]
  KvInfo :: KV Value
  KvCas :: Text -> Maybe Value -> Value -> KV (Either Value ())

data FsRead a where
  FsRead :: Text -> FsRead (Either FsError Text)
  FsListDir :: Text -> FsRead (Either FsError [Text])
  FsGlob :: Text -> FsRead (Either FsError [Text])
  FsGrep :: Text -> Text -> FsRead (Either FsError [Hit])
  FsExists :: Text -> FsRead (Either FsError Bool)
  FsMetadata :: Text -> FsRead (Maybe FileMeta)
  FsReadGlob :: Text -> FsRead [FileRead]
  FsHash :: Text -> FsRead (Either FsError (Maybe Text))

data FsWrite a where
  FsWrite :: Text -> Text -> FsWrite (Either FsError ())
  FsWriteCas :: Text -> Maybe Text -> Text -> FsWrite (Either (Maybe Text) ())

data Http a where
  HttpGet :: Text -> Http (Either HttpError Value)
  HttpPost :: Text -> Value -> Http (Either HttpError Value)

data Git a where
  GitLog :: Int -> Git (Either GitError [Commit])
  GitStatus :: Git (Either GitError [StatusEntry])
  GitDiffStat :: Text -> Git (Either GitError [FileDelta])
  GitShow :: Text -> Git (Either GitError Commit)
  GitLogNumstat :: Int -> Git (Either GitError [CommitDeltas])

data Time a where
  TimeNow :: Time Int

data Entropy a where
  EntropySeed :: Entropy Int

data Meta a where
  MetaConstructors :: Meta [(Text, Int)]
  MetaLookupCon :: Text -> Meta (Maybe (Int, Int))
  MetaPrimOps :: Meta [Text]
  MetaEffects :: Meta [Text]
  MetaDiagnostics :: Meta [Text]
  MetaVersion :: Meta Text
  MetaHelp :: Meta [Text]

data Ask a where
  AskWith :: Text -> Value -> Ask Value

data Llm a where
  LlmStructured :: Text -> Value -> Llm (Either LlmError Value)

data AgentId = AgentId Int deriving (Show, Eq)
data BackendThreadId = BackendThreadId Text deriving (Show, Eq)
data SpawnWorkspace = SpawnNewWorktree WorktreeSpec | SpawnExistingWorktree WorktreeId deriving (Show, Eq)
data SpawnSpec = SpawnSpec { spawnWorkspace :: SpawnWorkspace, spawnAgentLabel :: Text, spawnTask :: Text } deriving (Show, Eq)
data SpawnStage = StageAllocating | StageWorktreeReady | StageBound | StageThreadAccepted | StageRunning deriving (Show, Eq)
data BackendFailure = BackendUnavailable Text | ProtocolRejected Text | RunFailed Text deriving (Show, Eq)
data CyclePayload = PayloadStructured Value | PayloadUnstructured Text | PayloadAbsent deriving (Show, Eq)
data WorkerRun = WorkerRun { runAgent :: AgentId, runWorktree :: WorktreeHandle, runThread :: BackendThreadId } deriving (Show, Eq)
data AgentActivity = ActivityCommand Text (Maybe Int) | ActivityFileChanged Text deriving (Show, Eq)
data TokenUsage = TokenUsage { usageInput :: Int, usageCachedInput :: Int, usageOutput :: Int, usageReasoningOutput :: Int, usageTotal :: Int } deriving (Show, Eq)
data SpawnReceipt = SpawnReceipt { receiptAgent :: AgentId, receiptWorktree :: WorktreeId, receiptBindingRef :: Text, receiptThread :: BackendThreadId, receiptModel :: Text, receiptTurn :: Text, receiptRounds :: Int, receiptUsage :: Maybe TokenUsage } deriving (Show, Eq)
data SpawnOutcome = SpawnOutcome { outcomeRun :: WorkerRun, outcomePayload :: CyclePayload, outcomeReceipt :: SpawnReceipt, outcomeActivity :: [AgentActivity] } deriving (Show, Eq)
data AgentStep = StepToolCall AgentId Text Text Value | StepDone SpawnOutcome deriving (Show, Eq)
instance ToJSON SpawnStage where toJSON s = toJSON (show s)
instance ToJSON BackendFailure where { toJSON (BackendUnavailable t) = object ["backendUnavailable" .= t]; toJSON (ProtocolRejected t) = object ["protocolRejected" .= t]; toJSON (RunFailed t) = object ["runFailed" .= t] }
data CycleId = CycleId Int deriving (Show, Eq)
instance ToJSON CycleId where toJSON (CycleId n) = toJSON n
data SpawnError = SpawnWorktreeFailed SpawnStage WorktreeError | SpawnBindingFailed SpawnStage WorktreeError | SpawnBackendFailed SpawnStage BackendFailure | SpawnRollbackFailed SpawnStage Text Text | SpawnResultMalformed Text | SpawnDriveFailed SpawnStage Text | SpawnCapacityExhausted Int | SpawnCancelled CycleId deriving (Show, Eq)
instance ToJSON SpawnError where
  toJSON e = case e of
    SpawnWorktreeFailed stage worktreeFailure -> object ["tag" .= ("SpawnWorktreeFailed" :: Text), "stage" .= stage, "worktreeFailure" .= worktreeFailure]
    SpawnBindingFailed bindStage bindingFailure -> object ["tag" .= ("SpawnBindingFailed" :: Text), "bindStage" .= bindStage, "bindingFailure" .= bindingFailure]
    SpawnBackendFailed backendStage backendFailure -> object ["tag" .= ("SpawnBackendFailed" :: Text), "backendStage" .= backendStage, "backendFailure" .= backendFailure]
    SpawnRollbackFailed rollbackStage originalFailure rollbackFailure -> object ["tag" .= ("SpawnRollbackFailed" :: Text), "rollbackStage" .= rollbackStage, "originalFailure" .= originalFailure, "rollbackFailure" .= rollbackFailure]
    SpawnResultMalformed malformedDetail -> object ["tag" .= ("SpawnResultMalformed" :: Text), "malformedDetail" .= malformedDetail]
    SpawnDriveFailed driveStage driveDetail -> object ["tag" .= ("SpawnDriveFailed" :: Text), "driveStage" .= driveStage, "driveDetail" .= driveDetail]
    SpawnCapacityExhausted capacityLimit -> object ["tag" .= ("SpawnCapacityExhausted" :: Text), "capacityLimit" .= capacityLimit]
    SpawnCancelled cancelledCycle -> object ["tag" .= ("SpawnCancelled" :: Text), "cancelledCycle" .= cancelledCycle]

data Subagent a where
  SubagentSpawn :: SpawnSpec -> Value -> Subagent (Either SpawnError SpawnOutcome)
  SubagentBegin :: SpawnSpec -> Value -> Value -> Subagent (Either SpawnError AgentStep)
  SubagentResume :: AgentId -> Text -> Bool -> Value -> Subagent (Either SpawnError AgentStep)
  SubagentSpawnAsync :: SpawnSpec -> Value -> Subagent (Either SpawnError CycleId)
  SubagentAwait :: CycleId -> Subagent (Either SpawnError SpawnOutcome)
  SubagentCancel :: CycleId -> Subagent ()

data ExecError = ExecSpawn Text | ExecBadDir Text | ExecTimeout Text deriving (Show, Eq)
instance ToJSON ExecError where
  toJSON e = case e of
    ExecSpawn detail -> object ["tag" .= ("ExecSpawn" :: Text), "detail" .= detail]
    ExecBadDir detail -> object ["tag" .= ("ExecBadDir" :: Text), "detail" .= detail]
    ExecTimeout detail -> object ["tag" .= ("ExecTimeout" :: Text), "detail" .= detail]

data Exec a where
  Run :: Text -> Exec (Either ExecError Proc)
  RunIn :: Text -> Text -> Exec (Either ExecError Proc)
  RunArgv :: [Text] -> Exec (Either ExecError Proc)

data Journal a where
  RecordStep :: Text -> Text -> Value -> Journal ()
  TraceStep :: Text -> Text -> Value -> Journal ()

data WorktreeId = WorktreeId Text deriving (Show, Eq)
data GitOid = GitOid Text deriving (Show, Eq)
data GitRef = GitRef Text deriving (Show, Eq)
data BranchName = BranchName Text deriving (Show, Eq)
data WorktreeSource = SourceCurrentRepository | SourceRef GitRef | SourceWorktree WorktreeId deriving (Show, Eq)
data DirtyPolicy = RequireClean | AllowDirtySnapshot deriving (Show, Eq)
data WorktreeSpec = WorktreeSpec { specSource :: WorktreeSource, specLabel :: Text, specDirtyPolicy :: DirtyPolicy } deriving (Show, Eq)
data InProgressKind = InProgressMerge | InProgressRebase | InProgressCherryPick | InProgressRevert | InProgressBisect deriving (Show, Eq)
data DirtySummary = DirtySummary { staged :: [Text], unstaged :: [Text], untracked :: [Text], ignoredExcluded :: Int } deriving (Show, Eq)
data HeadState = OnBranch { headBranch :: BranchName, headOid :: GitOid } | Detached { headOid :: GitOid } deriving (Show, Eq)
data WorkingState = WorkingState { changes :: DirtySummary, operation :: Maybe InProgressKind } deriving (Show, Eq)
data SubmissionObservation = SubmissionObservation { observedWorktreeId :: WorktreeId, baseHead :: GitOid, committedPaths :: [Text], submittedHead :: HeadState, workingState :: WorkingState } deriving (Show, Eq)
data GitFailureReceipt = GitFailureReceipt { gitArgs :: [Text], gitCwd :: Text, gitExitCode :: Maybe Int, gitStdout :: Text, gitStderr :: Text } deriving (Show, Eq)
data WorktreeReceipt = WorktreeReceipt { treeId :: WorktreeId, cwd :: Text, branch :: BranchName, sourceHead :: GitOid, snapshotRef :: Maybe GitRef, createdAt :: Int } deriving (Show, Eq)
data WorktreeHandle = WorktreeHandle { handleReceipt :: WorktreeReceipt } deriving (Show, Eq)
data WorktreeSummary = WorktreeSummary { summaryReceipt :: WorktreeReceipt, present :: Bool } deriving (Show, Eq)
data MergeOutcome = Merged GitOid | Conflict [Text] deriving (Show, Eq)
instance ToJSON WorktreeId where toJSON (WorktreeId t) = toJSON t
instance ToJSON GitOid where toJSON (GitOid t) = toJSON t
instance ToJSON GitRef where toJSON (GitRef t) = toJSON t
instance ToJSON BranchName where toJSON (BranchName t) = toJSON t
instance ToJSON InProgressKind where toJSON k = toJSON (show k)
instance ToJSON DirtySummary where toJSON d = object ["staged" .= d.staged, "unstaged" .= d.unstaged, "untracked" .= d.untracked, "ignoredExcluded" .= d.ignoredExcluded]
instance ToJSON GitFailureReceipt where toJSON r = object ["args" .= r.gitArgs, "cwd" .= r.gitCwd, "exitCode" .= r.gitExitCode, "stdout" .= r.gitStdout, "stderr" .= r.gitStderr]
data WorktreeError = SourceDirty DirtySummary | NotARepository Text | WorktreeLost WorktreeId | DirtySubmoduleUnsupported Text | SourceOperationInProgress InProgressKind | WorktreeBusy WorktreeId Text | SubmissionUnstable WorktreeId | WorktreeUnauthorized WorktreeId | WorktreeAuthorityDenied Text | GitFailure GitFailureReceipt | WorktreeNotRegistered WorktreeId | InvalidRegistryRoot Text Text | StorageFailure Text Text deriving (Show, Eq)
instance ToJSON WorktreeError where
  toJSON e = case e of
    SourceDirty dirty -> object ["tag" .= ("SourceDirty" :: Text), "dirty" .= dirty]
    NotARepository path -> object ["tag" .= ("NotARepository" :: Text), "path" .= path]
    WorktreeLost lostId -> object ["tag" .= ("WorktreeLost" :: Text), "lostId" .= lostId]
    DirtySubmoduleUnsupported submodule -> object ["tag" .= ("DirtySubmoduleUnsupported" :: Text), "submodule" .= submodule]
    SourceOperationInProgress inProgress -> object ["tag" .= ("SourceOperationInProgress" :: Text), "inProgress" .= inProgress]
    WorktreeBusy busyId holder -> object ["tag" .= ("WorktreeBusy" :: Text), "busyId" .= busyId, "holder" .= holder]
    SubmissionUnstable unstableId -> object ["tag" .= ("SubmissionUnstable" :: Text), "unstableId" .= unstableId]
    WorktreeUnauthorized unauthorizedId -> object ["tag" .= ("WorktreeUnauthorized" :: Text), "unauthorizedId" .= unauthorizedId]
    WorktreeAuthorityDenied authorityDetail -> object ["tag" .= ("WorktreeAuthorityDenied" :: Text), "authorityDetail" .= authorityDetail]
    GitFailure receipt -> object ["tag" .= ("GitFailure" :: Text), "receipt" .= receipt]
    WorktreeNotRegistered notRegisteredId -> object ["tag" .= ("WorktreeNotRegistered" :: Text), "notRegisteredId" .= notRegisteredId]
    InvalidRegistryRoot root inside -> object ["tag" .= ("InvalidRegistryRoot" :: Text), "root" .= root, "inside" .= inside]
    StorageFailure storagePath storageDetail -> object ["tag" .= ("StorageFailure" :: Text), "storagePath" .= storagePath, "storageDetail" .= storageDetail]

data Worktree a where
  WorktreeCreate :: WorktreeSpec -> Worktree (Either WorktreeError WorktreeHandle)
  WorktreeLookup :: WorktreeId -> Worktree (Either WorktreeError WorktreeHandle)
  WorktreeList :: Worktree (Either WorktreeError [WorktreeSummary])
  WorktreeBranchOf :: WorktreeId -> Worktree (Either WorktreeError BranchName)
  WorktreeHeadOf :: WorktreeId -> Worktree (Either WorktreeError GitOid)
  WorktreeObserveSubmission :: WorktreeId -> Worktree (Either WorktreeError SubmissionObservation)
  WorktreeMergeInto :: WorktreeId -> BranchName -> Text -> Worktree (Either WorktreeError MergeOutcome)

data EventId = EventId Int deriving (Show, Eq)
data SubscriptionId = SubscriptionId Int deriving (Show, Eq)
data Watch = WatchCommit WorktreeId | WatchHead WorktreeId | WatchDeadline Int | WatchAsync Int | WatchMailbox Int deriving (Show, Eq)
data HeadChangeKind = Advanced [GitOid] | Amended GitOid GitOid | Rewritten [(GitOid, GitOid)] | Rewound | Switched | UnknownChange deriving (Show, Eq)
data HeadChangeReceipt = HeadChangeReceipt { headWorktree :: WorktreeId, oldHead :: Maybe GitOid, newHead :: GitOid, kind :: HeadChangeKind, headBranch :: Maybe BranchName, observedAtMs :: Int } deriving (Show, Eq)
data CommitReceipt = CommitReceipt { commitWorktree :: WorktreeId, oid :: GitOid, parents :: [GitOid], subject :: Text, author :: Text, committedAtMs :: Int, files :: [Text] } deriving (Show, Eq)
data Tick = Tick { firedAtMs :: Int } deriving (Show, Eq)
data RepositoryEvent = ObservedCommit EventId CommitReceipt | ObservedHeadChange EventId HeadChangeReceipt | ObservedTick EventId Tick | ObservedAsyncDone EventId Int | ObservedMessage EventId Int Value deriving (Show, Eq)
data EventError = EventQueueOverflow Int Int | EventUnknownSubscription Int | EventSourceLost Text | EventSourceFailed Text | EventUnknownMailbox Int deriving (Show, Eq)
instance ToJSON EventError where
  toJSON e = case e of
    EventQueueOverflow overflowSub dropped -> object ["tag" .= ("EventQueueOverflow" :: Text), "overflowSub" .= overflowSub, "dropped" .= dropped]
    EventUnknownSubscription unknownSub -> object ["tag" .= ("EventUnknownSubscription" :: Text), "unknownSub" .= unknownSub]
    EventSourceLost lostDetail -> object ["tag" .= ("EventSourceLost" :: Text), "lostDetail" .= lostDetail]
    EventSourceFailed failedDetail -> object ["tag" .= ("EventSourceFailed" :: Text), "failedDetail" .= failedDetail]
    EventUnknownMailbox unknownMailbox -> object ["tag" .= ("EventUnknownMailbox" :: Text), "unknownMailbox" .= unknownMailbox]

data RepoEvent a where
  RepoEventSubscribe :: [Watch] -> RepoEvent (Either EventError SubscriptionId)
  RepoEventDrain :: SubscriptionId -> RepoEvent (Either EventError [RepositoryEvent])
  RepoEventAwait :: SubscriptionId -> Int -> RepoEvent (Either EventError [RepositoryEvent])
  RepoEventUnsubscribe :: SubscriptionId -> RepoEvent (Either EventError ())
  MailboxNew :: RepoEvent (Either EventError Int)
  MailboxSend :: Int -> Text -> Value -> RepoEvent (Either EventError ())
  MailboxDrop :: Int -> RepoEvent (Either EventError ())

data AskUser a where
  AskUserWith :: Value -> AskUser Value
  NoteWith :: Text -> AskUser ()

data ReadState a where
  ReadStateWith :: ReadState Value

data InvocationExit = ExitRoundsExhausted Text | ExitNotFinalized Text | ExitCancelled Text | ExitRuntimeFailure Text deriving (Show, Eq)
instance ToJSON InvocationExit where
  toJSON e = case e of
    ExitRoundsExhausted detail -> object ["tag" .= ("ExitRoundsExhausted" :: Text), "detail" .= detail]
    ExitNotFinalized detail -> object ["tag" .= ("ExitNotFinalized" :: Text), "detail" .= detail]
    ExitCancelled detail -> object ["tag" .= ("ExitCancelled" :: Text), "detail" .= detail]
    ExitRuntimeFailure detail -> object ["tag" .= ("ExitRuntimeFailure" :: Text), "detail" .= detail]

data RunLLMTurn a where
  RunLLMTurnWith :: Text -> Value -> RunLLMTurn Value

data Fork a where
  ForkWith :: Int -> Text -> Fork Value
  ForkAllWith :: Int -> [Text] -> Fork Value

data Finalize v a where
  FinalizeWith :: Int -> v -> Finalize v a

data AsyncStatus = AsyncRunning | AsyncSettled | AsyncWasCancelled deriving (Show, Eq)
data Green a where
  AsyncSpawnWith :: Int -> (Int -> Eff bodyEffs ()) -> Green Int
  AsyncDoneWith :: Int -> Green ()
  AsyncJoinAnyWith :: [Int] -> Green Int
  AsyncStatusWith :: Int -> Green Int
  AsyncCancelWith :: Int -> Green ()

data ActorEffectProfile = ActorReadWriteProfile | ActorReadOnlyProfile deriving (Show, Eq)
data ActorTerminalStatus = ActorCompletedStatus | ActorFailedStatus Text | ActorCancelledStatus Text deriving (Show, Eq)
data ActorCallStatus = ActorCallSucceeded | ActorCallFailed Text deriving (Show, Eq)
data Actor a where
  ActorStartWith :: Text -> (Int -> Eff childEffs ()) -> ActorEffectProfile -> [Text] -> Actor (Int, Int)
  ActorWaitWith :: (Int, Int) -> Actor ActorTerminalStatus
  ActorPollWith :: (Int, Int) -> Actor (Maybe ActorTerminalStatus)
  ActorCallWith :: (Int, Int) -> protocol result -> Actor result
  ActorTryCallWith :: (Int, Int) -> protocol () -> Actor ActorCallStatus
  ActorCastWith :: (Int, Int) -> protocol () -> Actor ()

data ActorKernel a where
  ActorInstallShutdownWith :: Int -> (Int -> Eff childEffs ()) -> ActorKernel ()
  ActorReadyWith :: ActorKernel ()
  ActorReplyWith :: Int -> result -> ActorKernel ()
  ActorContinueWith :: Int -> next -> ActorKernel ()

data ActorLocal (api :: Type -> Type) a where
  ActorReceiveWith :: Int -> (forall result. api result -> Eff handlerEffs ()) -> ActorLocal api next

data AgentTools a where
  AgentToolsAwaitWith :: Value -> Text -> Maybe Text -> AgentTools (Text, Value)
  AgentToolsReplyWith :: Value -> AgentTools ()

data AgentSession a where
  AgentSessionWith :: Int -> input -> Int -> Maybe Text -> AgentSession output
  AgentAttachWith :: Maybe Text -> AgentSession ()

-- | Emit a line of console output. Thin wrapper over the Print effect
-- so chains never need `send (Print …)`.
say :: forall effs. Member Console effs => Text -> Eff effs ()
say = send . Print
-- | Look up a key; Nothing when absent.
kvGet :: forall effs. Member KV effs => Text -> Eff effs (Maybe Value)
kvGet = send . KvGet
-- | Persist a JSON value under a key.
kvSet :: forall effs. Member KV effs => Text -> Value -> Eff effs ()
kvSet k v = send (KvSet k v)
-- | Delete a key (no-op when absent).
kvDel :: forall effs. Member KV effs => Text -> Eff effs ()
kvDel = send . KvDelete
-- | Delete all keys whose name starts with @prefix@; return the count deleted.
-- Pass "" (empty string) to clear the ENTIRE store — this erases ALL
-- persisted KV data for this server session, so use with caution.
-- Recommended pattern: namespace keys as "ns/key" and clear with "ns/".
-- NOTE: per-session automatic scoping is a deferred design decision (#327);
-- callers manage namespaces manually via this prefix argument.
kvClear :: forall effs. Member KV effs => Text -> Eff effs Int
kvClear = send . KvClear
-- | All keys whose name starts with @prefix@, returned sorted.
-- E.g. @kvKeysP "agent/"@ returns @["agent/bar", "agent/foo", ...]@.
-- Pass "" to list ALL keys, sorted.
kvKeysP :: forall effs. Member KV effs => Text -> Eff effs [Text]
kvKeysP = send . KvKeysP
-- | Summary of KV store state as a JSON Value:
-- @{count :: Int, sample :: [Text], file_size_bytes :: Int}@.
-- Use to inspect junk-drawer accumulation without listing all keys.
-- Extract fields with optics: @i <- kvInfo; i ^? key "count" . _Int@
kvInfo :: forall effs. Member KV effs => Eff effs Value
kvInfo = send KvInfo
-- | Atomic compare-and-swap: set @key@ to @new@ only if its current
-- value equals @expected@ (Nothing = require the key ABSENT).
-- @Right ()@ on success; @Left actual@ (the current value) on a
-- mismatch, with nothing written. Cross-process safe (the store
-- file is flocked), so it is the lost-update-free primitive that
-- kvModify\/kvIncr\/kvAppend retry over — prefer those for the
-- common read-modify-write; reach for kvCas directly for a custom
-- conflict policy.
kvCas :: forall effs. Member KV effs => Text -> Maybe Value -> Value -> Eff effs (Either Value ())
kvCas k e n = send (KvCas k e n)
-- | Read a file. Failure is TYPED (#335): `Left (FsNotFound p)` / `Left
-- (FsNotUtf8 p)` / `Left (FsIo _)`. The natural spelling unwraps-or-aborts with
-- a failable bind: `Right src <- readFile path` (or `readFile path >>= liftEither`).
readFile :: forall effs. Member FsRead effs => FilePath -> Eff effs (Either FsError Text)
readFile = send . FsRead
-- | List a directory. `Left (FsNotFound _)` when absent; unwrap with `liftEither`.
listDirectory :: forall effs. Member FsRead effs => FilePath -> Eff effs (Either FsError [FilePath])
listDirectory = send . FsListDir
-- | TOTAL existence predicate (System.Directory semantics): False for a
-- missing path, a directory, or a path outside the sandbox — never throws.
doesFileExist :: forall effs. Member FsRead effs => FilePath -> Eff effs Bool
doesFileExist p = send (FsMetadata p) <&> maybe False (\m -> m.isFile)
-- | TOTAL existence predicate: False for missing/non-dir/out-of-sandbox.
doesDirectoryExist :: forall effs. Member FsRead effs => FilePath -> Eff effs Bool
doesDirectoryExist p = send (FsMetadata p) <&> maybe False (\m -> m.isDir)
-- | File size in bytes, or `Nothing` if the path is missing.
getFileSize :: forall effs. Member FsRead effs => FilePath -> Eff effs (Maybe Int)
getFileSize p = send (FsMetadata p) <&> fmap (\m -> m.size)
-- | File metadata as a `FileMeta` record {size, isFile, isDir}, or `Nothing`
-- if the path is missing/unreadable (use record-dot: `m.size`, `m.isDir`).
fsMeta :: forall effs. Member FsRead effs => FilePath -> Eff effs (Maybe FileMeta)
fsMeta = send . FsMetadata
-- | Expand a glob to matching file paths. `Left (FsSandbox _)` on an empty
-- or absolute pattern, `Left (FsNotFound _)` on a missing search root; unwrap
-- with `Right ps <- glob pat` or `glob pat >>= liftEither`.
glob :: forall effs. Member FsRead effs => FilePath -> Eff effs (Either FsError [FilePath])
glob = send . FsGlob
-- | Regex-search files matching a path glob. ARG ORDER: regex FIRST, glob
-- SECOND — a path glob like "*.rs" goes in arg 2, not arg 1. Returns [Hit]
-- {path, line, text} (the shared Hit shape, so it composes with
-- hitsByFile/refs). Failure is typed: `Left (FsBadRegex _)` on a bad regex.
-- NB regex metachars are double-escaped here (JSON x Haskell), so a literal dot
-- needs four backslashes; the FsBadRegex detail shows the exact form.
grepGlob :: forall effs. Member FsRead effs => Text -> FilePath -> Eff effs (Either FsError [Hit])
grepGlob pat g = send (FsGrep pat g)
-- | Read every file matching a glob with PER-FILE failure isolation: one
-- `FileRead {path, contents}` per match — `contents` is `Right text` on a clean
-- UTF-8 read, `Left err` on a per-file failure (binary / non-UTF-8, permission).
-- One bad file (e.g. a binary swept up by a wide glob) does NOT fail the whole
-- batch. An empty glob is rejected loudly, but a glob matching NOTHING yields
-- `[]` silently — check `null rs` when absence itself is the signal. Recover
-- the readable files with
-- `[r.path | r <- rs, isRight r.contents]`, or split all outcomes with
-- `partitionEithers (map (.contents) rs)`.
readGlob :: forall effs. Member FsRead effs => Text -> Eff effs [FileRead]
readGlob = send . FsReadGlob
-- | Dry-run `update`: returns an `UpdateOutcome` (the review diff, or the
-- reason it can't apply), writes NOTHING. Never errors — the conflict comes
-- back as data so you can branch before committing.
planUpdate :: forall effs. Member FsRead effs => FilePath -> Text -> Text -> Eff effs UpdateOutcome
planUpdate path old new = do
  er <- readFile path
  case er of
    Left e -> pure (UpdateRejected ("file not found: " <> T.pack (show e)) Nothing)
    Right src ->
      let n = if T.null old then 0 else length (T.splitOn old src) - 1
      in if T.null old then pure (UpdateRejected "'old' must be non-empty" Nothing)
         else if n == 0 then pure (UpdateRejected "not found" Nothing)
         else if n > 1 then pure (UpdateRejected "ambiguous" (Just n))
         else case Patch.genPatch path src (replace old new src) of
                Left _ -> pure UpdateNoChange
                Right fp -> pure (UpdateDiff (Patch.renderPatch [fp]))
-- | Blake3 content hash (hex) of a file, or Nothing if it does not exist.
-- The compare-and-swap token for writeCheckedIf: read it, compute your new
-- content, then write back only if the file still hashes the same.
fileHash :: forall effs. Member FsRead effs => FilePath -> Eff effs (Maybe Text)
fileHash p = send (FsHash p) >>= liftEither
-- | Write a file (mkdir -p on the parent). `Left (FsSandbox _)` on a path
-- escape, `Left (FsIo _)` on write failure; unwrap with `liftEither`.
writeFile :: forall effs. Member FsWrite effs => FilePath -> Text -> Eff effs (Either FsError ())
writeFile f c = send (FsWrite f c)
-- | Append to a file (reads then writes). Failure is TYPED (#335): a read
-- or write failure comes back as `Left (FsError)` DATA, nothing partially
-- applied; unwrap with `Right () <- appendFile path t` or `>>= liftEither`.
appendFile :: forall effs. Members '[FsRead, FsWrite] effs => FilePath -> Text -> Eff effs (Either FsError ())
appendFile p t = do
  er <- readFile p
  case er of
    Left e -> pure (Left e)
    Right old -> writeFile p (old <> t)
-- | Exact str-replace, EXACTLY-ONCE. Reports the outcome as an
-- `UpdateOneOutcome` DATA value (never throws, mirrors `InsertAfterOutcome`):
-- empty `old`, a missing file, `old` not found, or `old` matching 2+ places
-- is `UpdateOneRejected` (nothing written); otherwise `UpdateOneApplied`.
-- Pass enough surrounding text that `old` is unique. Use planUpdate to review
-- the diff first; the full editing surface is in tidepool://edits.
update :: forall effs. Members '[FsRead, FsWrite] effs => FilePath -> Text -> Text -> Eff effs UpdateOneOutcome
update path old new
  | T.null old = pure (UpdateOneRejected "'old' must be non-empty" Nothing)
  | otherwise = do
      er <- readFile path
      case er of
        Left e -> pure (UpdateOneRejected ("file not found: " <> T.pack (show e)) Nothing)
        Right src ->
          case length (T.splitOn old src) - 1 of
            0 -> pure (UpdateOneRejected ("'old' not found in " <> path) Nothing)
            1 -> writeFile path (replace old new src) >>= liftEither >> pure UpdateOneApplied
            n -> pure (UpdateOneRejected ("'old' matches " <> T.pack (show n) <> " places in " <> path <> " (add surrounding context to disambiguate)") (Just n))
-- | Replace EVERY occurrence of `old` with `new`. Reports the outcome as an
-- `UpdateAllOutcome` DATA value (never throws): empty `old`, a missing file,
-- or zero matches is `UpdateAllRejected` (nothing written); otherwise
-- `UpdateAllApplied` carries the replacement count.
updateAll :: forall effs. Members '[FsRead, FsWrite] effs => FilePath -> Text -> Text -> Eff effs UpdateAllOutcome
updateAll path old new
  | T.null old = pure (UpdateAllRejected "'old' must be non-empty")
  | otherwise = do
      er <- readFile path
      case er of
        Left e -> pure (UpdateAllRejected ("file not found: " <> T.pack (show e)))
        Right src ->
          let n = length (T.splitOn old src) - 1
          in if n == 0
               then pure (UpdateAllRejected ("'old' not found in " <> path))
               else writeFile path (replace old new src) >>= liftEither >> pure (UpdateAllApplied n)
-- | `update` from the `input` JSON parameter: {file, old, new} (for big/quote-heavy
-- fragments). Reports the outcome as an `UpdateOneOutcome` DATA value (never
-- throws, same contract as `update`): a malformed payload (missing or
-- non-string file/old/new key) is `UpdateOneRejected` — one bad item never
-- aborts a batch.
updateJ :: forall effs. Members '[FsRead, FsWrite] effs => Value -> Eff effs UpdateOneOutcome
updateJ v = case (v ^? key "file" . _String, v ^? key "old" . _String, v ^? key "new" . _String) of
  (Just f, Just o, Just n) -> update f o n
  _ -> pure (UpdateOneRejected "updateJ: need {file, old, new} strings in input" Nothing)
-- | Insert a block after the unique line containing `anchor`. Reports the
-- outcome as an `InsertAfterOutcome` DATA value (never throws): a missing
-- file, or an anchor matching zero or 2+ lines, is `InsertAfterRejected`
-- (nothing written); otherwise `InsertAfterApplied`.
insertAfter :: forall effs. Members '[FsRead, FsWrite] effs => FilePath -> Text -> Text -> Eff effs InsertAfterOutcome
insertAfter path anchor block = do
  er <- readFile path
  case er of
    Left e -> pure (InsertAfterRejected ("file not found: " <> T.pack (show e)) Nothing)
    Right src ->
      let ls = lines src
          n = length (filter (isInfixOf anchor) ls)
      in case n of
           1 -> writeFile path (unlines (concatMap (\l -> if anchor `isInfixOf` l then [l, block] else [l]) ls))
                  >>= liftEither >> pure InsertAfterApplied
           _ -> pure (InsertAfterRejected ("anchor matched " <> T.pack (show n) <> " lines in " <> path) (Just n))
-- | Compute-check-commit: write only if every named check holds; failures
-- come back as a `WriteOutcome` (nothing written on failure).
writeChecked :: forall effs. Member FsWrite effs => FilePath -> [(Text, Bool)] -> Text -> Eff effs WriteOutcome
writeChecked path checks content = do
  let failed = [name | (name, ok) <- checks, not ok]
  if null failed
    then writeFile path content >>= liftEither >> pure (Written path (length checks))
    else pure (WriteBlocked path failed)
-- | Content-hash compare-and-swap write (#330). Writes CONTENT only if the
-- file's current blake3 hash equals EXPECTED (Nothing = expect the file ABSENT,
-- i.e. create-only). The compare-and-write is atomic within the handler, closing
-- the lost-update race between parallel agents. Returns a WriteOutcome: 'Written'
-- on success, or 'WriteConflict' (carrying expected vs actual hash) if the
-- precondition failed — conflicts come back as DATA, nothing is written. Get
-- EXPECTED from fileHash; on a conflict re-read, recompute, and retry.
writeCheckedIf :: forall effs. Member FsWrite effs => Maybe Text -> FilePath -> Text -> Eff effs WriteOutcome
writeCheckedIf expected path content = do
  r <- send (FsWriteCas path expected content)
  pure $ case r of
    Right () -> Written path 1
    Left actual -> WriteConflict path expected actual
-- | Fetch JSON from an HTTP endpoint. Failure is TYPED (#335): `Left
-- (HttpStatus code body)` on a non-2xx response, `Left (HttpNetwork _)`
-- on a network failure. Unwrap with `Right v <- httpGet url` or `>>= liftEither`.
httpGet :: forall effs. Member Http effs => Text -> Eff effs (Either HttpError Value)
httpGet = send . HttpGet
-- | POST a JSON body; returns the response Value (see `httpGet` for the
-- failure shape).
httpPost :: forall effs. Member Http effs => Text -> Value -> Eff effs (Either HttpError Value)
httpPost url body = send (HttpPost url body)
-- | Last N commits, newest-first. Each 'Commit' carries sha/subject/author/date/files.
gitLog :: forall effs. Member Git effs => Int -> Eff effs (Either GitError [Commit])
gitLog = send . GitLog
-- | Working-tree status. Each 'StatusEntry' has path and 2-char XY state code
-- (e.g. "M ", "??", "A ").
gitStatus :: forall effs. Member Git effs => Eff effs (Either GitError [StatusEntry])
gitStatus = send GitStatus
-- | Per-file diff stats. THE ARGUMENT IS A REVSPEC COMPARED AGAINST THE WORKING
-- TREE, not "commit vs its parent" — `gitDiffStat sha` on a clean tree is
-- `Right []` (correct data, not an error). For "what did this commit change",
-- pass a RANGE: `gitDiffStat (sha <> "~1.." <> sha)` (also "main..HEAD",
-- "HEAD~3..HEAD"). For bulk per-commit history, use `gitLogNumstat` instead —
-- one subprocess for N commits, no per-commit mapM. 'FileDelta' carries
-- path/adds/dels/binary.
gitDiffStat :: forall effs. Member Git effs => Text -> Eff effs (Either GitError [FileDelta])
gitDiffStat = send . GitDiffStat
-- | Single commit by revspec. `Left (GitBadRevspec _)` on an unknown or
-- ambiguous revspec; unwrap with `Right c <- gitShow rev` or `>>= liftEither`.
gitShow :: forall effs. Member Git effs => Text -> Eff effs (Either GitError Commit)
gitShow = send . GitShow
-- | Last N commits, newest-first, EACH PAIRED WITH ITS OWN per-file numstat
-- deltas — one subprocess for all N, in place of `gitLog` followed by a
-- per-commit `mapM gitDiffStat`. 'CommitDeltas' carries {commit, deltas};
-- a merge or otherwise-empty commit has `deltas = []`. A renamed file records
-- only its NEW path.
gitLogNumstat :: forall effs. Member Git effs => Int -> Eff effs (Either GitError [CommitDeltas])
gitLogNumstat = send . GitLogNumstat
-- | Current UTC time as an opaque UTCTime (epoch-millisecond resolution).
getCurrentTime :: forall effs. Member Time effs => Eff effs UTCTime
getCurrentTime = UTCTime <$> send TimeNow
-- @substrate-helper@
entropySeed :: forall effs. Member Entropy effs => Eff effs Int
entropySeed = send EntropySeed
-- | Constructor table: (name, arity) pairs.
metaConstructors :: forall effs. Member Meta effs => Eff effs [(Text, Int)]
metaConstructors = send MetaConstructors
-- | Look up a constructor by name: (tag, arity).
metaLookupCon :: forall effs. Member Meta effs => Text -> Eff effs (Maybe (Int, Int))
metaLookupCon = send . MetaLookupCon
-- | Names of the JIT-implemented primops.
metaPrimOps :: forall effs. Member Meta effs => Eff effs [Text]
metaPrimOps = send MetaPrimOps
-- | Effect type names in the running stack.
metaEffects :: forall effs. Member Meta effs => Eff effs [Text]
metaEffects = send MetaEffects
-- | Drain pending runtime diagnostics.
metaDiagnostics :: forall effs. Member Meta effs => Eff effs [Text]
metaDiagnostics = send MetaDiagnostics
-- | Server crate version.
metaVersion :: forall effs. Member Meta effs => Eff effs Text
metaVersion = send MetaVersion
-- | Helper-verb signatures of the running stack.
metaHelp :: forall effs. Member Meta effs => Eff effs [Text]
metaHelp = send MetaHelp
-- @substrate-helper@
askRaw :: forall effs. Member Ask effs => Text -> Value -> Eff effs Value
askRaw prompt payload = send (AskWith prompt payload)
-- @substrate-helper@
llmRaw :: forall effs. Member Llm effs => Text -> Value -> Eff effs (Either LlmError Value)
llmRaw prompt payload = send (LlmStructured prompt payload)
findTally :: Eq a => a -> [(a, Int)] -> Maybe [(a, Int)]
findTally _ [] = Nothing
findTally x ((k, n):rest) = if x == k then Just ((k, n + 1) : rest) else case findTally x rest of { Just rest' -> Just ((k, n) : rest'); Nothing -> Nothing }
tallyList :: Eq a => [a] -> [(a, Int)]
tallyList = foldl' (\acc x -> case findTally x acc of { Just acc' -> acc'; Nothing -> acc ++ [(x, 1)] }) []
-- @substrate-helper@
-- | RAW one-cycle coupled spawn: workspace + binding + agent + one
-- backend cycle, atomically; `schema` is the JSON Schema the terminal
-- result must conform to. Prefer the typed wrapper in
-- `Tidepool.Agent.Spawn` (schema derived from your result type's
-- Generic representation, payload decoded by its FromJSON instance);
-- this is its substrate.
spawnAgentRaw :: forall effs. Member Subagent effs => SpawnSpec -> Value -> Eff effs (Either SpawnError SpawnOutcome)
spawnAgentRaw spec schema = send (SubagentSpawn spec schema)
-- @substrate-helper@
-- | RAW begin of a coupled spawn that carries dynamic tools: it does
-- everything `spawnAgentRaw` does, then drives the turn to its FIRST
-- stop instead of to the end — either `StepToolCall agent callId tool
-- args` (the child called one of your tools and its turn is PARKED
-- until you answer) or `StepDone outcome` (it never called one).
-- `tools` is a JSON array of {name, description, inputSchema};
-- `schema` is the JSON Schema the terminal result must conform to.
-- Prefer `spawnAgentWithTools` in `Tidepool.Agent.Spawn`, which
-- compiles both from your types and runs the answer loop for you.
agentBeginRaw :: forall effs. Member Subagent effs => SpawnSpec -> Value -> Value -> Eff effs (Either SpawnError AgentStep)
agentBeginRaw spec tools schema = send (SubagentBegin spec tools schema)
-- @substrate-helper@
-- | RAW answer to the parked tool call, driving the turn on to its next
-- stop (another `StepToolCall`, or `StepDone`). `agent` and `callId`
-- are echoed from the `StepToolCall` you are answering; naming a
-- different agent or a different call is refused (`SpawnDriveFailed`)
-- rather than misrouted. `ok` False is a REFUSAL the child reads and
-- reacts to — an ordinary conversational fact, not a transport error,
-- and never a way to leave the call unanswered; `body` is then the
-- text it sees. Prefer `spawnAgentWithTools` in `Tidepool.Agent.Spawn`.
agentResumeRaw :: forall effs. Member Subagent effs => AgentId -> Text -> Bool -> Value -> Eff effs (Either SpawnError AgentStep)
agentResumeRaw agent callId ok body = send (SubagentResume agent callId ok body)
-- | Spawn in a NEW managed worktree: worktree spec, agent label, task.
spawnSpec :: WorktreeSpec -> Text -> Text -> SpawnSpec
spawnSpec wspec lbl task = SpawnSpec (SpawnNewWorktree wspec) lbl task
-- | Spawn in an EXISTING unbound managed worktree by durable id.
-- Fails `SpawnBindingFailed` (naming the holder) if it is bound.
spawnSpecIn :: WorktreeId -> Text -> Text -> SpawnSpec
spawnSpecIn tid lbl task = SpawnSpec (SpawnExistingWorktree tid) lbl task
-- | One-line operator-readable rendering of a spawn failure.
-- Case-match the constructor when you mean to BRANCH on it.
renderBackendFailure :: BackendFailure -> Text
renderBackendFailure (BackendUnavailable t) = "backend unavailable: " <> t
renderBackendFailure (ProtocolRejected t) = "backend rejected request: " <> t
renderBackendFailure (RunFailed t) = "agent run failed: " <> t
-- @substrate-helper@
-- | RAW async spawn: everything `spawnAgentRaw` does, except that the
-- cycle runs on its OWN thread and this call returns as soon as it is
-- admitted — a `CycleId` naming the running cycle, not its outcome.
-- Refused with `SpawnCapacityExhausted` when the handler's cycle table
-- is already full; that is a BOUND, not a queue, so nothing is
-- allocated behind it. Every cycle must eventually be reaped by
-- `agentAwaitRaw` or `agentCancelRaw`. Prefer the typed wrapper
-- `spawnAsync` in `Tidepool.Agent.Spawn` (schema derived from your
-- result type, handle abstract over it); this is its substrate.
agentSpawnAsyncRaw :: forall effs. Member Subagent effs => SpawnSpec -> Value -> Eff effs (Either SpawnError CycleId)
agentSpawnAsyncRaw spec schema = send (SubagentSpawnAsync spec schema)
-- @substrate-helper@
-- | RAW await: BLOCK until the named cycle finishes, and return the same
-- `Either SpawnError SpawnOutcome` the synchronous `spawnAgentRaw`
-- returns — the async path is the same call, reaped later. Awaiting a
-- cycle this handler never minted (or one already reaped) is a
-- `SpawnDriveFailed` at `StageRunning`: a caller-sequencing failure,
-- not a backend one. Prefer the typed wrapper `awaitAgent` in
-- `Tidepool.Agent.Spawn`, which decodes the payload into your result
-- type as `spawnAgent` does.
agentAwaitRaw :: forall effs. Member Subagent effs => CycleId -> Eff effs (Either SpawnError SpawnOutcome)
agentAwaitRaw cycle = send (SubagentAwait cycle)
-- @substrate-helper@
-- | RAW cancel: reap the named cycle's backend and release its binding.
-- TOTAL — cancelling a cycle that already finished, or one this handler
-- never minted, is a NO-OP, so there is nothing to case-match. Retain-
-- first as everywhere else: the binding is settled, and the worktree
-- stays registered and rebindable — nothing is deleted. Prefer the
-- typed wrapper `cancelAgent` in `Tidepool.Agent.Spawn`.
agentCancelRaw :: forall effs. Member Subagent effs => CycleId -> Eff effs ()
agentCancelRaw cycle = send (SubagentCancel cycle)
-- | Run a shell command; returns a `Proc` record {exitCode, stdout, stderr}
-- (use `ok p` for the zero-exit check). Failure is TYPED (#335): `Left
-- (ExecSpawn _)` when the process can't be spawned, `Left (ExecBadDir _)`
-- for `runIn` with a bad/escaping directory, `Left (ExecTimeout _)` when
-- the command outran its timeout and was killed. A nonzero EXIT is NOT a
-- failure — inspect `p.exitCode`. Natural spelling: `Right p <- run cmd`.
run :: forall effs. Member Exec effs => Text -> Eff effs (Either ExecError Proc)
run = send . Run
runIn :: forall effs. Member Exec effs => Text -> Text -> Eff effs (Either ExecError Proc)
runIn dir cmd = send (RunIn dir cmd)
runArgv :: forall effs. Member Exec effs => [Text] -> Eff effs (Either ExecError Proc)
runArgv = send . RunArgv
-- | Append one durable journal entry. `kind` and `key` are
-- caller-chosen labels; `payload` is an opaque JSON value. Flushed
-- immediately; append-only — never rewritten or compacted.
record :: forall effs. Member Journal effs => Text -> Text -> Value -> Eff effs ()
record kind key payload = send (RecordStep kind key payload)
-- | Append one observability entry to the run's sibling TRACE stream: decision narration and telemetry, never folded into resume. `stage` names what kind of moment this is (e.g. "resume-verdict", "park"); `key` is the branch or unit it concerns; `payload` is an opaque JSON value whose shape may evolve freely. The handler stamps a timestamp on every line, so trace and journal merge into one timeline.
trace :: forall effs. Member Journal effs => Text -> Text -> Value -> Eff effs ()
trace stage key payload = send (TraceStep stage key payload)
-- | Create a managed worktree. `Left (SourceDirty summary)` when the
-- source is dirty and the spec did not opt in; case-match the error
-- rather than unwrapping if you mean to handle it.
createWorktree :: forall effs. Member Worktree effs => WorktreeSpec -> Eff effs (Either WorktreeError WorktreeHandle)
createWorktree = send . WorktreeCreate
-- | Look a retained worktree up by durable id. Survives restart:
-- resolution reads on-disk registry state, not process memory.
-- `Left (WorktreeLost i)` when it is registered but gone from disk.
lookupWorktree :: forall effs. Member Worktree effs => WorktreeId -> Eff effs (Either WorktreeError WorktreeHandle)
lookupWorktree = send . WorktreeLookup
-- | Every registered worktree, present or lost. A lost tree is listed
-- with `present = False` rather than failing the whole listing.
listWorktrees :: forall effs. Member Worktree effs => Eff effs (Either WorktreeError [WorktreeSummary])
listWorktrees = send WorktreeList
-- | The durable identity of a managed worktree. Pure: the handle
-- already carries its receipt, so this reads no git state.
worktreeId :: WorktreeHandle -> WorktreeId
worktreeId h = h.handleReceipt.treeId
-- | Merge `branch` into the worktree `treeId` names, as `git merge --no-ff`
-- — never a fast-forward, so a landed merge always carries a genuine merge
-- commit. On conflict, the conflicting paths are read and the merge is
-- ABORTED before this returns: the worktree is left clean either way,
-- success or conflict. `Left (GitFailure r)` is a `git` invocation that
-- never entered a merge at all (an unknown branch, a locked index) —
-- distinct from `Right (Conflict paths)`, a merge that genuinely started
-- and conflicted.
mergeBranchInto :: forall effs. Member Worktree effs => WorktreeId -> BranchName -> Text -> Eff effs (Either WorktreeError MergeOutcome)
mergeBranchInto treeId branch message = send (WorktreeMergeInto treeId branch message)
-- | Observe a candidate checkout through one bounded Worktree operation.
-- This reports submitted HEAD, dirty state, and in-progress operation
-- together; it does not seal or mutate the checkout.
observeSubmission :: forall effs. Member Worktree effs => WorktreeId -> Eff effs (Either WorktreeError SubmissionObservation)
observeSubmission = send . WorktreeObserveSubmission
-- | Block until `sub` has queued at least one observation, or
-- `timeoutMs` elapses (negative blocks with no deadline). An elapsed
-- timeout is an EMPTY list — distinguishable from a real batch, never
-- an error; poison/source-loss still fail via the `Either`.
awaitSubscriptionRaw :: forall effs. Member RepoEvent effs => SubscriptionId -> Int -> Eff effs (Either EventError [RepositoryEvent])
awaitSubscriptionRaw sub timeoutMs = send (RepoEventAwait sub timeoutMs)
-- | Mint a fresh mailbox: an event source only the caller (and whoever
-- it hands the id to) can send into.
mailboxNew :: forall effs. Member RepoEvent effs => Eff effs (Either EventError Int)
mailboxNew = send MailboxNew
-- | Send never blocks: append and return. A burst of sends sharing
-- `key` coalesces to the LAST payload.
mailboxSend :: forall effs. Member RepoEvent effs => Int -> Text -> Value -> Eff effs (Either EventError ())
mailboxSend mid key payload = send (MailboxSend mid key payload)
-- | Drop a mailbox. A later send against it is
-- `Left (EventUnknownMailbox _)`.
mailboxDrop :: forall effs. Member RepoEvent effs => Int -> Eff effs (Either EventError ())
mailboxDrop = send . MailboxDrop
askUserRaw :: forall effs. Member AskUser effs => Value -> Eff effs Value
askUserRaw spec = send (AskUserWith spec)
noteRaw :: forall effs. Member AskUser effs => Text -> Eff effs ()
noteRaw text = send (NoteWith text)
getStateJson :: forall effs. Member ReadState effs => Eff effs Value
getStateJson = send ReadStateWith
{-# OPAQUE runLLMTurn #-}
runLLMTurn :: forall a effs. Member RunLLMTurn effs => Text -> Eff effs a
runLLMTurn prompt = runLLMTurnSited 0 prompt
{-# OPAQUE runLLMTurnFork #-}
runLLMTurnFork :: forall a effs. Member RunLLMTurn effs => Text -> Eff effs (Either InvocationExit a)
runLLMTurnFork prompt = runLLMTurnForkSited 0 prompt
{-# OPAQUE runLLMTurnFanout #-}
runLLMTurnFanout :: forall a effs. Member RunLLMTurn effs => [Text] -> Eff effs [Either InvocationExit a]
runLLMTurnFanout prompts = runLLMTurnFanoutSited 0 prompts
renderInvocationExit :: InvocationExit -> Text
renderInvocationExit (ExitRoundsExhausted d) = "round exhaustion: " <> d
renderInvocationExit (ExitNotFinalized d) = "non-finalization: " <> d
renderInvocationExit (ExitCancelled d) = "cancelled: " <> d
renderInvocationExit (ExitRuntimeFailure d) = "runtime failure: " <> d
-- @substrate-helper@
{-# OPAQUE runLLMTurnSited #-}
runLLMTurnSited :: forall a effs. Member RunLLMTurn effs => Int -> Text -> Eff effs a
runLLMTurnSited sid p = unsafeCoerce <$> send (RunLLMTurnWith p (object ["typedSite" .= sid]))
-- @substrate-helper@
{-# OPAQUE runLLMTurnForkSited #-}
runLLMTurnForkSited :: forall a effs. Member RunLLMTurn effs => Int -> Text -> Eff effs (Either InvocationExit a)
runLLMTurnForkSited sid p = unsafeCoerce <$> send (RunLLMTurnWith p (object ["typedSite" .= sid, "fork" .= True]))
-- @substrate-helper@
{-# OPAQUE runLLMTurnFanoutSited #-}
runLLMTurnFanoutSited :: forall a effs. Member RunLLMTurn effs => Int -> [Text] -> Eff effs [Either InvocationExit a]
runLLMTurnFanoutSited sid prompts = unsafeCoerce <$> send (RunLLMTurnWith (intercalate "\n" prompts) (object ["typedSite" .= sid, "fork" .= True, "fan" .= length prompts, "prompts" .= prompts]))
-- @substrate-helper@
{-# OPAQUE forkSited #-}
forkSited :: forall a effs. Member Fork effs => Int -> Text -> Eff effs a
forkSited sid brief = unsafeCoerce <$> send (ForkWith sid brief)
-- @substrate-helper@
{-# OPAQUE forkAllSited #-}
forkAllSited :: forall a effs. Member Fork effs => Int -> [Text] -> Eff effs [a]
forkAllSited sid prompts = unsafeCoerce <$> send (ForkAllWith sid prompts)
{-# OPAQUE finalize #-}
finalize :: forall v a effs. Member (Finalize v) effs => v -> Eff effs a
finalize v = finalizeSited 0 v
{-# OPAQUE finalizeSited #-}
finalizeSited :: forall v a effs. Member (Finalize v) effs => Int -> v -> Eff effs a
finalizeSited sid v = send (FinalizeWith sid v)
-- @substrate-helper@
-- | Fork a green thread; substrate for 'Tidepool.Async.async'.
-- The body rides as a lambda so the closure-sentinel scan fires
-- and the runtime tenures it (see the effect's Rust definition).
-- The authored wrapper publishes its result into a managed
-- Haskell cell before the body's last, payload-free
-- AsyncDoneWith suspension.
asyncSpawn :: forall effs. Member Green effs => Eff effs () -> Eff effs Int
asyncSpawn body = send (AsyncSpawnWith 0 (\_ -> body >>= \() -> send (AsyncDoneWith 0)))
-- @substrate-helper@
-- | Park until ANY of these threads reaches a terminal state;
-- resumes with the id of the one that did.
asyncJoinAny :: forall effs. Member Green effs => [Int] -> Eff effs Int
asyncJoinAny = send . AsyncJoinAnyWith
-- @substrate-helper@
-- | A thread's current state. Never parks.
asyncStatus :: forall effs. Member Green effs => Int -> Eff effs AsyncStatus
asyncStatus t = decode <$> send (AsyncStatusWith t)
  where
    decode 1 = AsyncSettled
    decode 2 = AsyncWasCancelled
    decode _ = AsyncRunning
-- @substrate-helper@
-- | Cancel a thread: its runtime resource scope closes, discarding its pending
-- suspensions. Idempotent, and a no-op on a terminal thread.
asyncCancel :: forall effs. Member Green effs => Int -> Eff effs ()
asyncCancel = send . AsyncCancelWith
