{-# LANGUAGE NoImplicitPrelude, OverloadedStrings, DataKinds, TypeOperators, FlexibleContexts, FlexibleInstances, UndecidableInstances, GADTs, PartialTypeSignatures, ScopedTypeVariables, ExtendedDefaultRules, LambdaCase, TupleSections, MultiWayIf, RecordWildCards, NamedFieldPuns, ViewPatterns, BangPatterns, TypeApplications, BlockArguments, NumericUnderscores, MultilineStrings, DeriveFunctor, DeriveFoldable, DeriveTraversable, DeriveGeneric, DeriveAnyClass, QuasiQuotes, DuplicateRecordFields, OverloadedRecordDot, OverloadedLabels #-}
-- GENERATED by the tidepool MCP server from its effect handler
-- declarations. Do not edit; regenerated (content-addressed) at startup.
-- PER-WINDOW shim: re-exports the stable Tidepool.Effects.Core and adds
-- only `type M`, this compile's own effect row — see that module and
-- tidepool-mcp/CLAUDE.md's stable-effects-core section.
module Tidepool.Effects (module Tidepool.Effects.Core, M) where
import Tidepool.Effects.Core
import Control.Monad.Freer hiding (run)
import Tidepool.Prelude hiding (error)

type M = Eff '[Console, KV, Fs, Http, Exec, Lsp, Llm, Git, Time, Ask, RunLLMTurn]
__shimProbe :: M ()
__shimProbe = pure ()
