[package]
name = "tidepool-macro"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Procedural macros for the Tidepool language"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
serde_json.workspace = true
tidepool-extract-cmd.workspace = true

[dev-dependencies]
tidepool-repr.workspace = true
tidepool-eval.workspace = true
