{-# LANGUAGE DataKinds #-}
-- Default actor effects — GENERATED by tidepool-protocol, DO NOT EDIT. Build: `//bridge/protocol:generated`.
module Tidepool.Internal.ActorProfiles (ActorEffects) where

import Tidepool.Agent.Reply (Replies)
import Tidepool.Agent.Watch (Watches)
import Tidepool.Effects.Core
  ( ResourceScopes
  , ActorContext
  , AgentLaunch
  , AgentInspection
  , AgentControl
  , BoundWorktree
  , WorktreeRegistry
  , WorktreeAllocation
  , WorktreeIntegration
  , Sleep
  , Notifications
  , Jev
  , ModelCall
  , Commands
  , Console
  , AskUser
  , Green
  , Actor
  , Reflect
  , Lookup
  , Source
  , Journal
  , RepoEvent
  )

type ActorEffects =
  '[Replies, Watches, ResourceScopes, ActorContext, AgentLaunch, AgentInspection, AgentControl, BoundWorktree, WorktreeRegistry, WorktreeAllocation, WorktreeIntegration, Sleep, Notifications, Jev, ModelCall, Commands, Console, AskUser, Green, Actor, Reflect, Lookup, Source, Journal, RepoEvent]
