{-# LANGUAGE DataKinds #-}
-- Concrete public actor effect rows — GENERATED by tidepool-protocol, DO NOT EDIT. Build: `//bridge/protocol:generated`.
module Tidepool.Internal.ActorProfiles
  ( CoreEffects
  , ResearchLeafEffects
  , ResearchEffects
  , CodingEffects
  , IntegrationEffects
  , ActorEffects
  ) where

import Tidepool.Agent.Reply (Replies)
import Tidepool.Agent.Watch (Watches)
import Tidepool.Effects.Core
  ( Actor
  , ActorContext
  , AgentControl
  , AgentInspection
  , AgentLaunch
  , BoundWorktree
  , Commands
  , Console
  , Forks
  , Jev
  , Journal
  , Lookup
  , ModelCall
  , Notifications
  , Reflect
  , RepoEvent
  , Source
  , WorktreeAllocation
  , WorktreeIntegration
  , WorktreeRegistry
  )

type CoreEffects =
  '[Replies, Watches, ActorContext, Notifications, Jev, ModelCall, Commands, Console, Actor, Reflect, Lookup]

type ResearchLeafEffects =
  '[Replies, Watches, ActorContext, BoundWorktree, Notifications, Jev, ModelCall, Commands, Console, Actor, Reflect, Lookup]

type ResearchEffects =
  '[Replies, Watches, Forks, ActorContext, AgentInspection, AgentControl, BoundWorktree, Notifications, Jev, ModelCall, Commands, Console, Actor, Reflect, Lookup]

type CodingEffects =
  '[Replies, Watches, Forks, ActorContext, AgentInspection, AgentControl, BoundWorktree, WorktreeAllocation, WorktreeIntegration, Notifications, Jev, ModelCall, Commands, Console, Actor, Reflect, Lookup, Source]

type IntegrationEffects =
  '[Replies, Watches, ActorContext, AgentInspection, BoundWorktree, WorktreeIntegration, Notifications, Jev, ModelCall, Commands, Console, Actor, Reflect, Lookup]

type ActorEffects =
  '[Replies, Watches, Forks, ActorContext, AgentLaunch, AgentInspection, AgentControl, BoundWorktree, WorktreeRegistry, WorktreeAllocation, WorktreeIntegration, Notifications, Jev, ModelCall, Commands, Console, Actor, Reflect, Lookup, Source, Journal, RepoEvent]
