{-# LANGUAGE OverloadedStrings #-}
-- Generated by tidepool-protocol.
module Tidepool.Internal.ModelControl where
import Prelude
import Data.Text (Text)
import Tidepool.Aeson
import qualified Tidepool.Aeson.KeyMap as KM

controlObject :: [Text] -> (Object -> Result a) -> Value -> Result a
controlObject allowed parse = withObject "ModelCall control" $ \o ->
  if all (`elem` allowed) (map KM.toText (KM.keys o)) then parse o else Error "unknown ModelCall control field"

controlCount :: Int -> Result Int
controlCount count = if count < 0 then Error "negative ModelCall count" else pure count

data ModelEffortEnvelope = ModelLowEffort | ModelMediumEffort | ModelHighEffort deriving (Show, Eq)
instance ToJSON ModelEffortEnvelope where
  toJSON ModelLowEffort = toJSON ("low" :: Text)
  toJSON ModelMediumEffort = toJSON ("medium" :: Text)
  toJSON ModelHighEffort = toJSON ("high" :: Text)
instance FromJSON ModelEffortEnvelope where
  parseJSON = withText "ModelEffortEnvelope" $ \value -> case value of
    "low" -> pure ModelLowEffort
    "medium" -> pure ModelMediumEffort
    "high" -> pure ModelHighEffort
    _ -> Error "unknown ModelCall control value"

data ModelLimitEnvelope = ModelRequestsLimit | ModelToolsLimit | ModelTokensLimit | ModelDeadlineLimit deriving (Show, Eq)
instance ToJSON ModelLimitEnvelope where
  toJSON ModelRequestsLimit = toJSON ("requests" :: Text)
  toJSON ModelToolsLimit = toJSON ("tools" :: Text)
  toJSON ModelTokensLimit = toJSON ("reported_tokens" :: Text)
  toJSON ModelDeadlineLimit = toJSON ("deadline" :: Text)
instance FromJSON ModelLimitEnvelope where
  parseJSON = withText "ModelLimitEnvelope" $ \value -> case value of
    "requests" -> pure ModelRequestsLimit
    "tools" -> pure ModelToolsLimit
    "reported_tokens" -> pure ModelTokensLimit
    "deadline" -> pure ModelDeadlineLimit
    _ -> Error "unknown ModelCall control value"

data ModelRequestLimits = ModelRequestLimits (Maybe Int) (Maybe Int) (Maybe Int) (Maybe Int) deriving (Show, Eq)
instance ToJSON ModelRequestLimits where
  toJSON (ModelRequestLimits f0 f1 f2 f3) = object ["requests" .= f0, "tools" .= f1, "reported_tokens" .= f2, "seconds" .= f3]
instance FromJSON ModelRequestLimits where
  parseJSON = controlObject ["requests", "tools", "reported_tokens", "seconds"] $ \o -> pure ModelRequestLimits <*> ((o .:? "requests") >>= traverse controlCount) <*> ((o .:? "tools") >>= traverse controlCount) <*> ((o .:? "reported_tokens") >>= traverse controlCount) <*> ((o .:? "seconds") >>= traverse controlCount)

data ModelRequestEnvelope = ModelRequestEnvelope Text Text (Maybe Text) (Maybe ModelEffortEnvelope) ModelRequestLimits Value (Maybe Value) Bool deriving (Show, Eq)
instance ToJSON ModelRequestEnvelope where
  toJSON (ModelRequestEnvelope f0 f1 f2 f3 f4 f5 f6 f7) = object ["instructions" .= f0, "input" .= f1, "model" .= f2, "effort" .= f3, "limits" .= f4, "tools" .= f5, "result_schema" .= f6, "after_tool" .= f7]
instance FromJSON ModelRequestEnvelope where
  parseJSON = controlObject ["instructions", "input", "model", "effort", "limits", "tools", "result_schema", "after_tool"] $ \o -> pure ModelRequestEnvelope <*> (o .: "instructions") <*> (o .: "input") <*> (o .:? "model") <*> (o .:? "effort") <*> (o .: "limits") <*> (o .: "tools") <*> (o .:? "result_schema") <*> (o .: "after_tool")

data ModelUsageEnvelope = ModelUsageEnvelope Int Int Int Int deriving (Show, Eq)
instance ToJSON ModelUsageEnvelope where
  toJSON (ModelUsageEnvelope f0 f1 f2 f3) = object ["requests" .= f0, "tools" .= f1, "reported_tokens" .= f2, "unknown_usage_requests" .= f3]
instance FromJSON ModelUsageEnvelope where
  parseJSON = controlObject ["requests", "tools", "reported_tokens", "unknown_usage_requests"] $ \o -> pure ModelUsageEnvelope <*> ((o .: "requests") >>= controlCount) <*> ((o .: "tools") >>= controlCount) <*> ((o .: "reported_tokens") >>= controlCount) <*> ((o .: "unknown_usage_requests") >>= controlCount)

data ModelOutcomeEnvelope = ModelTextOutcome Text | ModelTypedOutcome Value | ModelFailedOutcome Text | ModelCancelledOutcome  | ModelExhaustedOutcome ModelLimitEnvelope deriving (Show, Eq)
instance ToJSON ModelOutcomeEnvelope where
  toJSON (ModelTextOutcome f0) = object ["kind" .= ("text" :: Text), "value" .= f0]
  toJSON (ModelTypedOutcome f0) = object ["kind" .= ("typed" :: Text), "value" .= f0]
  toJSON (ModelFailedOutcome f0) = object ["kind" .= ("failed" :: Text), "value" .= f0]
  toJSON (ModelCancelledOutcome ) = object ["kind" .= ("cancelled" :: Text)]
  toJSON (ModelExhaustedOutcome f0) = object ["kind" .= ("exhausted" :: Text), "value" .= f0]
instance FromJSON ModelOutcomeEnvelope where
  parseJSON = withObject "ModelOutcomeEnvelope" $ \o -> do
    kind <- o .: "kind"
    case (kind :: Text) of
      "text" -> controlObject ["kind", "value"] (\o -> pure ModelTextOutcome <*> (o .: "value")) (Object o)
      "typed" -> controlObject ["kind", "value"] (\o -> pure ModelTypedOutcome <*> (o .: "value")) (Object o)
      "failed" -> controlObject ["kind", "value"] (\o -> pure ModelFailedOutcome <*> (o .: "value")) (Object o)
      "cancelled" -> controlObject ["kind"] (\o -> pure ModelCancelledOutcome) (Object o)
      "exhausted" -> controlObject ["kind", "value"] (\o -> pure ModelExhaustedOutcome <*> (o .: "value")) (Object o)
      _ -> Error "unknown ModelCall control variant"

data ModelReceiptEnvelope = ModelReceiptEnvelope Text Text [Text] ModelUsageEnvelope ModelUsageEnvelope ModelOutcomeEnvelope deriving (Show, Eq)
instance ToJSON ModelReceiptEnvelope where
  toJSON (ModelReceiptEnvelope f0 f1 f2 f3 f4 f5) = object ["invocation_id" .= f0, "parent_cell" .= f1, "requests" .= f2, "counts" .= f3, "cell_counts" .= f4, "outcome" .= f5]
instance FromJSON ModelReceiptEnvelope where
  parseJSON = controlObject ["invocation_id", "parent_cell", "requests", "counts", "cell_counts", "outcome"] $ \o -> pure ModelReceiptEnvelope <*> (o .: "invocation_id") <*> (o .: "parent_cell") <*> (o .: "requests") <*> (o .: "counts") <*> (o .: "cell_counts") <*> (o .: "outcome")

data ModelControlStep = ModelCallback Text Text Text Value | ModelHook Text Text Text Value Text Int Value Text | ModelFinished ModelReceiptEnvelope deriving (Show, Eq)
instance ToJSON ModelControlStep where
  toJSON (ModelCallback f0 f1 f2 f3) = object ["kind" .= ("callback" :: Text), "invocation" .= f0, "call_id" .= f1, "name" .= f2, "arguments" .= f3]
  toJSON (ModelHook f0 f1 f2 f3 f4 f5 f6 f7) = object ["kind" .= ("hook" :: Text), "invocation" .= f0, "operation" .= f1, "name" .= f2, "arguments" .= f3, "handle" .= f4, "ordinal" .= f5, "value" .= f6, "output" .= f7]
  toJSON (ModelFinished f0) = object ["kind" .= ("finished" :: Text), "receipt" .= f0]
instance FromJSON ModelControlStep where
  parseJSON = withObject "ModelControlStep" $ \o -> do
    kind <- o .: "kind"
    case (kind :: Text) of
      "callback" -> controlObject ["kind", "invocation", "call_id", "name", "arguments"] (\o -> pure ModelCallback <*> (o .: "invocation") <*> (o .: "call_id") <*> (o .: "name") <*> (o .: "arguments")) (Object o)
      "hook" -> controlObject ["kind", "invocation", "operation", "name", "arguments", "handle", "ordinal", "value", "output"] (\o -> pure ModelHook <*> (o .: "invocation") <*> (o .: "operation") <*> (o .: "name") <*> (o .: "arguments") <*> (o .: "handle") <*> (o .: "ordinal") <*> (o .: "value") <*> (o .: "output")) (Object o)
      "finished" -> controlObject ["kind", "receipt"] (\o -> pure ModelFinished <*> (o .: "receipt")) (Object o)
      _ -> Error "unknown ModelCall control variant"

data ModelAnnotationEnvelope = ModelNoAnnotation  | ModelAbstained Text | ModelAnnotated Text | ModelPruned Text Text deriving (Show, Eq)
instance ToJSON ModelAnnotationEnvelope where
  toJSON (ModelNoAnnotation ) = object ["kind" .= ("none" :: Text)]
  toJSON (ModelAbstained f0) = object ["kind" .= ("abstained" :: Text), "reason" .= f0]
  toJSON (ModelAnnotated f0) = object ["kind" .= ("annotated" :: Text), "text" .= f0]
  toJSON (ModelPruned f0 f1) = object ["kind" .= ("pruned" :: Text), "handle" .= f0, "text" .= f1]
instance FromJSON ModelAnnotationEnvelope where
  parseJSON = withObject "ModelAnnotationEnvelope" $ \o -> do
    kind <- o .: "kind"
    case (kind :: Text) of
      "none" -> controlObject ["kind"] (\o -> pure ModelNoAnnotation) (Object o)
      "abstained" -> controlObject ["kind", "reason"] (\o -> pure ModelAbstained <*> (o .: "reason")) (Object o)
      "annotated" -> controlObject ["kind", "text"] (\o -> pure ModelAnnotated <*> (o .: "text")) (Object o)
      "pruned" -> controlObject ["kind", "handle", "text"] (\o -> pure ModelPruned <*> (o .: "handle") <*> (o .: "text")) (Object o)
      _ -> Error "unknown ModelCall control variant"
