//! Embed complete Haskell source trees into the installed binaries. Generated
//! `&[(relative_path, contents)]` tables cover the Tidepool library and Exomonad's
//! interactive actor surface without hand-maintained file lists. Only `.hs`
//! sources are included; build artifacts and test-only probes are excluded.
//!
//! The same mechanism carries the package `exomonad new` scaffolds: the workspace
//! skills, the Jev facade, and the starter agent spec are embedded from the
//! files this repository already keeps them in, so scaffolding cannot drift
//! from the source it is copied out of.

#![warn(clippy::unwrap_used, clippy::expect_used)]
#[path = "../../exomonad/actor/src/lookup_tool/qualified_name.rs"]
mod qualified_name;
use qualified_name::qualifier_and_identifier;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=../../exomonad/actor/src/lookup_tool/qualified_name.rs");
    // Shared target directories must not reuse another checkout's source paths.
    println!("cargo:rerun-if-env-changed=CARGO_MANIFEST_DIR");
    #[allow(clippy::expect_used, reason = "CARGO_MANIFEST_DIR")]
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    // The embed root is `haskell/lib` itself (not `haskell/lib/Tidepool`),
    // so every top-level module namespace under it — `Tidepool.*` and
    // `Jev.*` alike — is embedded with no per-namespace registration. A
    // module's relative path under `haskell/lib` is its embedded path
    // verbatim, matching the `-ihaskell/lib` GHC search root actors compile
    // against.
    #[allow(
        clippy::expect_used,
        reason = "haskell/lib must exist relative to the tidepool crate"
    )]
    let stdlib_root = Path::new(&manifest)
        .join("../haskell/lib")
        .canonicalize()
        .expect("haskell/lib must exist relative to the tidepool crate");

    emit_bundle(
        &stdlib_root,
        "../haskell/lib",
        "",
        "EMBEDDED_STDLIB",
        "embedded_stdlib.rs",
    );

    #[allow(
        clippy::expect_used,
        reason = "haskell/actors must exist relative to the tidepool crate"
    )]
    let actor_root = Path::new(&manifest)
        .join("../haskell/actors")
        .canonicalize()
        .expect("haskell/actors must exist relative to the tidepool crate");
    emit_bundle(
        &actor_root,
        "../haskell/actors",
        "",
        "EMBEDDED_EXOMONAD_HASKELL",
        "embedded_exomonad_haskell.rs",
    );

    emit_scaffold_package(Path::new(&manifest).join("../.."));
}

/// The Exomonad package `exomonad new` writes into a project, as
/// `&[(workspace_relative_path, contents)]`, plus the jev-dsl revision the
/// shipped example workspace pins. The template tree is the source of truth;
/// local plans and prompts describe this repository's current run and do not
/// belong in a fresh project.
fn emit_scaffold_package(repository: PathBuf) {
    let template = repository.join("exomonad/examples/workspace/.exomonad");
    println!("cargo:rerun-if-changed={}", template.display());
    let mut entries = Vec::new();
    collect_all(&template, &template, &mut entries);
    entries.retain(|(relative, _)| {
        let path = Path::new(relative);
        !matches!(path.components().next(), Some(std::path::Component::Normal(name)) if name == "plans" || name == "prompts")
            && relative != "config.toml"
    });
    entries.sort();
    let skill_files: Vec<(String, PathBuf)> = entries
        .iter()
        .filter(|(relative, _)| relative.starts_with("skills/"))
        .cloned()
        .collect();
    let entries: Vec<(String, PathBuf)> = entries
        .into_iter()
        .map(|(relative, path)| (format!(".exomonad/{relative}"), path))
        .collect();

    let mut out = String::from(
        "// @generated by build.rs — the package `exomonad new` scaffolds.\n\
         pub(crate) static SCAFFOLD_PACKAGE: &[(&str, &str)] = &[\n",
    );
    for (relative, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let contents = std::fs::read_to_string(path)
            .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
        out.push_str(&format!("    ({relative:?}, {contents:?}),\n"));
    }
    out.push_str("];\n");

    let example_flake = repository.join("exomonad/examples/workspace/flake.nix");
    println!("cargo:rerun-if-changed={}", example_flake.display());
    out.push_str(&format!(
        "/// The jev-dsl revision `exomonad/examples/workspace/flake.nix` pins.\n\
         pub(crate) static JEV_DSL_URL: &str = {:?};\n",
        jev_dsl_url(&example_flake)
    ));

    #[allow(
        clippy::unwrap_used,
        reason = "OUT_DIR is always set by cargo when running a build script"
    )]
    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("scaffold_package.rs");
    #[allow(clippy::expect_used, reason = "write generated scaffold package")]
    std::fs::write(dest, out).expect("write generated scaffold package");

    emit_usage_pointer_index(&repository, &skill_files);
}

/// Generate the compact lookup table consumed by `exomonad-actor`. The
/// facade already owns the shipped source inventory; only identifier/locator
/// pairs cross the crate boundary, so actor builds never embed skill text.
fn emit_usage_pointer_index(repository: &Path, skill_files: &[(String, PathBuf)]) {
    let checks = repository.join("exomonad/examples/workspace/.exomonad/checks");
    println!("cargo:rerun-if-changed={}", checks.display());
    let mut sources: Vec<(String, PathBuf)> = std::fs::read_dir(&checks)
        .unwrap_or_else(|error| panic!("read {}: {error}", checks.display()))
        .map(|entry| {
            entry
                .unwrap_or_else(|error| panic!("read entry in {}: {error}", checks.display()))
                .path()
        })
        .filter(|path| path.extension().is_some_and(|extension| extension == "hs"))
        .map(|path| {
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            (format!(".exomonad/checks/{name}"), path)
        })
        .collect();
    sources.sort_by(|left, right| left.0.cmp(&right.0));
    for (relative, path) in skill_files.iter().filter(|(relative, _)| {
        Path::new(relative)
            .file_name()
            .is_some_and(|name| name == "SKILL.md")
    }) {
        sources.push((format!(".exomonad/{relative}"), path.clone()));
    }

    let mut index = BTreeMap::<String, String>::new();
    for (locator, path) in sources {
        println!("cargo:rerun-if-changed={}", path.display());
        let source = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
        for token in raw_tokens(&source) {
            let token = token.trim_matches('.');
            let Some((_qualifier, identifier)) = qualifier_and_identifier(token) else {
                continue;
            };
            index
                .entry(identifier.to_owned())
                .or_insert(locator.clone());
        }
    }

    let mut out = String::from(
        "// @generated by build.rs — compact shipped usage pointers.\n\
         pub(crate) static EXOMONAD_USAGE_POINTERS: &[(&str, &str)] = &[\n",
    );
    for (identifier, locator) in index {
        out.push_str(&format!("    ({identifier:?}, {locator:?}),\n"));
    }
    out.push_str("];\n");
    #[allow(
        clippy::unwrap_used,
        reason = "Cargo supplies OUT_DIR to build scripts"
    )]
    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("usage_pointers.rs");
    #[allow(clippy::expect_used, reason = "generation failure must fail the build")]
    std::fs::write(dest, out).expect("write generated usage pointers");
}

fn raw_tokens(source: &str) -> impl Iterator<Item = &str> {
    let is_word = |character: char| {
        character.is_ascii_alphanumeric()
            || character == '_'
            || character == '\''
            || character == '.'
    };
    let mut start = None;
    let mut tokens = Vec::new();
    for (index, character) in source.char_indices() {
        if is_word(character) {
            start.get_or_insert(index);
        } else if let Some(begin) = start.take() {
            tokens.push(&source[begin..index]);
        }
    }
    if let Some(begin) = start {
        tokens.push(&source[begin..]);
    }
    tokens.into_iter()
}

/// The pinned jev-dsl flake URL, read out of the example workspace's own
/// `flake.nix` so the revision exists in exactly one place.
fn jev_dsl_url(flake: &Path) -> String {
    let text = std::fs::read_to_string(flake)
        .unwrap_or_else(|error| panic!("read {}: {error}", flake.display()));
    text.lines()
        .find_map(|line| {
            let (_, rest) = line.split_once("url = \"")?;
            let (url, _) = rest.split_once('"')?;
            url.contains("jev-dsl").then(|| url.to_owned())
        })
        .unwrap_or_else(|| panic!("no jev-dsl input url in {}", flake.display()))
}

fn collect_all(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    #[allow(clippy::expect_used, reason = "read_dir")]
    for entry in std::fs::read_dir(dir).expect("read_dir") {
        #[allow(clippy::expect_used, reason = "dir entry")]
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            collect_all(root, &path, out);
        } else {
            #[allow(clippy::expect_used, reason = "under root")]
            let relative = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((relative, path));
        }
    }
}

fn emit_bundle(root: &Path, watch_root: &str, prefix: &str, symbol: &str, output: &str) {
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect(root, root, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = format!(
        "// @generated by build.rs — embedded Haskell sources.\n\
         pub static {symbol}: &[(&str, &str)] = &[\n"
    );
    for (rel, abs) in &entries {
        println!("cargo:rerun-if-changed={watch_root}/{rel}");
        #[allow(clippy::expect_used, reason = "read an embedded Haskell source")]
        let source = std::fs::read_to_string(abs).expect("read embedded source");
        out.push_str(&format!(
            "    ({:?}, {source:?}),\n",
            format!("{prefix}{rel}")
        ));
    }
    out.push_str("];\n");
    // Rerun if files are added/removed under the tree.
    println!("cargo:rerun-if-changed={watch_root}");

    #[allow(
        clippy::unwrap_used,
        reason = "OUT_DIR is always set by cargo when running a build script"
    )]
    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join(output);
    #[allow(clippy::expect_used, reason = "write generated source bundle")]
    std::fs::write(dest, out).expect("write generated source bundle");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    #[allow(clippy::expect_used, reason = "read_dir")]
    for entry in std::fs::read_dir(dir).expect("read_dir") {
        #[allow(clippy::expect_used, reason = "dir entry")]
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            if name == "Prelude_cbor" {
                continue;
            }
            collect(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "hs") {
            // This module exists only to probe a GHC representation detail;
            // other `Internal` modules are production library dependencies.
            if path
                .file_name()
                .is_some_and(|name| name == "DataTextProbe.hs")
            {
                continue;
            }
            #[allow(clippy::expect_used, reason = "under root")]
            let rel = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}
