//! Embed complete Haskell source trees into the installed binaries. Generated
//! `&[(relative_path, contents)]` tables cover the Tidepool library and Exomonad's
//! interactive actor surface without hand-maintained file lists. Only `.hs`
//! sources are included; build artifacts and test-only probes are excluded.
//!
//! The same mechanism carries project-owned defaults for `exomonad new`.
//! Reusable workspace sources are cloned when the command runs.

#![warn(clippy::unwrap_used, clippy::expect_used)]
use std::path::{Path, PathBuf};

fn main() {
    // Shared target directories must not reuse another checkout's source paths.
    println!("cargo:rerun-if-env-changed=CARGO_MANIFEST_DIR");
    #[allow(clippy::expect_used, reason = "CARGO_MANIFEST_DIR")]
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");

    // Embedding the full `bridge/haskell` trees as string literals means any
    // `.hs` edit anywhere under them forces a full rebuild and relink of this
    // crate (`cargo:rerun-if-changed` on both trees). That cost only pays for
    // itself in a release/install build, where the binary must carry its own
    // copy of the sources. A dev build reads the checkout directly at
    // runtime (`haskell_sources::ensure_stdlib`/`ensure_exomonad_haskell`
    // walk up from the working directory), so it emits empty bundles instead
    // and watches nothing under either tree.
    println!("cargo:rerun-if-env-changed=TIDEPOOL_EMBED_HASKELL");
    let embed =
        std::env::var_os("TIDEPOOL_EMBED_HASKELL").as_deref() == Some(std::ffi::OsStr::new("1"));

    if embed {
        // The embed root is `haskell/lib` itself (not `haskell/lib/Tidepool`),
        // so every top-level module namespace under it — `Tidepool.*` and
        // `Jev.*` alike — is embedded with no per-namespace registration. A
        // module's relative path under `haskell/lib` is its embedded path
        // verbatim, matching the `-ihaskell/lib` GHC search root actors compile
        // against.
        #[allow(
            clippy::expect_used,
            reason = "haskell/lib must exist relative to the tidepool crate"
        )]
        let stdlib_root = Path::new(&manifest)
            .join("../haskell/lib")
            .canonicalize()
            .expect("haskell/lib must exist relative to the tidepool crate");

        emit_bundle(
            &stdlib_root,
            "../haskell/lib",
            "",
            "EMBEDDED_STDLIB",
            "embedded_stdlib.rs",
        );

        #[allow(
            clippy::expect_used,
            reason = "haskell/actors must exist relative to the tidepool crate"
        )]
        let actor_root = Path::new(&manifest)
            .join("../haskell/actors")
            .canonicalize()
            .expect("haskell/actors must exist relative to the tidepool crate");
        emit_bundle(
            &actor_root,
            "../haskell/actors",
            "",
            "EMBEDDED_EXOMONAD_HASKELL",
            "embedded_exomonad_haskell.rs",
        );
    } else {
        emit_empty_bundle("EMBEDDED_STDLIB", "embedded_stdlib.rs");
        emit_empty_bundle("EMBEDDED_EXOMONAD_HASKELL", "embedded_exomonad_haskell.rs");
    }

    emit_scaffold_package(Path::new(&manifest).join("../.."));
}

/// Dev-build stand-in for [`emit_bundle`]: same generated symbol and type, no
/// entries, and no `rerun-if-changed` on the source tree it would otherwise
/// watch — so editing `.hs` files under `bridge/haskell` does not touch this
/// crate's build script output.
fn emit_empty_bundle(symbol: &str, output: &str) {
    let out = format!(
        "// @generated by build.rs — TIDEPOOL_EMBED_HASKELL is unset; sources are read from the checkout at runtime.\n\
         pub static {symbol}: &[(&str, &str)] = &[];\n"
    );
    #[allow(
        clippy::unwrap_used,
        reason = "OUT_DIR is always set by cargo when running a build script"
    )]
    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join(output);
    #[allow(clippy::expect_used, reason = "write generated empty source bundle")]
    std::fs::write(dest, out).expect("write generated empty source bundle");
}

/// The project-owned files `exomonad new` writes, alongside the URL for the
/// generic workspace repository it clones.
fn emit_scaffold_package(repository: PathBuf) {
    let template = repository.join("exomonad/examples/workspace/.exomonad");
    println!("cargo:rerun-if-changed={}", template.display());
    let mut entries = Vec::new();
    collect_all(&template, &template, &mut entries);
    entries.retain(|(relative, _)| {
        relative == "AgentSpec.hs"
            || relative.starts_with("prompts/")
            || relative.starts_with("plans/")
    });
    entries.sort();
    let entries: Vec<(String, PathBuf)> = entries
        .into_iter()
        .map(|(relative, path)| (format!(".exomonad/{relative}"), path))
        .collect();

    let mut out = String::from(
        "// @generated by build.rs — the package `exomonad new` scaffolds.\n\
         pub(crate) static SCAFFOLD_PACKAGE: &[(&str, &str)] = &[\n",
    );
    for (relative, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let contents = std::fs::read_to_string(path)
            .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
        out.push_str(&format!("    ({relative:?}, {contents:?}),\n"));
    }
    out.push_str("];\n");

    let example_flake = repository.join("exomonad/examples/workspace/flake.nix");
    println!("cargo:rerun-if-changed={}", example_flake.display());
    out.push_str(&format!(
        "/// The jev-dsl revision `exomonad/examples/workspace/flake.nix` pins.\n\
         pub(crate) static JEV_DSL_URL: &str = {:?};\n",
        jev_dsl_url(&example_flake)
    ));
    out.push_str(&format!(
        "#[cfg_attr(test, allow(dead_code))]\npub(crate) static DEFAULT_WORKSPACE_URL: &str = {:?};\n",
        "https://github.com/tidepool-heavy-industries/exomonad-default-workspace.git"
    ));

    #[allow(
        clippy::unwrap_used,
        reason = "OUT_DIR is always set by cargo when running a build script"
    )]
    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("scaffold_package.rs");
    #[allow(clippy::expect_used, reason = "write generated scaffold package")]
    std::fs::write(dest, out).expect("write generated scaffold package");
}

/// The pinned jev-dsl flake URL, read out of the example workspace's own
/// `flake.nix` so the revision exists in exactly one place.
fn jev_dsl_url(flake: &Path) -> String {
    let text = std::fs::read_to_string(flake)
        .unwrap_or_else(|error| panic!("read {}: {error}", flake.display()));
    text.lines()
        .find_map(|line| {
            let (_, rest) = line.split_once("url = \"")?;
            let (url, _) = rest.split_once('"')?;
            url.contains("jev-dsl").then(|| url.to_owned())
        })
        .unwrap_or_else(|| panic!("no jev-dsl input url in {}", flake.display()))
}

fn collect_all(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    #[allow(clippy::expect_used, reason = "read_dir")]
    for entry in std::fs::read_dir(dir).expect("read_dir") {
        #[allow(clippy::expect_used, reason = "dir entry")]
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            collect_all(root, &path, out);
        } else {
            #[allow(clippy::expect_used, reason = "under root")]
            let relative = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((relative, path));
        }
    }
}

fn emit_bundle(root: &Path, watch_root: &str, prefix: &str, symbol: &str, output: &str) {
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect(root, root, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = format!(
        "// @generated by build.rs — embedded Haskell sources.\n\
         pub static {symbol}: &[(&str, &str)] = &[\n"
    );
    for (rel, abs) in &entries {
        println!("cargo:rerun-if-changed={watch_root}/{rel}");
        #[allow(clippy::expect_used, reason = "read an embedded Haskell source")]
        let source = std::fs::read_to_string(abs).expect("read embedded source");
        out.push_str(&format!(
            "    ({:?}, {source:?}),\n",
            format!("{prefix}{rel}")
        ));
    }
    out.push_str("];\n");
    // Rerun if files are added/removed under the tree.
    println!("cargo:rerun-if-changed={watch_root}");

    #[allow(
        clippy::unwrap_used,
        reason = "OUT_DIR is always set by cargo when running a build script"
    )]
    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join(output);
    #[allow(clippy::expect_used, reason = "write generated source bundle")]
    std::fs::write(dest, out).expect("write generated source bundle");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    #[allow(clippy::expect_used, reason = "read_dir")]
    for entry in std::fs::read_dir(dir).expect("read_dir") {
        #[allow(clippy::expect_used, reason = "dir entry")]
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            if name == "Prelude_cbor" {
                continue;
            }
            collect(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "hs") {
            // This module exists only to probe a GHC representation detail;
            // other `Internal` modules are production library dependencies.
            if path
                .file_name()
                .is_some_and(|name| name == "DataTextProbe.hs")
            {
                continue;
            }
            #[allow(clippy::expect_used, reason = "under root")]
            let rel = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}
