//! Embed the COMPLETE Haskell stdlib tree (`../haskell/lib/Tidepool/**.hs`) into
//! the binary at build time, so the installed server is self-sufficient from any
//! directory. Generates `$OUT_DIR/embedded_stdlib.rs` with a
//! `&[(relpath, contents)]` table, walking the real tree (no hand-maintained
//! subset to drift) and including only `.hs` sources — skipping the `Prelude_cbor`
//! build artifacts and the test-only `Internal/` probe.

use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let root = Path::new(&manifest)
        .join("../haskell/lib/Tidepool")
        .canonicalize()
        .expect("haskell/lib/Tidepool must exist relative to the tidepool crate");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect(&root, &root, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from(
        "// @generated by build.rs — embedded Haskell stdlib (Tidepool/<rel>, contents).\n\
         pub static EMBEDDED_STDLIB: &[(&str, &str)] = &[\n",
    );
    for (rel, abs) in &entries {
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    (\"Tidepool/{}\", include_str!(r\"{}\")),\n",
            rel,
            abs.display()
        ));
    }
    out.push_str("];\n");
    // Rerun if files are added/removed under the tree.
    println!("cargo:rerun-if-changed={}", root.display());

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("embedded_stdlib.rs");
    std::fs::write(dest, out).expect("write embedded_stdlib.rs");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    for entry in std::fs::read_dir(dir).expect("read_dir") {
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            // Skip the test-only probe and the CBOR build-artifact dir.
            if name == "Internal" || name == "Prelude_cbor" {
                continue;
            }
            collect(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "hs") {
            let rel = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}
