//! Embed complete Haskell source trees into the installed binaries. Generated
//! `&[(relative_path, contents)]` tables cover the Tidepool library and Shoal's
//! actor bootstrap policy without hand-maintained file lists. Only `.hs`
//! sources are included; build artifacts and test-only probes are excluded.

#![warn(clippy::unwrap_used, clippy::expect_used)]
use std::path::{Path, PathBuf};

fn main() {
    #[allow(clippy::expect_used, reason = "CARGO_MANIFEST_DIR")]
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    #[allow(
        clippy::expect_used,
        reason = "haskell/lib/Tidepool must exist relative to the tidepool crate"
    )]
    let stdlib_root = Path::new(&manifest)
        .join("../haskell/lib/Tidepool")
        .canonicalize()
        .expect("haskell/lib/Tidepool must exist relative to the tidepool crate");

    emit_bundle(
        &stdlib_root,
        "Tidepool/",
        "EMBEDDED_STDLIB",
        "embedded_stdlib.rs",
    );

    #[allow(
        clippy::expect_used,
        reason = "haskell/actors must exist relative to the tidepool crate"
    )]
    let actor_root = Path::new(&manifest)
        .join("../haskell/actors")
        .canonicalize()
        .expect("haskell/actors must exist relative to the tidepool crate");
    emit_bundle(
        &actor_root,
        "",
        "EMBEDDED_ACTOR_POLICY",
        "embedded_actor_policy.rs",
    );
}

fn emit_bundle(root: &Path, prefix: &str, symbol: &str, output: &str) {
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect(root, root, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = format!(
        "// @generated by build.rs — embedded Haskell sources.\n\
         pub static {symbol}: &[(&str, &str)] = &[\n"
    );
    for (rel, abs) in &entries {
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    (\"{}{}\", include_str!(r\"{}\")),\n",
            prefix,
            rel,
            abs.display()
        ));
    }
    out.push_str("];\n");
    // Rerun if files are added/removed under the tree.
    println!("cargo:rerun-if-changed={}", root.display());

    #[allow(
        clippy::unwrap_used,
        reason = "OUT_DIR is always set by cargo when running a build script"
    )]
    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join(output);
    #[allow(clippy::expect_used, reason = "write generated source bundle")]
    std::fs::write(dest, out).expect("write generated source bundle");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    #[allow(clippy::expect_used, reason = "read_dir")]
    for entry in std::fs::read_dir(dir).expect("read_dir") {
        #[allow(clippy::expect_used, reason = "dir entry")]
        let path = entry.expect("dir entry").path();
        if path.is_dir() {
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            if name == "Prelude_cbor" {
                continue;
            }
            collect(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "hs") {
            // This module exists only to probe a GHC representation detail;
            // other `Internal` modules are production library dependencies.
            if path
                .file_name()
                .is_some_and(|name| name == "DataTextProbe.hs")
            {
                continue;
            }
            #[allow(clippy::expect_used, reason = "under root")]
            let rel = path
                .strip_prefix(root)
                .expect("under root")
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}
