[package]
name = "tidepool-tide"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Tidepool interactive shell and compiler"
publish = false

[dependencies]
pest = "2.7"
pest_derive = "2.7"
tidepool-repr.workspace = true
tidepool-bridge.workspace = true
tidepool-bridge-derive.workspace = true
tidepool-eval.workspace = true
tidepool-effect.workspace = true
tidepool-macro.workspace = true
tidepool-codegen.workspace = true
frunk.workspace = true
ureq.workspace = true
url.workspace = true
rustyline = "15"
anyhow = "1.0"
thiserror.workspace = true
clap = { version = "4.4", features = ["derive"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
miette = { version = "7", features = ["fancy"] }

[package.metadata.tidepool]
haskell-deps = ["freer-simple"]
