# @generated by scripts/buck2-first-party.py from exact Rust include inputs.
load("@prelude//:rules.bzl", "export_file")

def declare_rust_test_inputs():
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_BadAssociated_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/BadAssociated.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_BadClass_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/BadClass.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_BadFD_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/BadFD.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_BadFamily_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/BadFamily.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_BadNextClass_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/BadNextClass.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_BadNextFamily_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/BadNextFamily.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_BadRetraction_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/BadRetraction.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_Common_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/Common.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_Consumer_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/Consumer.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_Next_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/Next.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_NextConsumer_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/NextConsumer.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_Old_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/Old.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_cell_splitter_fixtures_declaration_join_exact_isolation_Public_hs", src = "test-cell-splitter/fixtures/declaration-join/exact-isolation/Public.hs", visibility = ["PUBLIC"])
    export_file(name = "rust_input_test_prepared_stg_FreerResumeExpectations_json", src = "test-prepared-stg/FreerResumeExpectations.json", visibility = ["PUBLIC"])
