[package]
name = "tidepool-repr"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Intermediate representation for the Tidepool compiler"
readme = "../README.md"

[dependencies]
ciborium.workspace = true
thiserror.workspace = true
rustc-hash.workspace = true
serde_json.workspace = true

[dev-dependencies]
proptest.workspace = true
serial_test.workspace = true
tidepool-testing.workspace = true
