//! Runtime lookup for the compact usage table generated by the facade.
//!
//! The actor crate consumes a small immutable table supplied by its host. The
//! host owns the shipped workspace sources and builds that table, so editing a
//! skill does not embed its text or rebuild this crate.

use std::path::Path;

/// An immutable `(bare identifier, workspace locator)` table generated by the
/// facade build owner.
pub type UsagePointerTable = &'static [(&'static str, &'static str)];

/// Resolve a shipped usage pointer for `name` from `table`.
pub(crate) fn pointer_for(table: UsagePointerTable, name: &str) -> Option<String> {
    let locator = table
        .iter()
        .find_map(|(identifier, locator)| (*identifier == name).then_some(*locator))?;
    present(locator, Path::new("."))
}

/// A locator as a reader in `workspace` can follow it, or `None` when they
/// cannot. Skills are named because they are shipped in every scaffold;
/// checks are offered only where the workspace path exists.
fn present(locator: &str, workspace: &Path) -> Option<String> {
    if let Some(skill) = locator
        .strip_prefix(".exomonad/skills/")
        .and_then(|rest| rest.strip_suffix("/SKILL.md"))
    {
        return Some(format!("skill {skill}"));
    }
    workspace
        .join(locator)
        .is_file()
        .then(|| locator.to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pointer_lookup_uses_the_supplied_immutable_table() {
        static TABLE: &[(&str, &str)] = &[("call", ".exomonad/skills/exomonad-command/SKILL.md")];
        assert_eq!(
            pointer_for(TABLE, "call").as_deref(),
            Some("skill exomonad-command")
        );
        assert_eq!(pointer_for(TABLE, "missing"), None);
    }

    #[test]
    fn a_pointer_is_offered_only_where_it_can_be_followed() {
        let elsewhere = tempfile::tempdir().unwrap();
        assert_eq!(
            present(
                ".exomonad/skills/exomonad-command/SKILL.md",
                elsewhere.path()
            )
            .as_deref(),
            Some("skill exomonad-command")
        );
        assert_eq!(
            present(".exomonad/checks/handler-call.hs", elsewhere.path()),
            None
        );
        std::fs::create_dir_all(elsewhere.path().join(".exomonad/checks")).unwrap();
        std::fs::write(
            elsewhere.path().join(".exomonad/checks/handler-call.hs"),
            "",
        )
        .unwrap();
        assert_eq!(
            present(".exomonad/checks/handler-call.hs", elsewhere.path()).as_deref(),
            Some(".exomonad/checks/handler-call.hs")
        );
    }
}
