#!/usr/bin/env bash
set -euo pipefail

# Materialize the pinned Nix closures on the executor before remote actions.
# `nix eval` here only identifies paths and does not compile the toolchains.
cd "$(dirname "$0")/.."

usage() {
  printf 'Usage: scripts/buck2-configure.sh [--runtime-stdlib] [--tests]\n'
}

runtime_stdlib=false
test_toolchain=false
for argument in "$@"; do
  case "$argument" in
    --runtime-stdlib) runtime_stdlib=true ;;
    --tests) test_toolchain=true ;;
    --help|-h) usage; exit 0 ;;
    *) usage >&2; exit 2 ;;
  esac
done

if ! mountpoint -q "$PWD/buck-out"; then
  printf 'Provision a real per-checkout buck-out bind mount before configuring Buck: %s/buck-out\n' "$PWD" >&2
  exit 1
fi

remote_enabled=false
remote_toolchain=""
if [ "${TIDEPOOL_BUCK_REMOTE:-false}" = true ]; then
  platform_file=${TIDEPOOL_BUCK_PLATFORM_FILE:-/etc/swarm-build/platform}
  test -r "$platform_file" || { echo "Missing remote platform identity: $platform_file" >&2; exit 1; }
  remote_toolchain="$(cat "$platform_file")"
  [[ $remote_toolchain =~ ^[0-9a-f]{64}$ ]] || { echo 'Invalid remote platform identity' >&2; exit 1; }
  remote_address=${TIDEPOOL_BUCK_REMOTE_ADDRESS:-grpc://127.0.0.1:50051}
  [[ $remote_address =~ ^grpc://(localhost|127\.0\.0\.1):[0-9]+$ ]] || { echo 'Remote endpoint must use an SSH tunnel on loopback' >&2; exit 1; }
  remote_enabled=true
fi

if [[ -z ${TIDEPOOL_DEV_SHELL:-} ]]; then
  exec bash scripts/dev-shell.sh bash scripts/buck2-configure.sh "$@"
fi
flake_source=${TIDEPOOL_DEV_SHELL%#*}
system="$(nix eval --raw --impure --expr 'builtins.currentSystem')"
output_path() {
  nix eval --raw "${flake_source}#packages.${system}.buck-$1.outPath"
}
rust="$(output_path rust)"
ghc="$(output_path ghc)"
ghc_libdir="$("${ghc}/bin/ghc" --print-libdir)"
# Test packages select a distinct wrapper/package environment. Never substitute
# this libdir or compiler for the production worker's declared GHC closure.
test_ghc=
test_ghc_bin=
test_ghc_pkg=
test_haddock=
test_ghc_libdir=
haskell_test_closure=
jev_sources=
if [[ $test_toolchain == true ]]; then
  test_ghc_root="$(output_path test-ghc)"
  test_ghc=$test_ghc_root/bin/ghc
  test_ghc_bin=$test_ghc_root/bin
  test_ghc_pkg=$test_ghc_root/bin/ghc-pkg
  test_haddock=$test_ghc_root/bin/haddock
  test_ghc_libdir="$("$test_ghc" --print-libdir)"
  haskell_test_closure="$(output_path haskell-test-closure)"
  jev_sources="$(output_path jev-sources)"
fi
cc="$(output_path cc)"
binutils="$(output_path binutils)"
node="$(output_path node)"
npm_cache="$(output_path npm-cache)"
browser_node="$(output_path browser-node)"
browser_npm_cache="$(output_path browser-npm-cache)"
playwright_browsers="$(output_path playwright-browsers)"
browser_test_closure="$(output_path browser-test-closure)"
test_tools_closure="$(output_path test-tools-closure)"
matched_harness_source="$(output_path matched-harness-source)"
git_path="$(output_path test-git)"
bash_path="$(output_path bash)"
coreutils="$(output_path coreutils)"
tar_path="$(output_path tar)"
gzip="$(output_path gzip)"
python="$(output_path python)"
bubblewrap="$(output_path bubblewrap)"
runtime_stdlib_sources=
runtime_stdlib_products=
runtime_stdlib_extract=
# Runtime commands are pinned tool inputs, independently of catalog products.
exomonad_runtime_tools="$(output_path exomonad-runtime-tools)"
if [[ $runtime_stdlib == true ]]; then
  # The default shell can use a reduced toolchain-only tree. Project resources
  # require a full committed capture, independently of mounted build outputs.
  package_flake_source=${TIDEPOOL_DEV_FLAKE:-git+file://$PWD?rev=$(git rev-parse HEAD)\&submodules=1}
  case "$package_flake_source" in
    git+*\?*rev=*) ;;
    *) echo '--runtime-stdlib requires a full revision-pinned Git project flake' >&2; exit 2 ;;
  esac
  captured_source=$(nix flake metadata --json --no-write-lock-file "$package_flake_source" |
    "$python/bin/python3" -c 'import json,sys; print(json.load(sys.stdin)["path"])')
  if [[ ! -d $captured_source/bridge/haskell/lib ||
        ! -f $captured_source/tidepool/toolchain/src/bin/tidepool-module-package.rs ]]; then
    echo '--runtime-stdlib requires the full project source; a reduced toolchain flake cannot supply compiler products' >&2
    exit 2
  fi
  # Evaluation declares paths; materialize the matched package before its gate.
  runtime_stdlib_sources="$(nix eval --raw "${package_flake_source}#packages.${system}.runtime-stdlib-sources.outPath")"
  runtime_stdlib_products="$(nix eval --raw "${package_flake_source}#packages.${system}.runtime-stdlib-products.outPath")"
  runtime_stdlib_extract="$(nix eval --raw "${package_flake_source}#packages.${system}.tidepool-extract.outPath")"
fi
cmake="$(output_path cmake)"
perl="$(output_path perl)"
pkg_config="$(output_path pkg-config)"

tmp_config=$(mktemp "$PWD/.buckconfig.local.XXXXXX")
trap 'rm -f -- "$tmp_config"' EXIT
cat > "$tmp_config" <<EOF
# Generated by scripts/buck2-configure.sh from flake.lock.
[nix]
rustc = $rust/bin/rustc
rustdoc = $rust/bin/rustdoc
rustfmt = $rust/bin/rustfmt
clippy = $rust/bin/clippy-driver
ghc = $ghc/bin/ghc
ghc_bin = $ghc/bin
ghc_pkg = $ghc/bin/ghc-pkg
haddock = $ghc/bin/haddock
ghc_libdir = $ghc_libdir
test_ghc = $test_ghc
test_ghc_bin = $test_ghc_bin
test_ghc_pkg = $test_ghc_pkg
test_haddock = $test_haddock
test_ghc_libdir = $test_ghc_libdir
haskell_test_closure = $haskell_test_closure
jev_sources = $jev_sources
cc = $cc/bin/cc
cxx = $cc/bin/c++
ar = $binutils/bin/ar
node = $node/bin/node
npm_cache = $npm_cache
npm = $node/bin/npm
browser_node = $browser_node/bin/node
browser_npm = $browser_node/bin/npm
browser_npm_cache = $browser_npm_cache
playwright_browsers = $playwright_browsers
browser_test_closure = $browser_test_closure
test_tools_closure = $test_tools_closure
matched_harness_source = $matched_harness_source
git = $git_path/bin/git
bash = $bash_path/bin/bash
coreutils = $coreutils/bin
sleep = $coreutils/bin/sleep
tar = $tar_path/bin/tar
gzip = $gzip/bin/gzip
python = $python/bin/python3
bubblewrap = $bubblewrap/bin/bwrap
runtime_stdlib_sources = $runtime_stdlib_sources
runtime_stdlib_products = $runtime_stdlib_products
runtime_stdlib_extract = $runtime_stdlib_extract
runtime_stdlib_ghc_libdir = $ghc_libdir
exomonad_runtime_tools = $exomonad_runtime_tools
cmake = $cmake/bin/cmake
perl = $perl/bin/perl
pkg_config = $pkg_config/bin/pkg-config
action_path = $rust/bin:$cc/bin:$binutils/bin:$cmake/bin:$perl/bin:$pkg_config/bin:$python/bin:$bash_path/bin:$coreutils/bin:$tar_path/bin:$gzip/bin:$node/bin:$git_path/bin

[remote]
enabled = $remote_enabled
toolchain = $remote_toolchain
EOF
if [ "$remote_enabled" = true ]; then
  cat >> "$tmp_config" <<EOF

[buck2_re_client]
action_cache_address = $remote_address
engine_address = $remote_address
cas_address = $remote_address
tls = false
instance_name = swarm
EOF
fi
chmod 0644 "$tmp_config"
mv -f -- "$tmp_config" .buckconfig.local
trap - EXIT
printf 'Wrote %s/.buckconfig.local\n' "$PWD"
