#!/usr/bin/env python3
"""Derive Reindeer's dependency-only manifest from the migrated Cargo packages."""
import argparse
import json
from pathlib import Path
import subprocess
import tomllib

ROOT = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser()
parser.add_argument("--output-dir", type=Path, required=True)
DEST = parser.parse_args().output_dir.resolve()
DEST.mkdir(parents=True, exist_ok=True)
# Test roots retain their direct dev-dependency closure. These four additional
# roots are library-only; their dev dependencies and codegen's replaced build
# script are not part of the native library dependency bundle.
TEST_ROOTS = {"tidepool-atomic-write", "tidepool-repr", "tidepool-heap"}
LIBRARY_ROOTS = {"tidepool-bignum", "tidepool-bridge", "tidepool-effect", "tidepool-codegen"}
ROOTS = TEST_ROOTS | LIBRARY_ROOTS
LINUX_TARGETS = {None, "cfg(unix)"}
metadata = json.loads(subprocess.check_output([
    "cargo", "metadata", "--locked", "--filter-platform", "x86_64-unknown-linux-gnu",
    "--format-version", "1",
], cwd=ROOT))
packages = {p["id"]: p for p in metadata["packages"]}
nodes = {p["id"]: p for p in metadata["resolve"]["nodes"]}
selected = [p for p in packages.values() if p["name"] in ROOTS and p["source"] is None]
if len(selected) != len(ROOTS) or {p["name"] for p in selected} != ROOTS:
    raise SystemExit("Missing migrated Cargo package")
dependencies = {}
for package in selected:
    if package["features"]:
        raise SystemExit(f"Model Cargo feature selection before migrating {package['name']}")
    library_only = package["name"] in LIBRARY_ROOTS
    resolved_deps = nodes[package["id"]]["deps"]
    for dependency in package["dependencies"]:
        kind = dependency["kind"]
        # The generated library-only packages don't build their test targets.
        if library_only and kind == "dev":
            continue
        # codegen's build.rs is replaced by the checked-in native Buck C action.
        if package["name"] == "tidepool-codegen" and kind == "build":
            if dependency["name"] != "cc" or dependency["rename"] is not None or dependency["target"] is not None:
                raise SystemExit(f"Unmodeled codegen build dependency: {dependency['name']}")
            continue
        if kind == "build":
            raise SystemExit(f"Model build dependency for {package['name']}: {dependency['name']}")
        if dependency["optional"]:
            raise SystemExit(f"Model optional dependency for {package['name']}: {dependency['name']}")
        target_platform = dependency["target"]
        if target_platform not in LINUX_TARGETS:
            raise SystemExit(
                f"Unsupported Linux dependency selector in {package['name']}: {target_platform}"
            )
        dep_name = (dependency["rename"] or dependency["name"]).replace("-", "_")
        matching_edges = [
            edge for edge in resolved_deps
            if edge["name"] == dep_name
            and any(
                dep_kind["kind"] == kind and dep_kind["target"] == target_platform
                for dep_kind in edge["dep_kinds"]
            )
        ]
        if len(matching_edges) != 1:
            raise SystemExit(
                f"Missing or ambiguous Linux-resolved dependency {dep_name} in {package['name']}"
            )
        edge = matching_edges[0]
        target = packages[edge["pkg"]]
        if target["source"] is None:
            if target["name"] not in ROOTS:
                raise SystemExit(f"Unmigrated local dependency: {target['name']}")
            continue
        if target["source"] != "registry+https://github.com/rust-lang/crates.io-index":
            raise SystemExit(f"Declare non-registry source explicitly: {target['source']}")
        key = (target["name"], target["version"])
        spec = dependencies.setdefault(key, {"features": set(), "default": False})
        spec["features"].update(dependency["features"])
        spec["default"] |= dependency["uses_default_features"]
lines = [
    '# @generated by scripts/buck2-dependencies.py; Cargo manifests and root lock own dependencies.',
    '[package]', 'name = "tidepool-buck-dependencies"', 'version = "0.0.0"',
    'edition = "2021"', 'publish = false', '[workspace]', '[lib]', 'path = "empty.rs"',
    '[dependencies]',
]
for (name, version), spec in sorted(dependencies.items()):
    alias = name if sum(n == name for n, _ in dependencies) == 1 else name + "-" + version.replace(".", "_")
    fields = [f'package = {json.dumps(name)}', f'version = {json.dumps("=" + version)}',
              'default-features = ' + str(spec["default"]).lower(),
              'features = ' + json.dumps(sorted(spec["features"]))]
    lines.append(json.dumps(alias) + ' = { ' + ', '.join(fields) + ' }')
(DEST / 'Cargo.toml').write_text('\n'.join(lines) + '\n')
(DEST / 'Cargo.lock').write_bytes((ROOT / 'Cargo.lock').read_bytes())
subprocess.run(['cargo', 'metadata', '--offline', '--manifest-path', str(DEST / 'Cargo.toml'),
                '--format-version', '1', '--filter-platform', 'x86_64-unknown-linux-gnu'],
               cwd=ROOT, stdout=subprocess.DEVNULL, check=True)
root_lock = tomllib.loads((ROOT / 'Cargo.lock').read_text())
generated_lock = tomllib.loads((DEST / 'Cargo.lock').read_text())
def identity(p):
    return p['name'], p['version'], p.get('source'), p.get('checksum')
accepted = {identity(p) for p in root_lock['package']}
for package in generated_lock['package']:
    if package['name'] == 'tidepool-buck-dependencies' and package.get('source') is None:
        continue
    if identity(package) not in accepted:
        raise SystemExit(f"Generated dependency escaped root Cargo.lock: {package['name']} {package['version']}")
