#!/usr/bin/env bash
set -euo pipefail

# Materialize the pinned Nix closures on the executor before remote actions.
# `nix eval` here only identifies paths and does not compile the toolchains.
cd "$(dirname "$0")/.."
if [[ -z ${TIDEPOOL_DEV_SHELL:-} ]]; then
  exec bash scripts/dev-shell.sh bash scripts/buck2-configure.sh "$@"
fi
flake_source=${TIDEPOOL_DEV_SHELL%#*}
system="$(nix eval --raw --impure --expr 'builtins.currentSystem')"
output_path() {
  nix eval --raw "${flake_source}#packages.${system}.buck-$1.outPath"
}
rust="$(output_path rust)"
ghc="$(output_path ghc)"
ghc_libdir="$("${ghc}/bin/ghc" --print-libdir)"
cc="$(output_path cc)"
binutils="$(output_path binutils)"
node="$(output_path node)"
npm_cache="$(output_path npm-cache)"
browser_node="$(output_path browser-node)"
browser_npm_cache="$(output_path browser-npm-cache)"
playwright_browsers="$(output_path playwright-browsers)"
browser_test_closure="$(output_path browser-test-closure)"
git_path="$(output_path test-git)"
bash_path="$(output_path bash)"
coreutils="$(output_path coreutils)"
tar_path="$(output_path tar)"
gzip="$(output_path gzip)"
python="$(output_path python)"
cmake="$(output_path cmake)"
perl="$(output_path perl)"
pkg_config="$(output_path pkg-config)"
remote_enabled=false
remote_toolchain=""
if [ "${TIDEPOOL_BUCK_REMOTE:-false}" = true ]; then
  test -r /etc/swarm-build/platform || { echo "Missing remote platform identity" >&2; exit 1; }
  remote_toolchain="$(cat /etc/swarm-build/platform)"
  remote_enabled=true
fi

if ! mountpoint -q "$PWD/buck-out"; then
  printf 'Provision a real per-checkout buck-out bind mount before configuring Buck: %s/buck-out\n' "$PWD" >&2
  exit 1
fi

cat > .buckconfig.local <<EOF
# Generated by scripts/buck2-configure.sh from flake.lock.
[nix]
rustc = $rust/bin/rustc
rustdoc = $rust/bin/rustdoc
clippy = $rust/bin/clippy-driver
ghc = $ghc/bin/ghc
ghc_bin = $ghc/bin
ghc_pkg = $ghc/bin/ghc-pkg
haddock = $ghc/bin/haddock
ghc_libdir = $ghc_libdir
cc = $cc/bin/cc
cxx = $cc/bin/c++
ar = $binutils/bin/ar
node = $node/bin/node
npm_cache = $npm_cache
npm = $node/bin/npm
browser_node = $browser_node/bin/node
browser_npm = $browser_node/bin/npm
browser_npm_cache = $browser_npm_cache
playwright_browsers = $playwright_browsers
browser_test_closure = $browser_test_closure
git = $git_path/bin/git
bash = $bash_path/bin/bash
coreutils = $coreutils/bin
sleep = $coreutils/bin/sleep
tar = $tar_path/bin/tar
gzip = $gzip/bin/gzip
python = $python/bin/python3
cmake = $cmake/bin/cmake
perl = $perl/bin/perl
pkg_config = $pkg_config/bin/pkg-config
action_path = $rust/bin:$cc/bin:$binutils/bin:$cmake/bin:$perl/bin:$pkg_config/bin:$python/bin:$bash_path/bin:$coreutils/bin:$tar_path/bin:$gzip/bin:$node/bin:$git_path/bin

[remote]
enabled = $remote_enabled
toolchain = $remote_toolchain
EOF
if [ "$remote_enabled" = true ]; then
  cat >> .buckconfig.local <<'EOF'

[buck2_re_client]
action_cache_address = grpc://localhost:50051
engine_address = grpc://localhost:50051
cas_address = grpc://localhost:50051
tls = false
instance_name = swarm
EOF
fi
printf 'Wrote %s/.buckconfig.local\n' "$PWD"
