#!/usr/bin/env python3
"""Derive Reindeer's dependency-only manifest from the migrated Cargo packages."""
import argparse
import json
from pathlib import Path
import subprocess
import tomllib

ROOT = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser()
parser.add_argument("--output-dir", type=Path, required=True)
DEST = parser.parse_args().output_dir.resolve()
DEST.mkdir(parents=True, exist_ok=True)
# Expand only after native targets and feature/platform handling are accepted.
ROOTS = {"tidepool-atomic-write", "tidepool-repr", "tidepool-heap"}
metadata = json.loads(subprocess.check_output([
    "cargo", "metadata", "--locked", "--filter-platform", "x86_64-unknown-linux-gnu",
    "--format-version", "1",
], cwd=ROOT))
packages = {p["id"]: p for p in metadata["packages"]}
nodes = {p["id"]: p for p in metadata["resolve"]["nodes"]}
selected = [p for p in packages.values() if p["name"] in ROOTS and p["source"] is None]
if {p["name"] for p in selected} != ROOTS:
    raise SystemExit("Missing migrated Cargo package")
dependencies = {}
for package in selected:
    if package["features"] or any(d["optional"] for d in package["dependencies"]):
        raise SystemExit(f"Model Cargo feature selection before migrating {package['name']}")
    for edge in nodes[package["id"]]["deps"]:
        target = packages[edge["pkg"]]
        if target["source"] is None:
            if target["name"] not in ROOTS:
                raise SystemExit(f"Unmigrated local dependency: {target['name']}")
            continue
        if target["source"] != "registry+https://github.com/rust-lang/crates.io-index":
            raise SystemExit(f"Declare non-registry source explicitly: {target['source']}")
        key = (target["name"], target["version"])
        spec = dependencies.setdefault(key, {"features": set(), "default": False})
        for dependency in package["dependencies"]:
            name = (dependency["rename"] or dependency["name"]).replace("-", "_")
            if name != edge["name"]:
                continue
            if not any(k["kind"] == dependency["kind"] and k["target"] == dependency["target"] for k in edge["dep_kinds"]):
                continue
            spec["features"].update(dependency["features"])
            spec["default"] |= dependency["uses_default_features"]
lines = [
    '# @generated by scripts/buck2-dependencies.py; Cargo manifests and root lock own dependencies.',
    '[package]', 'name = "tidepool-buck-dependencies"', 'version = "0.0.0"',
    'edition = "2021"', 'publish = false', '[workspace]', '[lib]', 'path = "empty.rs"',
    '[dependencies]',
]
for (name, version), spec in sorted(dependencies.items()):
    alias = name if sum(n == name for n, _ in dependencies) == 1 else name + "-" + version.replace(".", "_")
    fields = [f'package = {json.dumps(name)}', f'version = {json.dumps("=" + version)}',
              'default-features = ' + str(spec["default"]).lower(),
              'features = ' + json.dumps(sorted(spec["features"]))]
    lines.append(json.dumps(alias) + ' = { ' + ', '.join(fields) + ' }')
(DEST / 'Cargo.toml').write_text('\n'.join(lines) + '\n')
(DEST / 'Cargo.lock').write_bytes((ROOT / 'Cargo.lock').read_bytes())
subprocess.run(['cargo', 'metadata', '--offline', '--manifest-path', str(DEST / 'Cargo.toml'),
                '--format-version', '1', '--filter-platform', 'x86_64-unknown-linux-gnu'],
               cwd=ROOT, stdout=subprocess.DEVNULL, check=True)
root_lock = tomllib.loads((ROOT / 'Cargo.lock').read_text())
generated_lock = tomllib.loads((DEST / 'Cargo.lock').read_text())
def identity(p):
    return p['name'], p['version'], p.get('source'), p.get('checksum')
accepted = {identity(p) for p in root_lock['package']}
for package in generated_lock['package']:
    if package['name'] == 'tidepool-buck-dependencies' and package.get('source') is None:
        continue
    if identity(package) not in accepted:
        raise SystemExit(f"Generated dependency escaped root Cargo.lock: {package['name']} {package['version']}")
