#!/usr/bin/env python3
"""Regenerate [workspace.dependencies] and per-crate dependency tables.

Surgical line rewrites only — never a full TOML round-trip, so comments and
key order in untouched lines are preserved exactly.

Policy:
  - Every internal `tidepool-*` path dependency is centralized unconditionally
    (uniform version/path pairing, zero ambiguity).
  - An external dependency is centralized only when at least two crates
    declare it with the IDENTICAL version requirement string and
    default-features left at its default (true). Among version-requirement
    groups of size >= 2, the largest group is centralized (ties broken by
    lexicographically smallest version string); every other group for that
    dependency name is left exactly as written. A dependency with no
    qualifying group (every user's version string is distinct, or the only
    repeated group has size 1) is left untouched everywhere.
  - The workspace entry's `features` list is the INTERSECTION of the
    `features` lists across the chosen group's members. Each member then
    keeps only its features beyond that intersection locally
    (`{ workspace = true, features = [...] }`), or plain `dep.workspace =
    true` when it needs nothing extra. This is exact: base ∪ (member ∖ base)
    == member, for every member of the group.

Usage:
  scripts/gen-workspace-deps.py           # rewrite files in place
  scripts/gen-workspace-deps.py --check   # exit 1 + diff if regeneration would change anything
"""
import difflib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SENTINEL_BEGIN = "# --- gen-workspace-deps: BEGIN (generated by scripts/gen-workspace-deps.py; do not hand-edit) ---"
SENTINEL_END = "# --- gen-workspace-deps: END ---"
INSERT_BEFORE = "# Optimize DEPENDENCIES (Cranelift, regalloc2, …) even in dev/test builds."

DEP_SECTION_RE = re.compile(r"^\[([^\]]+)\]$")
ARRAY_TABLE_RE = re.compile(r"^\[\[([^\]]+)\]\]$")
DEP_SECTION_NAMES = {"dependencies", "dev-dependencies", "build-dependencies"}


def is_dep_section(name):
    if name in DEP_SECTION_NAMES:
        return True
    m = re.match(r"^target\.(.+)\.(dependencies|dev-dependencies|build-dependencies)$", name)
    return bool(m)


SIMPLE_RE = re.compile(r'^([A-Za-z0-9_.\-]+)\s*=\s*"([^"]*)"\s*$')
DOTTED_WS_RE = re.compile(r"^([A-Za-z0-9_.\-]+)\.workspace\s*=\s*true\s*$")
INLINE_RE = re.compile(r"^([A-Za-z0-9_.\-]+)\s*=\s*\{(.*)\}\s*$")

KNOWN_KEYS = {"version", "path", "features", "default-features", "workspace"}


def split_top_level_commas(s):
    parts, cur, depth, in_str = [], "", 0, False
    for ch in s:
        if in_str:
            cur += ch
            if ch == '"':
                in_str = False
            continue
        if ch == '"':
            in_str = True
            cur += ch
            continue
        if ch in "[{":
            depth += 1
            cur += ch
            continue
        if ch in "]}":
            depth -= 1
            cur += ch
            continue
        if ch == "," and depth == 0:
            parts.append(cur)
            cur = ""
            continue
        cur += ch
    if cur.strip():
        parts.append(cur)
    return [p.strip() for p in parts]


def parse_inline_body(body):
    out = {}
    for part in split_top_level_commas(body):
        if "=" not in part:
            return None
        key, val = part.split("=", 1)
        key, val = key.strip(), val.strip()
        if key not in KNOWN_KEYS:
            return None
        if val.startswith('"') and val.endswith('"'):
            out[key] = val[1:-1]
        elif val in ("true", "false"):
            out[key] = val == "true"
        elif val.startswith("[") and val.endswith("]"):
            out[key] = re.findall(r'"([^"]*)"', val)
        else:
            return None
    return out


def parse_dep_line(line):
    """Returns (name, kind, fields) or None. kind in {'simple','inline','dotted'}."""
    m = DOTTED_WS_RE.match(line)
    if m:
        return m.group(1), "dotted", {"workspace": True}
    m = INLINE_RE.match(line)
    if m:
        name, body = m.group(1), m.group(2)
        fields = parse_inline_body(body)
        if fields is None:
            return None
        return name, "inline", fields
    m = SIMPLE_RE.match(line)
    if m:
        return m.group(1), "simple", {"version": m.group(2)}
    return None


def scan_dep_lines(lines):
    """Yield (line_index, name, kind, fields) for every recognized dependency
    line inside a [dependencies]-shaped section."""
    section = None
    for i, raw in enumerate(lines):
        line = raw.rstrip("\n")
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        m = ARRAY_TABLE_RE.match(stripped)
        if m:
            section = None
            continue
        m = DEP_SECTION_RE.match(stripped)
        if m:
            name = m.group(1)
            section = name if is_dep_section(name) else None
            continue
        if section is None:
            continue
        parsed = parse_dep_line(stripped)
        if parsed is None:
            print(f"warning: unrecognized dependency line, leaving untouched: {stripped!r}", file=sys.stderr)
            continue
        name, kind, fields = parsed
        yield i, section, name, kind, fields


def toml_str(s):
    return '"' + s + '"'


def toml_array(items):
    return "[" + ", ".join(toml_str(x) for x in items) + "]"


def render_inline(fields_in_order):
    body = ", ".join(f"{k} = {v}" for k, v in fields_in_order)
    return "{ " + body + " }"


def render_workspace_ref(name, extra_features):
    if not extra_features:
        return f"{name}.workspace = true"
    return f"{name} = " + render_inline([("workspace", "true"), ("features", toml_array(sorted(extra_features)))])


def render_local(name, version, path, default_features, features):
    order = []
    if version is not None:
        order.append(("version", toml_str(version)))
    if path is not None:
        order.append(("path", toml_str(path)))
    if default_features is False:
        order.append(("default-features", "false"))
    if features:
        order.append(("features", toml_array(sorted(features))))
    if not order or (len(order) == 1 and order[0][0] == "version" and path is None and not features and default_features is not False):
        return f'{name} = {toml_str(version)}'
    return f"{name} = " + render_inline(order)


def find_workspace_members(root_text):
    m = re.search(r"members\s*=\s*\[(.*?)\]", root_text, re.DOTALL)
    if not m:
        raise SystemExit("could not find [workspace] members array in root Cargo.toml")
    return re.findall(r'"([^"]+)"', m.group(1))


def crate_name_for(member_dir):
    text = (ROOT / member_dir / "Cargo.toml").read_text()
    m = re.search(r'^\s*name\s*=\s*"([^"]+)"\s*$', text, re.MULTILINE)
    if not m:
        raise SystemExit(f"could not find package name in {member_dir}/Cargo.toml")
    return m.group(1)


def parse_existing_workspace_deps(root_lines):
    """Parse the current sentinel-delimited [workspace.dependencies] block
    (if present) into {name: fields}. Used to reconstruct the effective
    declaration behind an already-`workspace = true` member line."""
    try:
        start = next(i for i, l in enumerate(root_lines) if l.rstrip("\n") == SENTINEL_BEGIN)
        end = next(i for i, l in enumerate(root_lines) if l.rstrip("\n") == SENTINEL_END)
    except StopIteration:
        return {}
    out = {}
    for i in range(start, end + 1):
        stripped = root_lines[i].rstrip("\n").strip()
        parsed = parse_dep_line(stripped)
        if parsed is None:
            continue
        name, kind, fields = parsed
        out[name] = fields
    return out


class Occurrence:
    def __init__(self, member, line_idx, section, name, is_internal, version, path, features, default_features):
        self.member = member
        self.line_idx = line_idx
        self.section = section
        self.name = name
        self.is_internal = is_internal
        self.version = version
        self.path = path
        self.features = set(features)
        self.default_features = default_features


def main():
    check_mode = "--check" in sys.argv[1:]

    root_toml_path = ROOT / "Cargo.toml"
    root_text = root_toml_path.read_text()
    root_lines = root_text.splitlines(keepends=True)

    members = find_workspace_members(root_text)
    member_crate_name = {m: crate_name_for(m) for m in members}
    crate_name_to_member = {v: k for k, v in member_crate_name.items()}

    prev_ws_deps = parse_existing_workspace_deps(root_lines)

    member_lines = {}
    occurrences_by_name = {}

    for member in members:
        mpath = ROOT / member / "Cargo.toml"
        lines = mpath.read_text().splitlines(keepends=True)
        member_lines[member] = lines
        for idx, section, name, kind, fields in scan_dep_lines(lines):
            is_internal = name.startswith("tidepool-") or name == "tidepool"
            if kind in ("dotted", "inline") and fields.get("workspace"):
                base = prev_ws_deps.get(name)
                if base is None:
                    raise SystemExit(
                        f"{member}/Cargo.toml:{idx+1}: `{name}` is already `workspace = true` "
                        f"but no [workspace.dependencies] entry exists for it — corrupt state, "
                        f"fix by hand or restore the workspace.dependencies block first."
                    )
                local_features = set(fields.get("features", []))
                eff_version = base.get("version")
                eff_path = base.get("path")
                eff_features = set(base.get("features", [])) | local_features
                eff_default_features = base.get("default-features", True)
            else:
                eff_version = fields.get("version")
                eff_path = fields.get("path")
                eff_features = set(fields.get("features", []))
                eff_default_features = fields.get("default-features", True)

            occ = Occurrence(
                member, idx, section, name, is_internal,
                eff_version, eff_path, eff_features, eff_default_features,
            )
            occurrences_by_name.setdefault(name, []).append(occ)

    # --- decide centralization ---
    ws_entries = {}  # name -> dict(version=?, path=?, features=set)
    chosen_group = {}  # name -> set(id(occ)) considered "in the centralized group"

    for name, occs in occurrences_by_name.items():
        is_internal = occs[0].is_internal
        if is_internal:
            versioned = {o.version for o in occs if o.version is not None}
            if len(versioned) > 1:
                raise SystemExit(f"internal dep `{name}` has inconsistent versions across crates: {versioned}")
            version = next(iter(versioned)) if versioned else None
            # Two shapes are NOT requirement-identical to the versioned
            # majority, and centralizing either would silently change what that
            # occurrence asks for:
            #   - no version at all (a bare `{ path = ... }`): centralizing
            #     widens it from unconstrained to `version`.
            #   - `default-features = false`: the workspace reference renders as
            #     `workspace = true` plus extra features (render_workspace_ref
            #     has no way to say "and keep default features off"), so
            #     centralizing re-enables default features.
            # Both are left fully local. The external branch below excludes the
            # second for the same reason.
            unpinned = [o for o in occs if o.version is None]
            no_defaults = [o for o in occs if o.default_features is False]
            if version is not None:
                group = [o for o in occs if o.version == version and o.default_features is not False]
            else:
                group = [o for o in occs if o.default_features is not False]
            # Only a skip when there IS a pinned majority to be excluded from:
            # if nothing pins this dep (a `publish = false` crate consumed by
            # path alone), every occurrence is unpinned and all of them are
            # centralized together — nothing was left behind to report.
            if unpinned and version is not None:
                print(
                    f"note: `{name}` is missing its version pin in {[o.member for o in unpinned]} "
                    f"(bare `{{ path = ... }}`, not `{{ version = \"{version}\", path = ... }}` like "
                    f"every other consumer) — left fully local, NOT centralized, since adding the "
                    f"version there would change that occurrence's requirement",
                    file=sys.stderr,
                )
            if no_defaults:
                print(
                    f"note: `{name}` is declared `default-features = false` in "
                    f"{[o.member for o in no_defaults]} — left fully local, NOT centralized, since "
                    f"a `workspace = true` reference cannot carry that flag and would re-enable "
                    f"default features",
                    file=sys.stderr,
                )
            if not group:
                continue
            member_dir = crate_name_to_member.get(name)
            if member_dir is None:
                raise SystemExit(f"internal dep `{name}` does not match any workspace member's package name")
            base_features = set.intersection(*(o.features for o in group))
            ws_entries[name] = {"version": version, "path": member_dir, "features": base_features}
            chosen_group[name] = set(id(o) for o in group)
            continue

        # external: group by (version, default_features==True), pick largest group size >= 2
        groups = {}
        for o in occs:
            if o.default_features is False:
                continue  # never centralize a default-features=false occurrence
            groups.setdefault(o.version, []).append(o)
        eligible = {v: g for v, g in groups.items() if len(g) >= 2}
        if not eligible:
            continue
        best_version = max(eligible, key=lambda v: (len(eligible[v]), "".join(reversed(v))))
        # deterministic tie-break: largest group size, then lexicographically smallest version
        best_size = max(len(g) for g in eligible.values())
        candidates = sorted(v for v, g in eligible.items() if len(g) == best_size)
        best_version = candidates[0]
        group = eligible[best_version]
        base_features = set.intersection(*(o.features for o in group))
        ws_entries[name] = {"version": best_version, "path": None, "features": base_features}
        chosen_group[name] = set(id(o) for o in group)

    # --- rewrite member files ---
    changed_members = {}
    for member in members:
        lines = list(member_lines[member])
        touched = False
        for occs in occurrences_by_name.values():
            for o in occs:
                if o.member != member:
                    continue
                entry = ws_entries.get(o.name)
                in_group = entry is not None and id(o) in chosen_group.get(o.name, set())
                current_line = lines[o.line_idx].rstrip("\n")
                if in_group:
                    extra = o.features - entry["features"]
                    new_line = render_workspace_ref(o.name, extra)
                else:
                    # leave fully-local declarations untouched byte-for-byte;
                    # only re-render if this line currently claims workspace=true
                    # but no longer qualifies (policy changed under it).
                    parsed = parse_dep_line(current_line.strip())
                    if parsed and parsed[1] in ("dotted", "inline") and parsed[2].get("workspace"):
                        new_line = render_local(o.name, o.version, o.path, o.default_features, o.features)
                    else:
                        new_line = current_line
                if new_line != current_line:
                    indent = lines[o.line_idx][: len(lines[o.line_idx]) - len(lines[o.line_idx].lstrip())]
                    lines[o.line_idx] = indent + new_line + "\n"
                    touched = True
        if touched:
            changed_members[member] = lines

    # --- add rust-version.workspace = true where missing ---
    RUST_VERSION_TARGETS = ["tidepool-lsp", "examples/guess", "examples/tide"]
    for member in RUST_VERSION_TARGETS:
        lines = changed_members.get(member, list(member_lines[member]))
        text = "".join(lines)
        if re.search(r"^rust-version\.workspace\s*=\s*true\s*$", text, re.MULTILINE):
            continue
        anchors = [
            re.compile(r"^authors\.workspace\s*=\s*true\s*$"),
            re.compile(r"^edition\.workspace\s*=\s*true\s*$"),
        ]
        new_lines = None
        for anchor in anchors:
            if not any(anchor.match(l.rstrip("\n")) for l in lines):
                continue
            candidate = []
            inserted = False
            for l in lines:
                candidate.append(l)
                if not inserted and anchor.match(l.rstrip("\n")):
                    candidate.append("rust-version.workspace = true\n")
                    inserted = True
            new_lines = candidate
            break
        if new_lines is None:
            raise SystemExit(f"{member}/Cargo.toml: could not find an anchor line for rust-version.workspace insertion")
        changed_members[member] = new_lines

    # --- render root [workspace.dependencies] block ---
    internal_names = sorted(n for n in ws_entries if occurrences_by_name[n][0].is_internal)
    external_names = sorted(n for n in ws_entries if not occurrences_by_name[n][0].is_internal)

    block_lines = [SENTINEL_BEGIN + "\n", "[workspace.dependencies]\n"]
    for n in internal_names:
        e = ws_entries[n]
        order = []
        if e["version"] is not None:
            order.append(("version", toml_str(e["version"])))
        order.append(("path", toml_str(e["path"])))
        if e["features"]:
            order.append(("features", toml_array(sorted(e["features"]))))
        block_lines.append(f"{n} = " + render_inline(order) + "\n")
    if internal_names and external_names:
        block_lines.append("\n")
    for n in external_names:
        e = ws_entries[n]
        if e["features"]:
            block_lines.append(f"{n} = " + render_inline([("version", toml_str(e["version"])), ("features", toml_array(sorted(e["features"])))]) + "\n")
        else:
            block_lines.append(f"{n} = {toml_str(e['version'])}\n")
    block_lines.append(SENTINEL_END + "\n")

    try:
        start = next(i for i, l in enumerate(root_lines) if l.rstrip("\n") == SENTINEL_BEGIN)
        end = next(i for i, l in enumerate(root_lines) if l.rstrip("\n") == SENTINEL_END)
        new_root_lines = root_lines[:start] + block_lines + root_lines[end + 1:]
    except StopIteration:
        anchor_idx = next((i for i, l in enumerate(root_lines) if l.rstrip("\n") == INSERT_BEFORE), None)
        if anchor_idx is None:
            raise SystemExit("could not find insertion anchor in root Cargo.toml")
        new_root_lines = root_lines[:anchor_idx] + block_lines + ["\n"] + root_lines[anchor_idx:]

    # --- apply or check ---
    all_targets = {"Cargo.toml": (root_toml_path, root_lines, new_root_lines)}
    for member, new_lines in changed_members.items():
        p = ROOT / member / "Cargo.toml"
        all_targets[f"{member}/Cargo.toml"] = (p, member_lines[member], new_lines)

    any_diff = False
    for label, (path, old_lines, new_lines) in sorted(all_targets.items()):
        old_text = "".join(old_lines)
        new_text = "".join(new_lines)
        if old_text == new_text:
            continue
        any_diff = True
        if check_mode:
            diff = difflib.unified_diff(
                old_text.splitlines(keepends=True),
                new_text.splitlines(keepends=True),
                fromfile=f"a/{label}", tofile=f"b/{label}",
            )
            sys.stdout.writelines(diff)
        else:
            path.write_text(new_text)

    n_internal = len(internal_names)
    n_external = len(external_names)
    n_decls = sum(len(chosen_group.get(n, ())) for n in ws_entries)

    if check_mode:
        if any_diff:
            print(f"\ngen-workspace-deps.py --check: manifests are STALE ({n_internal} internal + {n_external} external centralized deps, {n_decls} declarations)", file=sys.stderr)
            return 1
        print(f"gen-workspace-deps.py --check: up to date ({n_internal} internal + {n_external} external centralized deps, {n_decls} declarations)")
        return 0

    print(f"gen-workspace-deps.py: {n_internal} internal + {n_external} external deps centralized, {n_decls} declarations rewritten across {len(changed_members)} crate(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
