#!/usr/bin/env python3
"""Check or refresh source snapshots from an explicit native protocol generator."""

import argparse
from pathlib import Path
import subprocess
import tempfile


MARKER = b"GENERATED by tidepool-protocol, DO NOT EDIT."


def reconcile(root, generator, refresh=False):
    roster = subprocess.check_output([str(generator), "--list"], text=True).splitlines()
    declared = (root / "build/protocol/outputs.txt").read_text().splitlines()
    if roster != declared:
        raise ValueError("protocol output roster differs from build/protocol/outputs.txt")
    paths = [Path(name) for name in roster]
    if not paths or len(set(paths)) != len(paths):
        raise ValueError("protocol output roster must be nonempty and unique")
    if any(path.is_absolute() or ".." in path.parts for path in paths):
        raise ValueError("protocol outputs must be relative paths within the source root")
    wanted = set(paths)
    stale = []
    for directory in sorted({(root / path).parent for path in paths}):
        if not directory.exists():
            continue
        for source in directory.iterdir():
            if source.is_file() and source.relative_to(root) not in wanted:
                with source.open("rb") as stream:
                    if MARKER in stream.readline():
                        stale.append(source)
    with tempfile.TemporaryDirectory(prefix="tidepool-protocol-snapshots-") as temporary:
        output = Path(temporary)
        command = [str(generator), "--output-root", str(output)]
        for name in roster:
            command.extend(["--expect-output", name])
        subprocess.run(command, check=True)
        changed = []
        for path in paths:
            source, generated = root / path, output / path
            contents = generated.read_bytes()
            if not source.is_file() or source.read_bytes() != contents:
                changed.append(path)
        # Materialize and validate all producer outputs before modifying source.
        if refresh:
            for path in changed:
                source = root / path
                source.parent.mkdir(parents=True, exist_ok=True)
                source.write_bytes((output / path).read_bytes())
            for source in stale:
                source.unlink()
    return changed, sorted(source.relative_to(root) for source in stale)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generator", type=Path, required=True,
                        help="exact compiled tidepool-protocol-gen executable")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--refresh", action="store_true")
    options = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    changed, stale = reconcile(root, options.generator.resolve(), options.refresh)
    for path in changed:
        print(f"{'refreshed' if options.refresh else 'different'}: {path}")
    for path in stale:
        print(f"{'removed' if options.refresh else 'obsolete'}: {path}")
    return int(not options.refresh and bool(changed or stale))


if __name__ == "__main__":
    raise SystemExit(main())
