//! The pin for `gen::wire_rs`'s Event (`RepoEvent`) output — the same proof
//! `worktree_wire_rust.rs` gives Worktree, extended with the cross-effect
//! `foreign_types` reference (`Watch`/`HeadChangeKind`/`HeadChangeReceipt`/
//! `CommitReceipt` all name Worktree's OWN types) that Worktree's lane never
//! exercised.
//!
//! Two independent proofs, same shape as the Worktree pin:
//!
//! 1. [`event_wire_module_matches_pin`] — the WHOLE emitted module, byte-for-byte
//!    against a hardcoded string.
//! 2. [`event_wire_types_match_the_hand_written_block_field_for_field`] — per
//!    type, field/variant NAMES and ORDER (positional, never a set), Rust field
//!    types, the exact derive line, and `#[core(name = …)]` presence.
//!
//! Every expected value in test 2 is HAND-TRANSCRIBED from the `Ev*` block that
//! was live in `tidepool-bridge-effects/src/lib.rs` before this lane's flip
//! (`EvEventId` through `EvRepositoryEvent`) — not copied from this generator's
//! own output, for the same reason `worktree_wire_rust.rs`'s header gives.

use tidepool_protocol::effects;
use tidepool_protocol::gen::wire_rs;

const EXPECTED_MODULE: &str = r#"//! `RepoEvent` wire types — GENERATED by tidepool-protocol. DO NOT EDIT BY HAND.
//!
//! The schema in `tidepool-protocol/src/effects/` is the single source of
//! truth for this effect's contract. Regenerate with:
//!
//!     cargo run -p tidepool-protocol --bin tidepool-protocol-gen
//!
//! and verify with `cargo nextest run -p tidepool-protocol` (the
//! `generated_files_are_current` test), or rewrite in place with
//! `TIDEPOOL_REGEN_PROTOCOL=1`.

use crate::{WtBranchName, WtGitOid, WtWorktreeId};
use tidepool_bridge_derive::{FromCore, ToCore};

/// Haskell `EventId` — opaque RUNTIME identity, minted once per
/// reconciliation pass. A normal commit's `commit` and `headChanged`
/// observations share one, which is how a consumer tells two views of one
/// change from two changes.
#[derive(ToCore, FromCore, Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[core(name = "EventId")]
pub struct EvEventId {
    pub raw: i64,
}

/// Haskell `SubscriptionId` — one live `withHandler` registration.
#[derive(ToCore, FromCore, Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[core(name = "SubscriptionId")]
pub struct EvSubscriptionId {
    pub raw: i64,
}

/// Haskell `Watch` — one (worktree, kind) pair a subscription observes, or a
/// one-shot deadline. `<|>` concatenates watches, so a merged `Event` is ONE
/// subscription over several watches rather than several subscriptions.
/// `WatchDeadline` carries a RELATIVE millisecond duration: the runtime fixes
/// the absolute deadline at `subscribe()` time, `now + ms`. `WatchAsync`/
/// `WatchMailbox` name no worktree either — a raw `Int` rather than a
/// newtype, since this row must stand alone without `Green`.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
pub enum EvWatch {
    WatchCommit(WtWorktreeId),
    WatchHead(WtWorktreeId),
    WatchDeadline(i64),
    WatchAsync(i64),
    WatchMailbox(i64),
}

/// Haskell `HeadChangeKind`. `UnknownChange` is a correct answer, not a
/// failure: inventing `Advanced` for what was actually a reset would send a
/// child rebasing onto a commit that no longer means what the claim said.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
pub enum EvHeadChangeKind {
    Advanced(Vec<WtGitOid>),
    Amended(WtGitOid, WtGitOid),
    Rewritten(Vec<(WtGitOid, WtGitOid)>),
    Rewound,
    Switched,
    UnknownChange,
}

/// Haskell `HeadChangeReceipt`.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "HeadChangeReceipt")]
pub struct EvHeadChangeReceipt {
    pub head_worktree: WtWorktreeId,
    /// `None` on the first observation of a worktree that had no recorded head.
    pub old_head: Option<WtGitOid>,
    pub new_head: WtGitOid,
    pub kind: EvHeadChangeKind,
    /// `None` on a detached HEAD.
    pub head_branch: Option<WtBranchName>,
    pub observed_at_ms: i64,
}

/// Haskell `CommitReceipt`.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "CommitReceipt")]
pub struct EvCommitReceipt {
    pub commit_worktree: WtWorktreeId,
    pub oid: WtGitOid,
    pub parents: Vec<WtGitOid>,
    pub subject: String,
    pub author: String,
    pub committed_at_ms: i64,
    pub files: Vec<String>,
}

/// Haskell `Tick` — the payload a fired deadline watch delivers. Carries the
/// wall-clock moment the runtime observed it as due; the deadline the caller
/// asked for lives only in the `WatchDeadline` that fired.
#[derive(ToCore, FromCore, Clone, Copy, Debug, PartialEq, Eq)]
#[core(name = "Tick")]
pub struct EvTickReceipt {
    pub fired_at_ms: i64,
}

/// Haskell `RepositoryEvent` — one reconciled fact as it crosses the boundary.
/// The `EventId` rides on the wire rather than being minted per view, because
/// the SHARING is the information. `ObservedTick` is never broadcast — a fired
/// deadline is queued directly onto the ONE subscription that armed it.
/// `ObservedAsyncDone` carries only the settled thread's `Int` id, never its
/// result. `ObservedMessage` carries a mailbox `Int` and a bare JSON payload;
/// the coalesce key does not ride the wire.
/// Ret-only (never decoded from Haskell) — it appears exclusively as
/// `ret "[RepositoryEvent]"`, never in an `args { .. }` clause, so `FromCore`
/// here would be an unreachable impl, not a capability.
#[derive(ToCore, Clone, Debug, PartialEq)]
pub enum EvRepositoryEvent {
    ObservedCommit(EvEventId, EvCommitReceipt),
    ObservedHeadChange(EvEventId, EvHeadChangeReceipt),
    ObservedTick(EvEventId, EvTickReceipt),
    ObservedAsyncDone(EvEventId, i64),
    ObservedMessage(EvEventId, i64, serde_json::Value),
}

impl EvEventId {
    /// An untrusted raw value becomes a wire id here — infallibly: an
    /// integer identity carries no policy.
    #[must_use]
    pub fn new(raw: i64) -> Self {
        Self { raw }
    }

    /// The payload.
    #[must_use]
    pub fn as_i64(&self) -> i64 {
        self.raw
    }
}

impl EvSubscriptionId {
    /// An untrusted raw value becomes a wire id here — infallibly: an
    /// integer identity carries no policy.
    #[must_use]
    pub fn new(raw: i64) -> Self {
        Self { raw }
    }

    /// The payload.
    #[must_use]
    pub fn as_i64(&self) -> i64 {
        self.raw
    }
}
"#;

#[test]
fn event_wire_module_matches_pin() {
    let event = effects::event::event();
    let generated = wire_rs::file(&event);
    assert_eq!(generated.contents, EXPECTED_MODULE);
}

// ---------------------------------------------------------------------------
// The independent, hand-transcribed structural cross-check.
// ---------------------------------------------------------------------------

const WIRE: &str = "#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]";
const WIRE_COPY: &str = "#[derive(ToCore, FromCore, Clone, Copy, Debug, PartialEq, Eq)]";
const WIRE_ID_ORD: &str =
    "#[derive(ToCore, FromCore, Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]";
const WIRE_ID_ORD_HASH: &str =
    "#[derive(ToCore, FromCore, Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]";
const WIRE_RET_ONLY: &str = "#[derive(ToCore, Clone, Debug, PartialEq)]";

/// `(rust_field_name, rust_field_type)` pairs inside `pub struct NAME { … }`.
fn struct_fields<'a>(module: &'a str, name: &str) -> Vec<(&'a str, &'a str)> {
    let marker = format!("pub struct {name} {{");
    let start = module
        .find(&marker)
        .unwrap_or_else(|| panic!("no `pub struct {name}` in the generated module"));
    let body = &module[start + marker.len()..];
    let end = body.find("\n}\n").expect("unterminated struct");
    body[..end]
        .lines()
        .filter(|l| l.trim_start().starts_with("pub "))
        .map(|l| {
            let l = l.trim();
            let l = l.strip_prefix("pub ").expect("filtered for `pub ` prefix");
            let l = l.trim_end_matches(',');
            let (field, ty) = l.split_once(':').expect("field line must be `name: Type`");
            (field.trim(), ty.trim())
        })
        .collect()
}

/// Variant texts inside `pub enum NAME { … }`, in source order.
fn enum_variants<'a>(module: &'a str, name: &str) -> Vec<&'a str> {
    let marker = format!("pub enum {name} {{");
    let start = module
        .find(&marker)
        .unwrap_or_else(|| panic!("no `pub enum {name}` in the generated module"));
    let body = &module[start + marker.len()..];
    let end = body.find("\n}\n").expect("unterminated enum");
    body[..end]
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with("///"))
        .map(|l| l.trim_end_matches(','))
        .collect()
}

fn type_prelude<'a>(module: &'a str, marker: &str) -> &'a str {
    let start = module
        .find(marker)
        .unwrap_or_else(|| panic!("no `{marker}` in the generated module"));
    let prelude_start = module[..start].rfind("\n\n").map_or(0, |i| i + 2);
    &module[prelude_start..start]
}

#[allow(clippy::too_many_arguments)]
fn assert_struct(
    module: &str,
    wire_name: &str,
    hs_name: &str,
    derive_line: &str,
    needs_core_name: bool,
    fields: &[(&str, &str)],
) {
    let marker = format!("pub struct {wire_name} {{");
    let prelude = type_prelude(module, &marker);
    assert!(
        prelude.contains(derive_line),
        "{wire_name}: expected derive line `{derive_line}` in:\n{prelude}"
    );
    let core_attr = format!("#[core(name = \"{hs_name}\")]");
    assert_eq!(
        prelude.contains(&core_attr),
        needs_core_name,
        "{wire_name}: #[core(name = \"{hs_name}\")] presence mismatch in:\n{prelude}"
    );
    assert_eq!(
        struct_fields(module, wire_name),
        fields,
        "{wire_name}: field name/type/order mismatch"
    );
}

fn assert_enum(module: &str, wire_name: &str, derive_line: &str, variants: &[&str]) {
    let marker = format!("pub enum {wire_name} {{");
    let prelude = type_prelude(module, &marker);
    assert!(
        prelude.contains(derive_line),
        "{wire_name}: expected derive line `{derive_line}` in:\n{prelude}"
    );
    assert!(
        !prelude.contains("#[core(name"),
        "{wire_name}: an enum must never carry #[core(name = …)] — its data \
         constructors ARE its variant names"
    );
    assert_eq!(
        enum_variants(module, wire_name),
        variants,
        "{wire_name}: variant name/order mismatch"
    );
}

/// Every field/variant, in order, transcribed by hand from the `Ev*` block
/// that was live in `tidepool-bridge-effects/src/lib.rs` before this lane's
/// flip. See this file's header doc for why that transcription — not the
/// generator's own output — is what this test proves against.
#[test]
fn event_wire_types_match_the_hand_written_block_field_for_field() {
    let event = effects::event::event();
    let module = wire_rs::file(&event).contents;

    assert_struct(
        &module,
        "EvEventId",
        "EventId",
        WIRE_ID_ORD,
        true,
        &[("raw", "i64")],
    );
    assert_struct(
        &module,
        "EvSubscriptionId",
        "SubscriptionId",
        WIRE_ID_ORD_HASH,
        true,
        &[("raw", "i64")],
    );

    assert_enum(
        &module,
        "EvWatch",
        WIRE,
        &[
            "WatchCommit(WtWorktreeId)",
            "WatchHead(WtWorktreeId)",
            "WatchDeadline(i64)",
            "WatchAsync(i64)",
            "WatchMailbox(i64)",
        ],
    );

    assert_enum(
        &module,
        "EvHeadChangeKind",
        WIRE,
        &[
            "Advanced(Vec<WtGitOid>)",
            "Amended(WtGitOid, WtGitOid)",
            "Rewritten(Vec<(WtGitOid, WtGitOid)>)",
            "Rewound",
            "Switched",
            "UnknownChange",
        ],
    );

    assert_struct(
        &module,
        "EvHeadChangeReceipt",
        "HeadChangeReceipt",
        WIRE,
        true,
        &[
            ("head_worktree", "WtWorktreeId"),
            ("old_head", "Option<WtGitOid>"),
            ("new_head", "WtGitOid"),
            ("kind", "EvHeadChangeKind"),
            ("head_branch", "Option<WtBranchName>"),
            ("observed_at_ms", "i64"),
        ],
    );

    assert_struct(
        &module,
        "EvCommitReceipt",
        "CommitReceipt",
        WIRE,
        true,
        &[
            ("commit_worktree", "WtWorktreeId"),
            ("oid", "WtGitOid"),
            ("parents", "Vec<WtGitOid>"),
            ("subject", "String"),
            ("author", "String"),
            ("committed_at_ms", "i64"),
            ("files", "Vec<String>"),
        ],
    );

    assert_struct(
        &module,
        "EvTickReceipt",
        "Tick",
        WIRE_COPY,
        true,
        &[("fired_at_ms", "i64")],
    );

    assert_enum(
        &module,
        "EvRepositoryEvent",
        WIRE_RET_ONLY,
        &[
            "ObservedCommit(EvEventId, EvCommitReceipt)",
            "ObservedHeadChange(EvEventId, EvHeadChangeReceipt)",
            "ObservedTick(EvEventId, EvTickReceipt)",
            "ObservedAsyncDone(EvEventId, i64)",
            "ObservedMessage(EvEventId, i64, serde_json::Value)",
        ],
    );
}

#[test]
fn event_has_wire_types_but_no_adapters() {
    let event = effects::event::event();
    assert!(wire_rs::has_wire_types(&event));
    assert!(!tidepool_protocol::gen::adapter_rs::has_adapters(&event));
}
