//! Pin tests for `gen::adapter_rs`'s Worktree output.
//!
//! Worktree is deliberately absent from [`tidepool_protocol::effects::all`], so
//! `generated_files_are_current` never sees this module — nothing is written to
//! disk on this branch. These tests exercise `gen::adapter_rs::file` directly
//! against `effects::all_described()`, which is the test-only view that
//! includes Worktree. See the scaffold doc §11.5/§11.8.

use tidepool_protocol::gen::{adapter_rs, handler_rs};

fn worktree_adapter_text() -> String {
    let worktree = tidepool_protocol::effects::worktree::worktree();
    adapter_rs::file(&worktree).contents
}

/// Whole-module byte pin — the first and strictest layer. A blind regen that
/// silently changes a byte here fails this before anything else notices.
#[test]
fn worktree_adapter_module_text_is_pinned() {
    let expected = concat!(
        "//! `Worktree` domain↔wire adapters — GENERATED by tidepool-protocol. DO NOT EDIT BY HAND.\n",
        "//!\n",
        "//! The schema in `tidepool-protocol/src/effects/` is the single source of\n",
        "//! truth for this effect's contract. Regenerate with:\n",
        "//!\n",
        "//!     cargo run -p tidepool-protocol --bin tidepool-protocol-gen\n",
        "//!\n",
        "//! and verify with `cargo nextest run -p tidepool-protocol` (the\n",
        "//! `generated_files_are_current` test), or rewrite in place with\n",
        "//! `TIDEPOOL_REGEN_PROTOCOL=1`.\n",
        "\n",
        "use tidepool_bridge_effects::{\n",
        "    WtBranchName, WtDirtyPolicy, WtGitOid, WtGitRef, WtInProgressKind, WtWorktreeId,\n",
        "};\n",
        "use tidepool_worktree::{BranchName, DirtyPolicy, GitOid, GitRef, InProgressKind, WorktreeId};\n",
        "\n",
        "pub(crate) fn worktree_id_to_wire(worktree_id: &WorktreeId) -> WtWorktreeId {\n",
        "    WtWorktreeId {\n",
        "        raw: worktree_id.as_str().to_string(),\n",
        "    }\n",
        "}\n",
        "\n",
        "// WorktreeId::from_wire — HAND-WRITTEN, not generated: the rejection must become a DOMAIN error (`WorktreeNotRegistered`); only the path-safety check is generated, as this type's boundary constructor\n",
        "\n",
        "pub(crate) fn git_oid_to_wire(git_oid: &GitOid) -> WtGitOid {\n",
        "    WtGitOid {\n",
        "        raw: git_oid.as_str().to_string(),\n",
        "    }\n",
        "}\n",
        "\n",
        "pub(crate) fn git_ref_to_wire(git_ref: &GitRef) -> WtGitRef {\n",
        "    WtGitRef {\n",
        "        raw: git_ref.as_str().to_string(),\n",
        "    }\n",
        "}\n",
        "\n",
        "pub(crate) fn git_ref_from_wire(git_ref: &WtGitRef) -> GitRef {\n",
        "    GitRef::from_raw(git_ref.raw.clone())\n",
        "}\n",
        "\n",
        "pub(crate) fn branch_name_to_wire(branch_name: &BranchName) -> WtBranchName {\n",
        "    WtBranchName {\n",
        "        raw: branch_name.as_str().to_string(),\n",
        "    }\n",
        "}\n",
        "\n",
        "// WorktreeSource::from_wire — HAND-WRITTEN, not generated: composes a FALLIBLE conversion (`worktree_id_from_wire`); the error path is semantic\n",
        "\n",
        "pub(crate) fn dirty_policy_from_wire(dirty_policy: WtDirtyPolicy) -> DirtyPolicy {\n",
        "    match dirty_policy {\n",
        "        WtDirtyPolicy::RequireClean => DirtyPolicy::RequireClean,\n",
        "        WtDirtyPolicy::AllowDirtySnapshot => DirtyPolicy::AllowDirtySnapshot,\n",
        "    }\n",
        "}\n",
        "\n",
        "// WorktreeSpec::from_wire — HAND-WRITTEN, not generated: composes a FALLIBLE conversion; the error path is semantic\n",
        "\n",
        "pub(crate) fn in_progress_kind_to_wire(in_progress_kind: InProgressKind) -> WtInProgressKind {\n",
        "    match in_progress_kind {\n",
        "        InProgressKind::Merge => WtInProgressKind::InProgressMerge,\n",
        "        InProgressKind::Rebase => WtInProgressKind::InProgressRebase,\n",
        "        InProgressKind::CherryPick => WtInProgressKind::InProgressCherryPick,\n",
        "        InProgressKind::Revert => WtInProgressKind::InProgressRevert,\n",
        "        InProgressKind::Bisect => WtInProgressKind::InProgressBisect,\n",
        "    }\n",
        "}\n",
        "\n",
        "// DirtySummary::into_wire — HAND-WRITTEN, not generated: `usize` → `i64` widening on `ignoredExcluded`, and the three lists are cloned out of a borrow\n",
        "\n",
        "// GitFailureReceipt::into_wire — HAND-WRITTEN, not generated: `PathBuf` → lossy `String`, `Option<i32>` → `Option<i64>`\n",
        "\n",
        "// WorktreeReceipt::into_wire — HAND-WRITTEN, not generated: field renames (`worktree_id`→`tree_id`, `created_at_ms`→`created_at`) plus a `PathBuf` → lossy `String`\n",
        "\n",
        "// WorktreeHandle::into_wire — HAND-WRITTEN, not generated: delegates to the hand-written receipt conversion through `h.receipt()`\n",
        "\n",
        "// WorktreeSummary::into_wire — HAND-WRITTEN, not generated: delegates to the hand-written receipt conversion\n",
    );
    assert_eq!(worktree_adapter_text(), expected);
}

/// Independent of the whole-text pin above: every `pub(crate) fn` in the
/// module, in the ORDER it appears. Four `IdentityRaw` into_wire, one
/// `IdentityRaw` from_wire (`GitRef`), one `VariantMap` from_wire
/// (`DirtyPolicy`), one `VariantMap` into_wire (`InProgressKind`) — seven
/// total, matching the DONE CRITERIA count exactly.
#[test]
fn worktree_adapter_functions_appear_in_order() {
    let text = worktree_adapter_text();
    let names: Vec<&str> = text
        .lines()
        .filter_map(|l| l.strip_prefix("pub(crate) fn "))
        .map(|rest| rest.split(['(', ' ']).next().unwrap())
        .collect();
    assert_eq!(
        names,
        vec![
            "worktree_id_to_wire",
            "git_oid_to_wire",
            "git_ref_to_wire",
            "git_ref_from_wire",
            "branch_name_to_wire",
            "dirty_policy_from_wire",
            "in_progress_kind_to_wire",
        ]
    );
}

/// The `InProgressKind` variant map, positionally — a permutation of the same
/// five pairs would pass a set comparison but silently swap which domain
/// variant reports as which wire variant. Cross-checked BY HAND against
/// `in_progress_kind_to_wire` in `tidepool-handlers/src/handlers/worktree.rs`
/// (lines 121-129 as of the commit this test was written against): `Merge` ->
/// `InProgressMerge`, `Rebase` -> `InProgressRebase`, `CherryPick` ->
/// `InProgressCherryPick`, `Revert` -> `InProgressRevert`, `Bisect` ->
/// `InProgressBisect`, in exactly that order.
#[test]
fn in_progress_kind_variant_map_is_positional() {
    let text = worktree_adapter_text();
    let expected_pairs: Vec<(&str, &str)> = vec![
        ("Merge", "InProgressMerge"),
        ("Rebase", "InProgressRebase"),
        ("CherryPick", "InProgressCherryPick"),
        ("Revert", "InProgressRevert"),
        ("Bisect", "InProgressBisect"),
    ];
    let mut cursor = 0;
    for (domain_variant, wire_variant) in expected_pairs {
        let needle =
            format!("InProgressKind::{domain_variant} => WtInProgressKind::{wire_variant},");
        let found = text[cursor..]
            .find(&needle)
            .unwrap_or_else(|| panic!("arm `{needle}` missing, or out of position"));
        cursor += found + needle.len();
    }
}

/// Every `HandWritten` conversion generates NO function — only the comment
/// recording why. Checked both ways: no function DEFINITION exists for it
/// (some reasons legitimately mention a name like `worktree_id_from_wire` in
/// backtick-quoted prose, so the check anchors on `fn <name>(`, not a bare
/// substring), and (where the schema records one) the reason text is present
/// verbatim.
#[test]
fn hand_written_conversions_are_commented_not_generated() {
    let text = worktree_adapter_text();

    for missing_fn in [
        "receipt_to_wire",
        "spec_from_wire",
        "worktree_source_from_wire",
        "git_failure_receipt_to_wire",
        "dirty_summary_to_wire",
        "worktree_id_from_wire",
        "error_to_wire",
    ] {
        assert!(
            !text.contains(&format!("fn {missing_fn}(")),
            "`{missing_fn}` must not be generated — its conversion is HandWritten"
        );
    }

    for reason in [
        "the rejection must become a DOMAIN error (`WorktreeNotRegistered`); only the path-safety check is generated, as this type's boundary constructor",
        "composes a FALLIBLE conversion (`worktree_id_from_wire`); the error path is semantic",
        "composes a FALLIBLE conversion; the error path is semantic",
        "`usize` → `i64` widening on `ignoredExcluded`, and the three lists are cloned out of a borrow",
        "`PathBuf` → lossy `String`, `Option<i32>` → `Option<i64>`",
        "field renames (`worktree_id`→`tree_id`, `created_at_ms`→`created_at`) plus a `PathBuf` → lossy `String`",
    ] {
        assert!(
            text.contains(reason),
            "recorded HandWritten reason missing from the generated module: {reason}"
        );
    }
}

/// Exec and Journal both have empty `type_defs` (no `DomainMap` anywhere), so
/// neither gets an adapter module — same rule `wire_rs::has_wire_types`
/// follows for the wire module.
#[test]
fn exec_and_journal_have_no_adapters() {
    assert!(!adapter_rs::has_adapters(
        &tidepool_protocol::effects::exec::exec()
    ));
    assert!(!adapter_rs::has_adapters(
        &tidepool_protocol::effects::journal::journal()
    ));
}

/// `handler_rs::module_index` lists the adapter module alongside the effect's
/// own generated module for every DESCRIBED effect — including Worktree,
/// which `effects::all()` deliberately omits. This is the index a later flip
/// lane writes into; it must already know Worktree's adapter module exists.
#[test]
fn worktree_adapters_module_is_indexed() {
    let effects = tidepool_protocol::effects::all_described();
    let index = handler_rs::module_index(&effects).contents;
    assert!(
        index.contains("pub mod worktree;"),
        "index is missing the worktree module:\n{index}"
    );
    assert!(
        index.contains("pub mod worktree_adapters;"),
        "index is missing the worktree_adapters module:\n{index}"
    );
}
