//! The pin for `gen::wire_rs`'s Worktree output — the wire-record analogue of
//! `generated_files_are_current.rs`'s third layer, and the scaffold doc
//! §11.7's Class E ("wire-struct identity").
//!
//! Worktree is deliberately not in [`tidepool_protocol::effects::all`], so
//! nothing here is written to disk — this test calls the generator directly
//! against [`tidepool_protocol::effects::worktree::worktree`].
//!
//! Two independent proofs:
//!
//! 1. [`worktree_wire_module_matches_pin`] — the WHOLE emitted module,
//!    asserted byte-for-byte against a hardcoded string in this file.
//! 2. [`worktree_wire_types_match_the_hand_written_block_field_for_field`] —
//!    per type, the field/variant NAMES and ORDER (asserted POSITIONALLY, as
//!    a `Vec`, never as a set — a permutation is exactly the failure the
//!    hand-written struct's positional comment stood guard against and a set
//!    comparison would pass straight through), the Rust field types, the
//!    exact derive line, and the presence/absence of `#[core(name = …)]`.
//!
//! Every expected value in test 2 is HAND-TRANSCRIBED by reading the
//! still-live struct block in `tidepool-bridge-effects/src/lib.rs` (roughly
//! lines 105-232, `WtWorktreeId` through `WtWorktreeSummary`) — not copied out
//! of this generator's own output. That transcription is the only thing
//! making the test a proof rather than a tautology: a generator bug that
//! renders the wrong field order, the wrong Rust type, or the wrong derive set
//! would still produce SOME output, and only an independently-authored
//! expectation catches it being the wrong one.

use tidepool_protocol::effects;
use tidepool_protocol::gen::wire_rs;

const EXPECTED_MODULE: &str = r#"//! `Worktree` wire types — GENERATED by tidepool-protocol. DO NOT EDIT BY HAND.
//!
//! The schema in `tidepool-protocol/src/effects/` is the single source of
//! truth for this effect's contract. Regenerate with:
//!
//!     cargo run -p tidepool-protocol --bin tidepool-protocol-gen
//!
//! and verify with `cargo nextest run -p tidepool-protocol` (the
//! `generated_files_are_current` test), or rewrite in place with
//! `TIDEPOOL_REGEN_PROTOCOL=1`.

use tidepool_bridge_derive::{FromCore, ToCore};

/// Why a wire identity's boundary constructor refused a raw value.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum WireError {
    /// The raw value was empty.
    Empty {
        /// Which wire type refused it.
        wire_type: &'static str,
    },
    /// The raw value was not a safe single path segment: empty, too long,
    /// or carrying a byte outside ascii-alphanumeric plus the type's
    /// allowed extras.
    InvalidSegment {
        /// Which wire type refused it.
        wire_type: &'static str,
    },
}

/// Haskell `WorktreeId` — opaque durable identity. `data`, not a synonym: PRD
/// 19 requires that a `GitOid` can never be passed where a worktree id is
/// wanted.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "WorktreeId")]
pub struct WtWorktreeId {
    pub raw: String,
}

/// Haskell `GitOid` — domain data, distinct from `EvEventId`'s runtime identity.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "GitOid")]
pub struct WtGitOid {
    pub raw: String,
}

/// Haskell `GitRef` — a branch, tag, remote ref, or raw OID, resolved by git.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "GitRef")]
pub struct WtGitRef {
    pub raw: String,
}

/// Haskell `BranchName` — stored without the `refs/heads/` prefix.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "BranchName")]
pub struct WtBranchName {
    pub raw: String,
}

/// Haskell `WorktreeSource`.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
pub enum WtWorktreeSource {
    SourceCurrentRepository,
    SourceRef(WtGitRef),
    SourceWorktree(WtWorktreeId),
}

/// Haskell `DirtyPolicy`. Clean-by-default is the safety property; the opt-in
/// is spelled at the authored call site.
#[derive(ToCore, FromCore, Clone, Copy, Debug, PartialEq, Eq)]
pub enum WtDirtyPolicy {
    RequireClean,
    AllowDirtySnapshot,
}

/// Haskell `WorktreeSpec` — built in Haskell, consumed in Rust.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "WorktreeSpec")]
pub struct WtWorktreeSpec {
    pub spec_source: WtWorktreeSource,
    pub spec_label: String,
    pub spec_dirty_policy: WtDirtyPolicy,
}

/// Haskell `InProgressKind` — distinguished rather than collapsed to a string
/// so a resident can branch on it.
#[derive(ToCore, FromCore, Clone, Copy, Debug, PartialEq, Eq)]
pub enum WtInProgressKind {
    InProgressMerge,
    InProgressRebase,
    InProgressCherryPick,
    InProgressRevert,
    InProgressBisect,
}

/// Haskell `DirtySummary`. `ignored_excluded` is a COUNT, not a list: ignored
/// files are deliberately excluded from a snapshot, and listing them invites an
/// author to believe they were captured.
#[derive(ToCore, FromCore, Clone, Debug, Default, PartialEq, Eq)]
#[core(name = "DirtySummary")]
pub struct WtDirtySummary {
    pub staged: Vec<String>,
    pub unstaged: Vec<String>,
    pub untracked: Vec<String>,
    pub ignored_excluded: i64,
}

/// Haskell `GitFailureReceipt` — a failed git invocation, recorded verbatim so
/// the failure is diagnosable without re-running anything. Keeps stdout AND
/// stderr, never just the status.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "GitFailureReceipt")]
pub struct WtGitFailureReceipt {
    pub git_args: Vec<String>,
    pub git_cwd: String,
    /// `None` when the process was killed by a signal before exiting.
    pub git_exit_code: Option<i64>,
    pub git_stdout: String,
    pub git_stderr: String,
}

/// Haskell `WorktreeReceipt`. The id field is `tree_id`/`treeId` rather than
/// the PRD snippet's `worktreeId` — a record field selector and the top-level
/// `worktreeId` function the PRD pins by signature would be an ambiguous
/// occurrence at the export, so the field yielded.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "WorktreeReceipt")]
pub struct WtWorktreeReceipt {
    pub tree_id: WtWorktreeId,
    pub cwd: String,
    pub branch: WtBranchName,
    pub source_head: WtGitOid,
    pub snapshot_ref: Option<WtGitRef>,
    pub created_at: i64,
}

/// Haskell `WorktreeHandle` — a name plus its recorded facts, not an open
/// handle to anything.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "WorktreeHandle")]
pub struct WtWorktreeHandle {
    pub handle_receipt: WtWorktreeReceipt,
}

/// Haskell `WorktreeSummary`. `present` is a filesystem fact re-derived on each
/// listing rather than a recorded one, so a lost tree is listed rather than
/// failing the listing.
#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]
#[core(name = "WorktreeSummary")]
pub struct WtWorktreeSummary {
    pub summary_receipt: WtWorktreeReceipt,
    pub present: bool,
}

impl WtWorktreeId {
    /// The trust boundary: an untrusted raw value becomes a wire id here or
    /// not at all.
    pub fn new(raw: impl Into<String>) -> Result<Self, WireError> {
        let raw = raw.into();
        if raw.is_empty()
            || raw.len() > 128
            || !raw
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
        {
            return Err(WireError::InvalidSegment {
                wire_type: "WtWorktreeId",
            });
        }
        Ok(Self { raw })
    }

    pub fn as_str(&self) -> &str {
        &self.raw
    }
}

impl WtGitOid {
    /// The trust boundary: an untrusted raw value becomes a wire id here or
    /// not at all.
    pub fn new(raw: impl Into<String>) -> Result<Self, WireError> {
        let raw = raw.into();
        if raw.is_empty() {
            return Err(WireError::Empty {
                wire_type: "WtGitOid",
            });
        }
        Ok(Self { raw })
    }

    pub fn as_str(&self) -> &str {
        &self.raw
    }
}

impl WtGitRef {
    /// The trust boundary: an untrusted raw value becomes a wire id here or
    /// not at all.
    pub fn new(raw: impl Into<String>) -> Result<Self, WireError> {
        let raw = raw.into();
        if raw.is_empty() {
            return Err(WireError::Empty {
                wire_type: "WtGitRef",
            });
        }
        Ok(Self { raw })
    }

    pub fn as_str(&self) -> &str {
        &self.raw
    }
}

impl WtBranchName {
    /// The trust boundary: an untrusted raw value becomes a wire id here or
    /// not at all.
    pub fn new(raw: impl Into<String>) -> Result<Self, WireError> {
        let raw = raw.into();
        if raw.is_empty() {
            return Err(WireError::Empty {
                wire_type: "WtBranchName",
            });
        }
        Ok(Self { raw })
    }

    pub fn as_str(&self) -> &str {
        &self.raw
    }
}
"#;

#[test]
fn worktree_wire_module_matches_pin() {
    let worktree = effects::worktree::worktree();
    let generated = wire_rs::file(&worktree);
    assert_eq!(generated.contents, EXPECTED_MODULE);
}

// ---------------------------------------------------------------------------
// The independent, hand-transcribed structural cross-check.
// ---------------------------------------------------------------------------

const WIRE: &str = "#[derive(ToCore, FromCore, Clone, Debug, PartialEq, Eq)]";
const WIRE_COPY: &str = "#[derive(ToCore, FromCore, Clone, Copy, Debug, PartialEq, Eq)]";
const WIRE_DEFAULT: &str = "#[derive(ToCore, FromCore, Clone, Debug, Default, PartialEq, Eq)]";

/// `(rust_field_name, rust_field_type)` pairs inside `pub struct NAME { … }`,
/// in source order. Skips a field's own doc-comment lines, so a field
/// carrying one (`WtGitFailureReceipt::git_exit_code`) does not shift the
/// parse.
fn struct_fields<'a>(module: &'a str, name: &str) -> Vec<(&'a str, &'a str)> {
    let marker = format!("pub struct {name} {{");
    let start = module
        .find(&marker)
        .unwrap_or_else(|| panic!("no `pub struct {name}` in the generated module"));
    let body = &module[start + marker.len()..];
    let end = body.find("\n}\n").expect("unterminated struct");
    body[..end]
        .lines()
        .filter(|l| l.trim_start().starts_with("pub "))
        .map(|l| {
            let l = l.trim();
            let l = l.strip_prefix("pub ").expect("filtered for `pub ` prefix");
            let l = l.trim_end_matches(',');
            let (field, ty) = l.split_once(':').expect("field line must be `name: Type`");
            (field.trim(), ty.trim())
        })
        .collect()
}

/// Variant texts inside `pub enum NAME { … }`, in source order — e.g.
/// `"SourceRef(WtGitRef)"`, `"RequireClean"`.
fn enum_variants<'a>(module: &'a str, name: &str) -> Vec<&'a str> {
    let marker = format!("pub enum {name} {{");
    let start = module
        .find(&marker)
        .unwrap_or_else(|| panic!("no `pub enum {name}` in the generated module"));
    let body = &module[start + marker.len()..];
    let end = body.find("\n}\n").expect("unterminated enum");
    body[..end]
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with("///"))
        .map(|l| l.trim_end_matches(','))
        .collect()
}

/// The doc/derive/`#[core(name = …)]` text immediately preceding a
/// `pub struct NAME {` / `pub enum NAME {` declaration — bounded by the
/// nearest preceding blank line, which is how every type is separated in the
/// emitted module.
fn type_prelude<'a>(module: &'a str, marker: &str) -> &'a str {
    let start = module
        .find(marker)
        .unwrap_or_else(|| panic!("no `{marker}` in the generated module"));
    let prelude_start = module[..start].rfind("\n\n").map_or(0, |i| i + 2);
    &module[prelude_start..start]
}

#[allow(clippy::too_many_arguments)]
fn assert_struct(
    module: &str,
    wire_name: &str,
    hs_name: &str,
    derive_line: &str,
    needs_core_name: bool,
    fields: &[(&str, &str)],
) {
    let marker = format!("pub struct {wire_name} {{");
    let prelude = type_prelude(module, &marker);
    assert!(
        prelude.contains(derive_line),
        "{wire_name}: expected derive line `{derive_line}` in:\n{prelude}"
    );
    let core_attr = format!("#[core(name = \"{hs_name}\")]");
    assert_eq!(
        prelude.contains(&core_attr),
        needs_core_name,
        "{wire_name}: #[core(name = \"{hs_name}\")] presence mismatch in:\n{prelude}"
    );
    assert_eq!(
        struct_fields(module, wire_name),
        fields,
        "{wire_name}: field name/type/order mismatch"
    );
}

fn assert_enum(module: &str, wire_name: &str, derive_line: &str, variants: &[&str]) {
    let marker = format!("pub enum {wire_name} {{");
    let prelude = type_prelude(module, &marker);
    assert!(
        prelude.contains(derive_line),
        "{wire_name}: expected derive line `{derive_line}` in:\n{prelude}"
    );
    assert!(
        !prelude.contains("#[core(name"),
        "{wire_name}: an enum must never carry #[core(name = …)] — its data \
         constructors ARE its variant names"
    );
    assert_eq!(
        enum_variants(module, wire_name),
        variants,
        "{wire_name}: variant name/order mismatch"
    );
}

/// Every field/variant, in order, transcribed by hand from
/// `tidepool-bridge-effects/src/lib.rs`'s `WtWorktreeId`..`WtWorktreeSummary`
/// block (lines ~105-232 at the time of writing). See this file's header doc
/// for why that transcription — not the generator's own output — is what this
/// test proves against.
#[test]
fn worktree_wire_types_match_the_hand_written_block_field_for_field() {
    let worktree = effects::worktree::worktree();
    let module = wire_rs::file(&worktree).contents;

    assert_struct(
        &module,
        "WtWorktreeId",
        "WorktreeId",
        WIRE,
        true,
        &[("raw", "String")],
    );
    assert_struct(
        &module,
        "WtGitOid",
        "GitOid",
        WIRE,
        true,
        &[("raw", "String")],
    );
    assert_struct(
        &module,
        "WtGitRef",
        "GitRef",
        WIRE,
        true,
        &[("raw", "String")],
    );
    assert_struct(
        &module,
        "WtBranchName",
        "BranchName",
        WIRE,
        true,
        &[("raw", "String")],
    );

    assert_enum(
        &module,
        "WtWorktreeSource",
        WIRE,
        &[
            "SourceCurrentRepository",
            "SourceRef(WtGitRef)",
            "SourceWorktree(WtWorktreeId)",
        ],
    );

    assert_enum(
        &module,
        "WtDirtyPolicy",
        WIRE_COPY,
        &["RequireClean", "AllowDirtySnapshot"],
    );

    assert_struct(
        &module,
        "WtWorktreeSpec",
        "WorktreeSpec",
        WIRE,
        true,
        &[
            ("spec_source", "WtWorktreeSource"),
            ("spec_label", "String"),
            ("spec_dirty_policy", "WtDirtyPolicy"),
        ],
    );

    assert_enum(
        &module,
        "WtInProgressKind",
        WIRE_COPY,
        &[
            "InProgressMerge",
            "InProgressRebase",
            "InProgressCherryPick",
            "InProgressRevert",
            "InProgressBisect",
        ],
    );

    assert_struct(
        &module,
        "WtDirtySummary",
        "DirtySummary",
        WIRE_DEFAULT,
        true,
        &[
            ("staged", "Vec<String>"),
            ("unstaged", "Vec<String>"),
            ("untracked", "Vec<String>"),
            ("ignored_excluded", "i64"),
        ],
    );

    assert_struct(
        &module,
        "WtGitFailureReceipt",
        "GitFailureReceipt",
        WIRE,
        true,
        &[
            ("git_args", "Vec<String>"),
            ("git_cwd", "String"),
            ("git_exit_code", "Option<i64>"),
            ("git_stdout", "String"),
            ("git_stderr", "String"),
        ],
    );

    assert_struct(
        &module,
        "WtWorktreeReceipt",
        "WorktreeReceipt",
        WIRE,
        true,
        &[
            ("tree_id", "WtWorktreeId"),
            ("cwd", "String"),
            ("branch", "WtBranchName"),
            ("source_head", "WtGitOid"),
            ("snapshot_ref", "Option<WtGitRef>"),
            ("created_at", "i64"),
        ],
    );

    assert_struct(
        &module,
        "WtWorktreeHandle",
        "WorktreeHandle",
        WIRE,
        true,
        &[("handle_receipt", "WtWorktreeReceipt")],
    );

    assert_struct(
        &module,
        "WtWorktreeSummary",
        "WorktreeSummary",
        WIRE,
        true,
        &[
            ("summary_receipt", "WtWorktreeReceipt"),
            ("present", "bool"),
        ],
    );
}

// ---------------------------------------------------------------------------
// has_wire_types / module_index
// ---------------------------------------------------------------------------

#[test]
fn exec_and_journal_have_no_wire_types() {
    assert!(!wire_rs::has_wire_types(&effects::exec::exec()));
    assert!(!wire_rs::has_wire_types(&effects::journal::journal()));
}

#[test]
fn module_index_lists_only_effects_with_wire_types() {
    let described = effects::all_described();
    let index = wire_rs::module_index(&described).contents;

    assert!(index.contains("pub mod worktree;"));
    assert!(index.contains("pub use worktree::*;"));
    assert!(!index.contains("pub mod exec;"));
    assert!(!index.contains("pub mod journal;"));
}
