load("@prelude//:rules.bzl", "export_file")

export_file(name = "package_json", src = "package.json", out = "package.json", visibility = ["PUBLIC"])
export_file(name = "package_lock", src = "package-lock.json", out = "package-lock.json", visibility = ["PUBLIC"])
