[package]
name = "tidepool-effect"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Effect system and handlers for Tidepool prepared execution"
readme = "../../README.md"

[dependencies]
tidepool-repr.workspace = true
tidepool-bridge.workspace = true
frunk.workspace = true
thiserror.workspace = true
parking_lot.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
