{-# LANGUAGE OverloadedStrings #-}
-- | Pure layout. Inspection retains a lazy tree; no view owns runtime authority.
module Tidepool.View.Types (View(..), ImageFormat(..), ImageData(..), SvgDocument(..), viewTree) where
import Prelude
import Data.Text (Text)
import Tidepool.Inspection.Tree

data View = PlainText Text | Markdown Text | Row [View] | Column [View]
  | Caption View Text | Image ImageData Text | Vector SvgDocument | Inspection DisplayTree
-- | Encoded immutable bytes. The host validates encoding and enforces byte limits.
data ImageFormat = PNG | JPEG | WebP deriving (Eq, Show)
data ImageData = ImageData ImageFormat Text deriving (Eq, Show)
-- | Explicit SVG source, generated by any ordinary SVG library. Construction
-- identifies the format; the host parser validates it before passive rendering.
newtype SvgDocument = SvgDocument Text deriving (Eq, Show)

viewTree :: View -> DisplayTree
viewTree (PlainText t) = TextLeaf t
viewTree (Markdown t) = TextLeaf t
viewTree (Row xs) = Concat (map viewTree xs)
viewTree (Column xs) = Concat (concatMap (\v -> [viewTree v, LineBreak]) xs)
viewTree (Caption v t) = Concat [viewTree v, LineBreak, TextLeaf t]
viewTree (Image _ alt) = TextLeaf alt
viewTree (Vector _) = TextLeaf "<svg>"
viewTree (Inspection tree) = tree
